### ISSUE TITLE
generic/ltp.py default removed in latest ltp

### ISSUE THREAD

**Issue by jallen-amd** [avocado-framework-tests/avocado-misc-tests#1030]
The default ltp script used in generic/ltp.py (runltplite.sh) has been removed in the following commit to ltp:
https://github.com/linux-test-project/ltp/commit/e34ecfcd85bd067428d28187ecdb21c593216996

If no alternative test script is provided, the test is broken. A new default test script will need to be chosen.

**Comment by PraveenPenguin** [comment]
@jallen-amd  thanks for pointing issue #1031 will address this issue

**Comment by PraveenPenguin** [comment]
closing this issue as issue fixed in master
