### ISSUE TITLE
Changing test scripts from Python2 to Python2 and Python3

### ISSUE THREAD

**Issue by nasastry** [avocado-framework-tests/avocado-misc-tests#1078]
From https://pythonclock.org 
Python 2.7 will not be maintained past 2020 and remaining time is 8 months 21 days.

So to be compatible with Python2 and Python3 we need to change our test scripts. The effort estimated is around "+ 1011 -189" (adding 1011 lines of code and removing 189 lines of code).

Approach1:
More than changing code, we need to test the scripts. I can change all the scripts at once. But testing the scripts takes time.

Approach2:
Change the code in one folder example: `cpu/*.py`, test them properly and merge. Later jump in to another folder.

End goal is to run test scripts on Python2 or Python3 with out any test script errors.

Let me know your views. Thanks in advance.

**Comment by nasastry** [comment]
@PraveenPenguin @clebergnu @ldoktor Please let me know your views on this issue. Thank you for your support.

**Comment by clebergnu** [comment]
@nasastry I'm not able to tell you what's the best approach, but I can share what we did for Avocado itself.

For Avocado we added source-level support for both Python 2 and Python 3 (concurrently) by using the `six` portability library helper.  Now, recently (post 69.0 LTS release), we dropped all (hopefully) six and Python 2 compatibility code.

Maybe you could create a tag or branch that people can use for Python 2, and then switch the master branch to support Python 3 (given that the clock is ticking fast).

**Comment by nasastry** [comment]
@clebergnu Thanks for your quick feedback and suggestion.
I have gone through `official porting guide: https://docs.python.org/3/howto/pyporting.html`

And planning to have Python2 and Python3 support for these test scripts by that it can run on older Operating System(s).

**Comment by PraveenPenguin** [comment]
@nasastry as based on effort we can have two approach
1- same test script has both the support 
2-  we have tag a python2 support branch and master will support python3 that make easier way 

may we need help here as self volunteer  mode to have both support 
@narasimhan-v your thought will also help here

**Comment by narasimhan-v** [comment]
@nasastry do you have the changes handy ? or any way for us to find those ? that will help us come up with better suggestions.

**Comment by nasastry** [comment]
> @nasastry do you have the changes handy ? or any way for us to find those ? that will help us come up with better suggestions.

@narasimhan-v I have the patch, but not tested. If someone wants to have a look at it, I can post as a RFC.

**Comment by PraveenPenguin** [comment]
@nasastry cool i think send as RFC than we have more eyes on that

**Comment by narasimhan-v** [comment]
@nasastry Yes, please

**Comment by PraveenPenguin** [comment]
closing  as most of the test case moved to python3
