### ISSUE TITLE
can sosreport and supportconfig become a single test ?

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework-tests/avocado-misc-tests#1202]
Can we handle supported distros and respective commands inside a single test ?

**Comment by PraveenPenguin** [comment]
@narasimhan-v ah I miss this issue, yes that is the right approach

**Comment by harish-24** [comment]
@narasimhan-v @PraveenPenguin  I think from outside both more or less is meant to do the same thing. From test case implementation which we currently have I guess it is going to be independent of each other anyways. If we can find a commonality then we can merge both.

**Comment by narasimhan-v** [comment]
The reason I asked is not code commonality. I just did not want too many similar tests in the cfg file. So, if we merge both into single script (which calls one of these 2 functions based on distro), I have my requirement met. If that is not possible, we can deal that with no_run_test.

**Comment by PraveenPenguin** [comment]
@Pavithra1602 @kalshett can you please comment on this issue

**Comment by PraveenPenguin** [comment]
@narasimhan-v we had a discussion and what you mention we can mention in no_run for SLES and RHEL where it not applicable

**Comment by narasimhan-v** [comment]
Sure

**Comment by abdhaleegit** [comment]
done
