### ISSUE TITLE
kernel/kernbench.py found errors while building vmlinux kernel.

### ISSUE THREAD

**Issue by Joshhsi** [avocado-framework-tests/avocado-misc-tests#1262]
While running the test case kernel/kernbench.py, there is an error occurred during the process of building a vmlinux kernel.

The error message is as follows :
make[1]: *** No rule to make target 'certs/rhel.pem' , needed by 'certs/x509_certificate_list' . Stop.

And I've learned that the problem could be solved by comment out the lines CONFIG_SYSTEM_TRUSTED_KEY and CONFIG_MODULE_SIG_KEY in boot/config-4.18.0-80.7.2.el8_0.x86_64.

So the olddefconfig would copy the config that I modified and pass the test.
The concern is - is it a reasonable workaround to pass the test?

**Comment by PraveenPenguin** [comment]
@Joshhsi yes that is valid work around as kernbench test is like a  work load as kernel building and in test we are capturing time of kernel build operation ,is this ok to you  send PR as fix let me know either case i will do

**Comment by Joshhsi** [comment]
@PraveenPenguin Thanks for clarifying my thought, issue closed.

**Comment by PraveenPenguin** [comment]
@Joshhsi sure , so are you going to send fix ?

**Comment by kyle-ibm** [comment]
@PraveenPenguin we seem to be hitting this same issue in py2-lts branch
```
[stderr] make[2]: *** No rule to make target `certs/rhel.pem', needed by `certs/x509_certificate_list'.  Stop.
[stderr] make[1]: *** [certs] Error 2
Command '/usr/bin/time -o /var/tmp/avocado_Gdocr6/avocado_job_pSQT8F/6-kernbench.py_Kernbench.test_long-default-custom-636c/linux-master/time_file make -j 1 vmlinux' finished with 2 after 312.751744032s
[stderr] make: *** [sub-make] Error 2

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/core/test.py:844
Traceback (most recent call last):
  File "/root/tests/tests/avocado-misc-tests/kernel/kernbench.py", line 133, in test
    self.time_build(self.threads, timefile, "")
  File "/root/tests/tests/avocado-misc-tests/kernel/kernbench.py", line 60, in time_build
    self.fail("No vmlinux found, kernel build failed")
  File "/usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/core/test.py", line 1030, in fail
    raise exceptions.TestFail(message)
TestFail: No vmlinux found, kernel build failed
```

**Comment by PraveenPenguin** [comment]
@kyle-ibm sure we need to Backport #1267 this fix to py2-lts , let it first merge in master later we will adopt in py2-lts

**Comment by PraveenPenguin** [comment]
@kyle-ibm #1338 will fix above issue in python2 will wait for merge this PR
