### ISSUE TITLE
PowerNV detection not updated in py2-lts branch

### ISSUE THREAD

**Issue by kyle-ibm** [avocado-framework-tests/avocado-misc-tests#1302]
Seems like in master branch, most python files have updated the PowerNV detection code to this
```
IS_POWER_NV = 'PowerNV' in open('/proc/cpuinfo', 'r').read()
```
However, in the py2-lts branch, most PowerNV detection code is still this
```
IS_POWER_NV = 'PowerNV' in cpu._get_cpu_info()
```
which doesn't detect PowerNV systems correctly and causes tests to be skipped erroneously

**Comment by nasastry** [comment]
@PraveenPenguin @narasimhan-v @harish-24 
Can any one of you help here. Thanks!!

**Comment by PraveenPenguin** [comment]
@kyle-ibm thanks for reporting, let me check how we can achieve this as there is two way 
1 
a- 69 lts need fix and the same fix can be applied in avocado master (that fixed wider way )
b- and  detect PowerNV systems  
```
IS_POWER_NV = 'PowerNV' in cpu._get_cpu_info()
```
in master branch 

2- patch  py2-lts as same as a master branch, 
will update here soon with a solution

**Comment by abdhaleegit** [comment]
no more supporting python2
