### ISSUE TITLE
lpm_basic code flow discussion

### ISSUE THREAD

**Issue by kalshett** [avocado-framework-tests/avocado-misc-tests#1319]
Background: make lpm basic code separate, use vnic lpm code as baseline and remove vnic related code and make simple lpm_basic code ready. This si required for lpm CI where initial CI will be setup with basic lpm code.

lpm vnic code for ref: https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/io/net/virt-net/lpm.py

This issue is opened for discussion on lpm_basic.py flow although code is mostly replica of vnic except for vnic portion removed to make it 2 separate functionality testing.

**Comment by abdhaleegit** [comment]
Now we have basic and vnic lpm support in testcase
