### ISSUE TITLE
packages.py FAIL with "opal-prd package is not installed by default"

### ISSUE THREAD

**Issue by alfredyswu** [avocado-framework-tests/avocado-misc-tests#1385]
Test packages.py with latest Redhat OS 4.14.0-115.13.1.el7a.ppc64le
Result will show  "TestFail: 1 package(s) not installed by default" and "opal-prd package is not installed by default"

The opal-prd.ppc64le  is "rhel-7-for-power-9-rpms" instead of "anaconda/7.6 "
Manually run the command "yum list installed | grep opal-prd | tail -1"

_[root@mihawk-sut1-nvmeg4 results]# yum list installed | grep opal-prd | tail -1
opal-prd.ppc64le                  6.0.4-5.el7_6         @rhel-7-for-power-9-rpms
[root@mihawk-sut1-nvmeg4 results]#_

Verify this command on 4 systems and result is same.

[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3808881/job.log)

_Running 'yum list installed | grep powerpc-utils | tail -1'
[stdout] powerpc-utils-python.noarch 1.2.1-9.el7 @anaconda/7.6 
Command 'yum list installed | grep powerpc-utils | tail -1' finished with 0 after 0.600518941879s
powerpc-utils package is installed by default
Running 'yum list installed | grep ppc64-diag | tail -1'
[stdout] ppc64-diag.ppc64le 2.7.4-3.el7 @anaconda/7.6 
Command 'yum list installed | grep ppc64-diag | tail -1' finished with 0 after 0.598685979843s
ppc64-diag package is installed by default
Running 'yum list installed | grep lsvpd | tail -1'
[stdout] lsvpd.ppc64le 1.7.9-1.el7 @anaconda/7.6 
Command 'yum list installed | grep lsvpd | tail -1' finished with 0 after 0.612447023392s
lsvpd package is installed by default
Running 'yum list installed | grep opal-prd | tail -1'
[stdout] opal-prd.ppc64le 6.0.4-5.el7_6 @rhel-7-for-power-9-rpms
Command 'yum list installed | grep opal-prd | tail -1' finished with 0 after 0.596739053726s
**opal-prd package is not installed by default**
Running 'yum list installed | grep lshw | tail -1'
[stdout] lshw.ppc64le B.02.18-12.el7 @anaconda/7.6 
Command 'yum list installed | grep lshw | tail -1' finished with 0 after 0.598582029343s
lshw package is installed by default
Running 'yum list installed | grep librtas | tail -1'
[stdout] librtas.ppc64le 2.0.1-2.el7 @anaconda/7.6 
Command 'yum list installed | grep librtas | tail -1' finished with 0 after 0.599004030228s
librtas package is installed by default_

**Comment by shirishaganta** [comment]
The above error indicates that opal-prd package is not installed by default during installation and it is installed from repo <rhel-7-for-power-9-rpms> can you please confirm the same

**Comment by shirishaganta** [comment]
@alfredyswu I have sent a PR to resolve this issue.Once it gets merged,testcase will get pass

**Comment by kyle-ibm** [comment]
@shirishaganta Alfred updates their kernel using RHELs subscription manager and i think that repo is RHELs online repo for power9 systems which updates opal-prd also.
I checked our own system which doesn't have the subscription manager repo setup and this test passes.
