### ISSUE TITLE
sensors.py test CANCEL due to processor's architecture is not yet supported

### ISSUE THREAD

**Issue by alfredyswu** [avocado-framework-tests/avocado-misc-tests#1403]
After run sensors.py test via command "avocado run sensors.py --show-job-log"
Result feedback CANCEL as below:

```
[stdout] **********
[stdout] Your processor's architecture is not yet supported. Beware that sensors-detect might not work properly!
[stdout] **********
...
[stderr] yes: standard output: Broken pipe
Command 'yes | sudo sensors-detect' finished with 0 after 12.9916667938s
[stderr] yes: write error

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/core/test.py:831
Traceback (most recent call last):
File "/root/tests/tests/alfred_1105/avocado-misc-tests/cpu/sensors.py", line 100, in setUp
self.cancel('No sensors found to test !')
File "/usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/core/test.py", line 1057, in cancel
raise exceptions.TestCancel(message)
TestCancel: No sensors found to test !

CANCEL 1-sensors.py:Sensors.test -> TestCancel: No sensors found to test !
```

[sosreport-mihawk-sut1-nvmeg4-2019-11-05_sensors_-lzazokv.tar.xz.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3835646/sosreport-mihawk-sut1-nvmeg4-2019-11-05_sensors_-lzazokv.tar.xz.zip)
[sensors_20191105.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3835649/sensors_20191105.log)
[job-2019-11-05T13.24-1ebf34d_sensors.py.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3835651/job-2019-11-05T13.24-1ebf34d_sensors.py.zip)
[sensors_detect_manually.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3835665/sensors_detect_manually.log)

**Comment by PraveenPenguin** [comment]
@nasastry please have a look

**Comment by alvintpwang** [comment]
It's not a script issue but the system configuration issue.

Here is the steps for manual test. If your manual test is ok, then you can run the script.

Manual steps
===========
1) Check if ibmpowernv kernel is loaded. If it's not loaded, you need to update your kernel
# check if ibmpowernv is loaded
[root@mihawk1p1 hwmon0]# lsmod | grep ibm
ibmpowernv              8249  0

2) start the lm_sensors.service
systemctl start lm_sensors.service

3) detect sensor
yes | sudo sensors-detect

4) Get sensor reading

ex:
sensors
ibmpowernv-isa-0000
Adapter: ISA adapter
Chip 0 Vdd Remote Sense:  +0.79 V  (lowest =  +0.74 V, highest =  +0.79 V)
Chip 0 Vdn Remote Sense:  +0.83 V  (lowest =  +0.83 V, highest =  +0.83 V)
Chip 8 Vdd Remote Sense:  +0.77 V  (lowest =  +0.73 V, highest =  +0.77 V)
Chip 8 Vdn Remote Sense:  +0.67 V  (lowest =  +0.67 V, highest =  +0.67 V)
Chip 0 Vdd:               +0.79 V  (lowest =  +0.77 V, highest =  +0.79 V)
Chip 0 Vdn:               +0.83 V  (lowest =  +0.83 V, highest =  +0.83 V)
Chip 8 Vdd:               +0.77 V  (lowest =  +0.75 V, highest =  +0.77 V)
Chip 8 Vdn:               +0.68 V  (lowest =  +0.68 V, highest =  +0.68 V)
Chip 0 Core 0:            +35.0°C  (lowest = +28.0°C, highest = +38.0°C)
Chip 0 Core 4:            +35.0°C  (lowest = +28.0°C, highest = +38.0°C)
Chip 0 Core 8:            +35.0°C  (lowest = +28.0°C, highest = +39.0°C)
Chip 0 Core 12:           +35.0°C  (lowest = +28.0°C, highest = +39.0°C)
Chip 0 Core 16:           +35.0°C  (lowest = +28.0°C, highest = +37.0°C)
...

**Comment by alfredyswu** [comment]
> It's not a script issue but the system configuration issue.
> 
> Here is the steps for manual test. If your manual test is ok, then you can run the script.
> 
> Manual steps
> 
> 1. Check if ibmpowernv kernel is loaded. If it's not loaded, you need to update your kernel
>    #check if ibmpowernv is loaded
>    [root@mihawk1p1 hwmon0]# lsmod | grep ibm
>    ibmpowernv              8249  0
> 2. start the lm_sensors.service
>    systemctl start lm_sensors.service
> 3. detect sensor
>    yes | sudo sensors-detect
> 4. Get sensor reading
> 
> ex:
> sensors
> ibmpowernv-isa-0000
> Adapter: ISA adapter
> Chip 0 Vdd Remote Sense: +0.79 V (lowest = +0.74 V, highest = +0.79 V)
> Chip 0 Vdn Remote Sense: +0.83 V (lowest = +0.83 V, highest = +0.83 V)
> Chip 8 Vdd Remote Sense: +0.77 V (lowest = +0.73 V, highest = +0.77 V)
> Chip 8 Vdn Remote Sense: +0.67 V (lowest = +0.67 V, highest = +0.67 V)
> Chip 0 Vdd: +0.79 V (lowest = +0.77 V, highest = +0.79 V)
> Chip 0 Vdn: +0.83 V (lowest = +0.83 V, highest = +0.83 V)
> Chip 8 Vdd: +0.77 V (lowest = +0.75 V, highest = +0.77 V)
> Chip 8 Vdn: +0.68 V (lowest = +0.68 V, highest = +0.68 V)
> Chip 0 Core 0: +35.0°C (lowest = +28.0°C, highest = +38.0°C)
> Chip 0 Core 4: +35.0°C (lowest = +28.0°C, highest = +38.0°C)
> Chip 0 Core 8: +35.0°C (lowest = +28.0°C, highest = +39.0°C)
> Chip 0 Core 12: +35.0°C (lowest = +28.0°C, highest = +39.0°C)
> Chip 0 Core 16: +35.0°C (lowest = +28.0°C, highest = +37.0°C)
> ...

Hi Alvin,

I follow your steps to test

The command, "yes | sudo sensors-detect" still say no sensors were detected.

```
Sorry, no sensors were detected.
Either your system has no sensors, or they are not supported, or
they are connected to an I2C or SMBus adapter that is not
supported. 
```

But the sensors command seems the sensors reading is normal.

```
ibmpowernv-isa-0000
Adapter: ISA adapter
Chip 0 Vdd Remote Sense: +0.95 V (lowest = +0.68 V, highest = +1.00 V)
Chip 0 Vdn Remote Sense: +0.67 V (lowest = +0.67 V, highest = +0.67 V)
Chip 8 Vdd Remote Sense: +1.02 V (lowest = +0.70 V, highest = +1.03 V)
Chip 8 Vdn Remote Sense: +0.66 V (lowest = +0.66 V, highest = +0.66 V)
Chip 0 Vdd: +0.96 V (lowest = +0.69 V, highest = +1.01 V)
Chip 0 Vdn: +0.68 V (lowest = +0.68 V, highest = +0.68 V)
Chip 8 Vdd: +1.03 V (lowest = +0.71 V, highest = +1.03 V)
Chip 8 Vdn: +0.66 V (lowest = +0.66 V, highest = +0.66 V)
```
[sensor_manually_test.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3905003/sensor_manually_test.log)

**Comment by PraveenPenguin** [comment]
closing this as it seems system configuration issue, @alfredyswu if you still want to pursue feel free to reopen the issue
