### ISSUE TITLE
perf_sdt_probe.py test ERROR and report arguments wrong

### ISSUE THREAD

**Issue by alfredyswu** [avocado-framework-tests/avocado-misc-tests#1405]
After run perf_sdt_probe.py test via command "avocado run perf_sdt_probe.py --show-job-log"
And result get "TypeError: fail() takes at most 2 arguments (3 given)"

Result feedback ERROR as below:

```
Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/core/test.py:844
Traceback (most recent call last):
File "/root/tests/tests/alfred_1105/avocado-misc-tests/perf/perf_sdt_probe.py", line 140, in test
self.add_library()
File "/root/tests/tests/alfred_1105/avocado-misc-tests/perf/perf_sdt_probe.py", line 81, in add_library
self.fail("No SDT markers available in the %s", self.libpthread)
TypeError: fail() takes at most 2 arguments (3 given)

Local variables:
-> self <class 'perf_sdt_probe.PerfSDT'>: 1-perf_sdt_probe.py:PerfSDT.test
Running 'perf buildid-cache -v --remove /lib64/libpthread.so.0'
[stderr] Removing dc25002594f8b955dfb15cb52b9ac31f575759fe /lib64/libpthread.so.0: Ok
Command 'perf buildid-cache -v --remove /lib64/libpthread.so.0' finished with 0 after 0.00352621078491s
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
...
Traceback (most recent call last):

File "/usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/core/test.py", line 938, in _run_avocado
raise test_exception

TypeError: fail() takes at most 2 arguments (3 given)

ERROR 1-perf_sdt_probe.py:PerfSDT.test -> TypeError: fail() takes at most 2 arguments (3 given)
```

Host Kernel Build: 4.14.0-115.13.1.el7a.ppc64le
Host OS: Red Hat Enterprise Linux Server 7.6 (Maipo)

[perf_sdt_probe_manually_20191105.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3835722/perf_sdt_probe_manually_20191105.log)
[job-2019-11-05T15.43-8e6e2f5__perf_sdt_probe.py.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3835723/job-2019-11-05T15.43-8e6e2f5__perf_sdt_probe.py.zip)
[sosreport-mihawk-sut1-nvmeg4-2019-11-05_perf_sdt_probe_-kdsrowk.tar.xz.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3835724/sosreport-mihawk-sut1-nvmeg4-2019-11-05_perf_sdt_probe_-kdsrowk.tar.xz.zip)

**Comment by PraveenPenguin** [comment]
please try latest code base as I am not able to recreate this issue any more
