### ISSUE TITLE
perf_uprobe.py may need to be turned for RHEL 7.6

### ISSUE THREAD

**Issue by alfredyswu** [avocado-framework-tests/avocado-misc-tests#1406]
In the 2nd item of perf_uprobe.py, "test_uprobe_return", run perf_uprobe.py test via command "avocado run perf_uprobe.py --show-job-log" and result ERROR
"CmdError: Command 'perf record -o /var/tmp/tmpsvF27C -e probe_uprobe_test:doit__return -- ./uprobe_test' failed."

[stderr] Error: File /sys/kernel/debug/tracing/events/probe_uprobe_test/doit__return not found.
[stderr] Hint: **Perhaps this kernel misses some CONFIG_ setting to enable this feature?.**

```
Running 'perf record -o /var/tmp/tmpsvF27C -e probe_uprobe_test:doit__return -- ./uprobe_test'
[stderr] event syntax error: 'probe_uprobe_test:doit__return'
Command 'perf record -o /var/tmp/tmpsvF27C -e probe_uprobe_test:doit__return -- ./uprobe_test' finished with 129 after 0.920050859451s
[stderr] \___ unknown tracepoint
[stderr]
[stderr] Error: File /sys/kernel/debug/tracing/events/probe_uprobe_test/doit__return not found.
[stderr] Hint: Perhaps this kernel misses some CONFIG_ setting to enable this feature?.
[stderr]
[stderr] Run 'perf list' for a list of valid events
[stderr]
[stderr] Usage: perf record [<options>] [<command>]
[stderr] or: perf record [<options>] -- <command> [<options>]
[stderr]
[stderr] -e, --event <event> event selector. use 'perf list' to list available events

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/core/test.py:844
Traceback (most recent call last):
File "/root/tests/tests/alfred_1105/avocado-misc-tests/perf/perf_uprobe.py", line 99, in test_uprobe_return
% self.recProbe)
File "/root/tests/tests/alfred_1105/avocado-misc-tests/perf/perf_uprobe.py", line 71, in cmd_verify
return process.run(cmd, shell=True)
File "/usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/utils/process.py", line 1383, in run
raise CmdError(cmd, sp.result)
CmdError: Command 'perf record -o /var/tmp/tmpsvF27C -e probe_uprobe_test:doit__return -- ./uprobe_test' failed.
stdout: ''
stderr: "event syntax error: 'probe_uprobe_test:doit__return'\n \\___ unknown tracepoint\n\nError:\tFile /sys/kernel/debug/tracing/events/probe_uprobe_test/doit__return not
found.\nHint:\tPerhaps this kernel misses some CONFIG_ setting to enable this feature?.\n\nRun 'perf list' for a list of valid events\n\n Usage: perf record [<options>] [<command>]\n or: p
erf record [<options>] -- <command> [<options>]\n\n -e, --event <event> event selector. use 'perf list' to list available events\n"
additional_info: None

Local variables:
-> output <class 'avocado.utils.process.CmdResult'>: command: 'perf probe -x ./uprobe_test doit%return'
exit_status: 0
duration: 0.0046808719635009766
interrupted: False
pid: 34024
encoding: 'ISO-8859-1'
stdout: ''
stderr: 'Added new event:\n probe_uprobe_test:doit (on doit%return in /var/tmp/avocado_ufbYvl/uprobe_test)\n\nYou can now use it in all perf tools, such as:\n\n\tperf record -e probe_uprobe_test:doit -aR sleep 1\n\n'
-> self <class 'perf_uprobe.perfUprobe'>: 2-perf_uprobe.py:perfUprobe.test_uprobe_return
Running 'perf probe -d \*'
[stderr] Removed event: probe_uprobe_test:doit
Command 'perf probe -d \*' finished with 0 after 0.00265717506409s
...
CmdError: Command 'perf record -o /var/tmp/tmpsvF27C -e probe_uprobe_test:doit__return -- ./uprobe_test' failed.
stdout: ''
stderr: "event syntax error: 'probe_uprobe_test:doit__return'\n \\___ unknown tracepoint\n\nError:\tFile /sys/kernel/debug/tracing/events/probe_uprobe_test/doit__return not found.\nHint:\tPerhaps this kernel misses some CONFIG_ setting to enable this feature?.\n\nRun 'perf list' for a list of valid events\n\n Usage: perf record [<options>] [<command>]\n or: perf record [<options>] -- <command> [<options>]\n\n -e, --event <event> event selector. use 'perf list' to list available events\n"
additional_info: None

ERROR 2-perf_uprobe.py:perfUprobe.test_uprobe_return -> CmdError: Command 'perf record -o /var/tmp/tmpsvF27C -e probe_uprobe_test:doit__return -- ./uprobe_test' failed.

```

System information:
Host Kernel Build: 4.14.0-115.13.1.el7a.ppc64le
Host OS: Red Hat Enterprise Linux Server 7.6 (Maipo)
CPU : 12c, 160W, 2.8GHz x 2
MEM : Micron MTA36ASF4G72PZ-2G6E1 x 8

[sosreport-mihawk-sut1-nvmeg4-2019-11-05-_perf_uprobe_ixzmged.tar.xz.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3836298/sosreport-mihawk-sut1-nvmeg4-2019-11-05-_perf_uprobe_ixzmged.tar.xz.zip)
[perf_uprobe_20191105.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3836299/perf_uprobe_20191105.log)
[job-2019-11-05T20.42-26a9644__perf_uprobe.py.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3836313/job-2019-11-05T20.42-26a9644__perf_uprobe.py.zip)

**Comment by PraveenPenguin** [comment]
@nasastry please have a look

**Comment by alfredyswu** [comment]
For perf_uprobe.py, after follow instruction to edit the scipt, test Error.
Test script after edited:
[perf_uprobe_1118.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3858436/perf_uprobe_1118.zip)
TypeError: coercing to Unicode: need string or buffer, NoneType found


Running 'perf probe -d \*'
[stderr] "*" does not hit any event.
Command 'perf probe -d \*' finished with 254 after 0.00705695152283s
[stderr]   Error: Failed to delete events.

Test log:
[perf_uprobe_20191118.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3858435/perf_uprobe_20191118.log)

**Comment by nasastry** [comment]
@alfredyswu I guess you have used the code from https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1408/ not the other one. If this is the case then I will ask the developer to send the proper patch. Thanks for testing.

**Comment by alfredyswu** [comment]
> @alfredyswu I guess you have used the code from #1408 not the other one. If this is the case then I will ask the developer to send the proper patch. Thanks for testing.

@nasastry  Do you mean I should copy the code from "https://github.com/shirishaganta/avocado-misc-tests-1/blob/fix-py2-rh7.6-uprobe/perf/perf_uprobe.py" and run ?
The result still error:
```
ERROR 1-perf_uprobe_1118_raw.py:PerfUprobe.test_uprobe -> TestSetupFail: coercing to Unicode: need string or buffer, NoneType found
ERROR 2-perf_uprobe_1118_raw.py:PerfUprobe.test_uprobe_return -> TestSetupFail: coercing to Unicode: need string or buffer, NoneType found
ERROR 3-perf_uprobe_1118_raw.py:PerfUprobe.test_uprobe_variable -> TestSetupFail: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by Jeff-Chen-IBM** [comment]
@alfredyswu I passed this test case on ibm_remote1 with code copied from link above and keep file name as "perf_uprobe.py".

**Comment by alfredyswu** [comment]
If rename perf_uprobe.py to other name will cause result error.

Perf_uprobe test could pass after modify and keep the same filename.

PASS 1-perf_uprobe.py:PerfUprobe.test_uprobe
PASS 2-perf_uprobe.py:PerfUprobe.test_uprobe_return
PASS 3-perf_uprobe.py:PerfUprobe.test_uprobe_variable
