### ISSUE TITLE
After run ethtool-test.py, it cannot run the command “'ethtool --get-phy-tunable enP1p9s0f0 downshift'”, which causes the test FAILED.

### ISSUE THREAD

**Issue by betty-ju** [avocado-framework-tests/avocado-misc-tests#1456]
[Test Steps]
Run this command: “avocado run avocado-misc-tests/io/net/ethtool_test.py -m /tmp/mux/io_network_fvt_ethtool_test_ethtool_test.yaml --force-job-id 09de1c683a0a3a2041fda02834f5576924a99da5 --job-results-dir 20191110_nic_test_BCM57800__mihawk-sut1-nvmeg4_with_sut2/results”

-

[FW configuration]
BMC: op940.00.mih-1-0-gb27c6fb
PNOR: OP9-v2.4-4.31-prod
OS: Red Hat 7.6 (4.14.0-115.13.1.el7a.ppc64le)

-
[HW configuration]
CPU DD2.3 20core *2
Micron (MTA72ASS8G72PSZ-2S6G1) 64G*32
Seagate Jaguar 400GB *1
Marvell QUAD E'NET 2 Port 10G *1 (slot2)
PSU ACBEL 2000w*2

-

[Test result]
After run ethtool-test.py, it cannot run the command “'ethtool --get-phy-tunable enP1p9s0f0 downshift'”, which causes the test FAILED. The error log is like below:
↓↓↓↓↓
L0626 INFO | Running 'ethtool --get-phy-tunable enP1p9s0f0 downshift'
L0458 DEBUG| [stderr] ethtool: bad command line argument(s)
L0714 INFO | Command 'ethtool --get-phy-tunable enP1p9s0f0 downshift' finished with 1 after 0.000998020172119s
L0458 DEBUG| [stderr] For more information run ethtool -h
↑↑↑↑↑

After manually test it, it is still FAILED like below:
↓↓↓↓↓
[root@mihawk-sut8 ~]# ethtool --get-phy-tunable enP48p1s0f0 downshift
ethtool: bad command line argument(s)
For more information run ethtool -h
[root@mihawk-sut8 ~]#
↑↑↑↑↑

-
The FAILED situation will also happen in many Network Cards.
-
[Expect result]
After run ethtool-test.py, it should be PASS. 
[job.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3896481/job.zip)

**Comment by manvanthar** [comment]
Hi Betty,

       Older Distro's ethtool does not have the option --get-phy-tunable.    Hence the behavior even when run manually.

       For now that error can be ignored as RHEL7.6-ALT's ethtool doesn't have that support.  you could verify that with ethtool --help

**Comment by betty-ju** [comment]
Hi Manu,
Yes, ethtool 4.8 seems not support this command: "'ethtool --get-phy-tunable"
We will follow your suggestion to ignore it, thank you.

**Comment by manvanthar** [comment]
Thanks Betty.  Closing the github issue!
