### ISSUE TITLE
[Linux_FVT] [Perf] make error in perf_events_crash_test.py

### ISSUE THREAD

**Issue by Oracle-Chen** [avocado-framework-tests/avocado-misc-tests#1482]
Description :
make error in perf_events_crash_test.py

Problem description
After run perf_events_crash_test.py test via command "avocado run perf_events_crash_test.py --show-job-log"

make -s -S report error. Utility doesn't install so cancel manually.

START 1-perf_events_crash_test.py:Perf_crashevent.test
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
Not logging /proc/pci (file does not exist)
yum version: 3.4.3
Running 'rpm -q gcc'
[stdout] gcc-4.8.5-36.el7_6.2.ppc64le
Command 'rpm -q gcc' finished with 0 after 0.0093309879303s
Running 'rpm -q make'
[stdout] make-3.82-23.el7.ppc64le
Command 'rpm -q make' finished with 0 after 0.00816416740417s
Running 'rpm -q perf'
[stdout] perf-4.14.0-115.13.1.el7a.ppc64le
Command 'rpm -q perf' finished with 0 after 0.0104310512543s
Fetching https://github.com/deater/perf_event_tests/archive/master.zip -> /root/tests/data/cache/by_location/14b59763b6863a2760ae804cf988dfcf4258d9b0/perf-event.zip.A1bX9D
Retrieved URL "https://github.com/deater/perf_event_tests/archive/master.zip": content-length UNKNOWN, date: "Tue, 05 Nov 2019 08:46:19 GMT", last-modified: "UNKNOWN"
Running 'make -s -S'
[stderr] ar: creating libhelper.a
[stderr] exclude_idle.c: In function 'main':
[stderr] exclude_idle.c:71:4: warning: format '%llx' expects argument of type 'long long unsigned int', but argument 3 has type '__u64' [-Wformat=]
[stderr] fprintf(stderr,"Error opening leader %llx\n",pe.config);
[stderr] ^
[stderr] exclude_idle.c:124:4: warning: format '%llx' expects argument of type 'long long unsigned int', but argument 3 has type '__u64' [-Wformat=]
[stderr] fprintf(stderr,"Error opening leader %llx\n",pe.config);
[stderr] ^
[stderr] exclude_idle.c:176:4: warning: format '%llx' expects argument of type 'long long unsigned int', but argument 3 has type '__u64' [-Wformat=]
[stderr] fprintf(stderr,"Error opening leader %llx\n",pe.config);
[stderr] ^
[stderr] exclude_host.c: In function 'main':
[stderr] exclude_idle.c:229:4: warning: format '%llx' expects argument of type 'long long unsigned int', but argument 3 has type '__u64' [-Wformat=]
[stderr] fprintf(stderr,"Error opening leader %llx\n",pe.config);
[stderr] ^
[stderr] exclude_host.c:65:4: warning: format '%llx' expects argument of type 'long long unsigned int', but argument 3 has type '__u64' [-Wformat=]
...
11/29 retest:
The script run ./run_crash_tests.sh and script no response after below message.
Running './run_crash_tests.sh'
...
[stderr]
[stdout] On unpatched kernels this will cause a panic.
[stderr] This test attempts to write reserved bits in the offcore response registers
[stdout]
[stderr] This could in theory cause a GPF on kernels that do not block this (before 3.9)
[stdout] mmap1=0x7fffb99e0000
[stderr]
[stdout] mmap2=0x7fffb9780000
[stderr] Error opening 5301b7 3fffffffff Invalid argument
[stdout] Open 29 failed
[stdout] Open 29 failed
[stdout] Error opening event: Invalid argument
[stdout] This means the bug won't trigger, kernel probably too old
[stdout] Error opening event: Invalid argument
[stdout] This means the bug won't trigger, kernel probably too old
[stderr] open: No such file or directory
[stderr] perf_event_open: Invalid argument

System is good. No hang nor shutdown.
...

For detail information please check attached log

Reproducible ? yes
Steps to reproduce:
1. Run command "avocado run perf_events_crash_test.py --show-job-log"
2. Check test result

Log Details
(1) sosreport attached: yes
(2) console logs attached: no
(3) Install logs attached: no
(4) dmesg attached: yes

System information:
Host Kernel Build: 4.14.0-115.13.1.el7a.ppc64le
Host OS: Red Hat Enterprise Linux Server 7.6 (Maipo)
BMC: < op940.00-14-0-g8ca35dd >
PNOR: < OP9_v2.4-4.24-prod >
Adapter Firmware:
NVMe controller: Seagate Technology PLC Nytro Flash Storage : driver : nvme (version 1.0)
CPU : 12c, 160W, 2.8GHz x 2
MEM : Micron MTA36ASF4G72PZ-2G6E1 x 8
slot3 : Broadcom 5719
slot4 : Mellanox ROCE EN CONNECTX-5

[make error in perf_events_crash_test.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3917179/make.error.in.perf_events_crash_test.zip)

**Comment by PraveenPenguin** [comment]
@nasastry can you please help us in this issue

**Comment by PraveenPenguin** [comment]
@Oracle-Chen recent commit should fixes some python3 issue can please try this and let us know the result , if it pass please close this issue

**Comment by Oracle-Chen** [comment]
Hi, PraveenPenguin
After use python3 to install Avocado(ver:76.0) in Rhel8.1 to re-test, it suspends while running test, which makes the result failed.

Run command "avocado run perf_events_crash_test.py"
※Test-logs are in attachment:
◎20200227_perf-event-crash_SOL-log：SOL-log from client.
◎job：job-log generated by Avocado
◎sysinfo.20200227-000539.tar：system-information of SUT

[20200227_perf-event-crash.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4261097/20200227_perf-event-crash.zip)

**Comment by Gene-Lo** [comment]
Dear PraveenPenguin,
After use python3 to install Avocado(ver:77.0) in Rhel8.1 to re-test, it still suspends while running test, which makes the result failed.

Run command "avocado run perf_events_crash_test.py"
Here is job-log generated by Avocado:
[20200417-Distro-perf_events_crash_test-job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4543154/20200417-Distro-perf_events_crash_test-job.log)

**Comment by PraveenPenguin** [comment]
@Gene-Lo if you still facing issue , please open a new issue , closing this
