### ISSUE TITLE
lshw.py :Package 'powerpc-ibm-utils' is not Supporting for RHEL and SUSE Versions.

### ISSUE THREAD

**Issue by naveen538** [avocado-framework-tests/avocado-misc-tests#1529]
https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/ras/lshw.py

Job log:
----------
avocado run lshw.py 
JOB ID     : e163ce6af41d81fcf7f3424cf725a9975faef529
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2020-01-28T11.21-e163ce6/job.log
 (01/10) lshw.py:Lshwrun.test_lshw: CANCEL: Fail to install powerpc-ibm-utils required for this test. (2.62 s)
 (02/10) lshw.py:Lshwrun.test_lshw_short: CANCEL: Fail to install powerpc-ibm-utils required for this test. (2.14 s)
 (03/10) lshw.py:Lshwrun.test_lshw_class: CANCEL: Fail to install powerpc-ibm-utils required for this test. (2.14 s)
 (04/10) lshw.py:Lshwrun.test_lshw_verification: CANCEL: Fail to install powerpc-ibm-utils required for this test. (2.15 s)
 (05/10) lshw.py:Lshwrun.test_gen_rep: CANCEL: Fail to install powerpc-ibm-utils required for this test. (2.15 s)
 (06/10) lshw.py:Lshwrun.test_businfo: CANCEL: Fail to install powerpc-ibm-utils required for this test. (2.16 s)
 (07/10) lshw.py:Lshwrun.test_sanitize: CANCEL: Fail to install powerpc-ibm-utils required for this test. (1.75 s)
 (08/10) lshw.py:Lshwrun.test_prod_id_serial: CANCEL: Fail to install powerpc-ibm-utils required for this test. (1.74 s)
 (09/10) lshw.py:Lshwrun.test_lshw_options: CANCEL: Fail to install powerpc-ibm-utils required for this test. (1.75 s)
 (10/10) lshw.py:Lshwrun.test_lshw_notime: CANCEL: Fail to install powerpc-ibm-utils required for this test. (1.74 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 10
JOB TIME   : 21.56 s
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2020-01-28T11.21-e163ce6/results.html

**Comment by PraveenPenguin** [comment]
@naveen538 above commit will fix the issue , please try and if issue fixed for you close this issue

**Comment by naveen538** [comment]
Thanks @PraveenPenguin 
Commit works so closing the issue.

**Comment by naveen538** [comment]
Without fix
---------------
root@ltc-wcwsp3:/home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/ras# avocado run lshw.py
JOB ID     : 169514d0ab21d2fe16240dee3ae54d6fe7562b11
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2020-02-17T22.25-169514d/job.log
 (01/10) lshw.py:Lshwrun.test_lshw: ERROR: 'list' object attribute 'extend' is read-only (1.55 s)
 (02/10) lshw.py:Lshwrun.test_lshw_short: ERROR: 'list' object attribute 'extend' is read-only (1.58 s)
 (03/10) lshw.py:Lshwrun.test_lshw_class: ERROR: 'list' object attribute 'extend' is read-only (1.53 s)
 (04/10) lshw.py:Lshwrun.test_lshw_verification: ERROR: 'list' object attribute 'extend' is read-only (1.53 s)
 (05/10) lshw.py:Lshwrun.test_gen_rep: ERROR: 'list' object attribute 'extend' is read-only (1.54 s)
 (06/10) lshw.py:Lshwrun.test_businfo: ERROR: 'list' object attribute 'extend' is read-only (1.54 s)
 (07/10) lshw.py:Lshwrun.test_sanitize: ERROR: 'list' object attribute 'extend' is read-only (1.56 s)
 (08/10) lshw.py:Lshwrun.test_prod_id_serial: ERROR: 'list' object attribute 'extend' is read-only (1.55 s)
 (09/10) lshw.py:Lshwrun.test_lshw_options: ERROR: 'list' object attribute 'extend' is read-only (1.54 s)
 (10/10) lshw.py:Lshwrun.test_lshw_notime: ERROR: 'list' object attribute 'extend' is read-only (1.54 s)
RESULTS    : PASS 0 | ERROR 10 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 16.13 s
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2020-02-17T22.25-169514d/results.html
root@ltc-wcwsp3:/home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/ras# vi /home/OpTest/avocado-fvt-wrapper/results/job-2020-02-17T22.25-169514d/job.log

With fix
-----------
root@ltc-wcwsp3:/home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/ras# vi lshw.py
root@ltc-wcwsp3:/home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/ras# avocado run lshw.py
JOB ID     : ab805f3a57a0a42d96418d1384ff0920227f6dee
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2020-02-17T22.29-ab805f3/job.log
 (01/10) lshw.py:Lshwrun.test_lshw: PASS (7.52 s)
 (02/10) lshw.py:Lshwrun.test_lshw_short: PASS (8.82 s)
 (03/10) lshw.py:Lshwrun.test_lshw_class: PASS (16.36 s)
 (04/10) lshw.py:Lshwrun.test_lshw_verification: PASS (4.52 s)
 (05/10) lshw.py:Lshwrun.test_gen_rep: PASS (6.04 s)
 (06/10) lshw.py:Lshwrun.test_businfo: PASS (3.54 s)
 (07/10) lshw.py:Lshwrun.test_sanitize: PASS (4.66 s)
 (08/10) lshw.py:Lshwrun.test_prod_id_serial: PASS (4.42 s)
 (09/10) lshw.py:Lshwrun.test_lshw_options: PASS (6.40 s)
 (10/10) lshw.py:Lshwrun.test_lshw_notime: PASS (3.39 s)
RESULTS    : PASS 10 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 66.26 s
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2020-02-17T22.29-ab805f3/results.html
