### ISSUE TITLE
[OP]tcpdump test hung after changing MTU size (timing issue)

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1589]
the tcpdump follows below commands before it gets hung

1. check host and peer interface
Running 'ifup enP19p96s0f0'
22:25:38 DEBUG| [stdout] Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/519)

Running '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -q 102.10.10.193 'ip addr show''

22:25:39 DEBUG| [stdout] 5: enP28p112s0f2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 6000 qdisc mq state UP group default qlen 1000
22:25:39 DEBUG| [stdout]     link/ether 40:f2:e9:5d:7d:4a brd ff:ff:ff:ff:ff:ff
22:25:39 DEBUG| [stdout]     inet 102.10.10.193/24 brd 102.10.10.255 scope global noprefixroute enP28p112s0f2
22:25:39 DEBUG| [stdout]        valid_lft forever preferred_lft forever
22:25:39 DEBUG| [stdout]     inet6 fe80::42f2:e9ff:fe5d:7d4a/64 scope link
22:25:39 DEBUG| [stdout]        valid_lft forever preferred_lft forever

2. now it sets peer MTU 7000 interface

Running '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -q 102.10.10.193 'ip link set enP28p112s0f2 mtu 7000''

22:25:46 DEBUG| [stdout] 5: enP28p112s0f2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 7000 qdisc mq state UP group default qlen 1000
22:25:46 DEBUG| [stdout]     link/ether 40:f2:e9:5d:7d:4a brd ff:ff:ff:ff:ff:ff
22:25:46 DEBUG| [stdout]     inet 102.10.10.193/24 brd 102.10.10.255 scope global noprefixroute enP28p112s0f2
22:25:46 DEBUG| [stdout]        valid_lft forever preferred_lft forever
22:25:46 DEBUG| [stdout]     inet6 fe80::42f2:e9ff:fe5d:7d4a/64 scope link
22:25:46 DEBUG| [stdout]        valid_lft forever preferred_lft forever

3. now it sets MTU 7000 in host interface, but it fails to takes more time to bring the interface up

22:25:46 INFO | Running 'ip link set enP19p96s0f0 mtu 7000'
22:25:46 INFO | Command 'ip link set enP19p96s0f0 mtu 7000' finished with 0 after 0.1916368007659912s
22:25:46 INFO | Running 'ip add show enP19p96s0f0'
22:25:46 DEBUG| [stdout] 3: enP19p96s0f0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 7000 qdisc mq state DOWN group default qlen 1000
22:25:46 INFO | Command 'ip add show enP19p96s0f0' finished with 0 after 0.0030791759490966797s
22:25:46 DEBUG| [stdout]     link/ether 98:be:94:07:3a:68 brd ff:ff:ff:ff:ff:ff
22:25:46 DEBUG| [stdout]     inet 102.10.10.188/24 brd 102.10.10.255 scope global noprefixroute enP19p96s0f0
22:25:46 DEBUG| [stdout]        valid_lft forever preferred_lft forever
22:25:46 DEBUG| [stdout]     inet6 fe80::9abe:94ff:fe07:3a68/64 scope link noprefixroute
22:25:46 DEBUG| [stdout]        valid_lft forever preferred_lft forever

problem: the test do not wait for interface to come up, but immediately start tcmpdump test and it is hung for long time 

22:25:48 INFO | Running 'tcpdump -i enP19p96s0f0 -n -c 10 tcp -w '/home/ioci/logs/io_network/results/job-2020-03-22T12.54-3125666/test-results/43-avocado-misc-tests_io_net_tcpdump.py_TcpdumpTest.test_7000-protocol_tcp-34b6/data/tcpdump''
.
.

**Comment by narasimhan-v** [comment]
@smruti77 can you please check on this ?

**Comment by smruti77** [comment]
ok

**Comment by smruti77** [comment]
@narasimhan-v not getting any timing issue, its working fine.

**Comment by smruti77** [comment]
JOB ID     : e036f6c73d3891ae8e1fbfdbebc8206b278861bc
JOB LOG    : /root/avocado/job-results/job-2020-05-22T02.13-e036f6c/job.log
 (01/21) tcpdump.py:TcpdumpTest.test;1500-generic-45dd: PASS (128.25 s)
 (02/21) tcpdump.py:TcpdumpTest.test;2000-generic-11af: PASS (113.51 s)
 (03/21) tcpdump.py:TcpdumpTest.test;3000-generic-98c8: PASS (111.50 s)
 (04/21) tcpdump.py:TcpdumpTest.test;1500-generic_host-8878: PASS (112.43 s)
 (05/21) tcpdump.py:TcpdumpTest.test;2000-generic_host-6bba: PASS (113.65 s)
 (06/21) tcpdump.py:TcpdumpTest.test;3000-generic_host-6ad7: PASS (113.76 s)
 (07/21) tcpdump.py:TcpdumpTest.test;1500-generic_src-2a16: PASS (163.25 s)
 (08/21) tcpdump.py:TcpdumpTest.test;2000-generic_src-7d79: PASS (163.57 s)
 (09/21) tcpdump.py:TcpdumpTest.test;3000-generic_src-4905: PASS (163.52 s)
 (10/21) tcpdump.py:TcpdumpTest.test;1500-generic_dst-b8d5: PASS (163.48 s)
 (11/21) tcpdump.py:TcpdumpTest.test;2000-generic_dst-9778: PASS (162.76 s)
 (12/21) tcpdump.py:TcpdumpTest.test;3000-generic_dst-3af0: PASS (161.57 s)
 (13/21) tcpdump.py:TcpdumpTest.test;1500-protocol_tcp-f63f: PASS (114.14 s)
 (14/21) tcpdump.py:TcpdumpTest.test;2000-protocol_tcp-8342: PASS (114.43 s)
 (15/21) tcpdump.py:TcpdumpTest.test;3000-protocol_tcp-25e3: PASS (114.58 s)
 (16/21) tcpdump.py:TcpdumpTest.test;1500-protocol_udp-924c: PASS (161.97 s)
 (17/21) tcpdump.py:TcpdumpTest.test;2000-protocol_udp-7822: PASS (163.38 s)
 (18/21) tcpdump.py:TcpdumpTest.test;3000-protocol_udp-30b5: PASS (163.59 s)
 (19/21) tcpdump.py:TcpdumpTest.test;1500-protocol_icmp-ef2b: PASS (114.41 s)
 (20/21) tcpdump.py:TcpdumpTest.test;2000-protocol_icmp-4fd5: PASS (114.81 s)
 (21/21) tcpdump.py:TcpdumpTest.test;3000-protocol_icmp-e14a: PASS (115.28 s)
RESULTS    : PASS 21 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 2848.62 s
JOB HTML   : /root/avocado/job-results/job-2020-05-22T02.13-e036f6c/results.html
