### ISSUE TITLE
[OP] network_stress: Failed to set mtu in peer because MTU difference between host and peer

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1590]
A new observation with many other test like network_stress.py where the script is changing MTU size between host and peer in mid of test combination

while this is happening,at some steps the script does this causing mtu set on peer fails

1. at the start of the the test both host and peer interface has  MTU size 1500
2. now first it changes MTU 2000 in peer over ssh command from host (MTU at host is still 1500 at this step)
3. than it changes MTU size in host interface to MTU 2000 (at this stage both host and peer are at MTU 2000) everthing is fine till now
4. But now after all the ping tests in network_stress, it first changing MTU in host interface back to 1500 (note here)  at this point host is at 1500 and peer is  MTU 2000

this is causing script to fail to ping to peer as MTU difference is blocking the ssh

to fix is to make sure you set back peer interface mtu to 1500 first 
and than set host interface mtu to 1500.  will reslove this issue

**Comment by abdhaleegit** [comment]
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1593/ this fixes above issues

**Comment by narasimhan-v** [comment]
> #1593 this fixes above issues

which was quoted as taken care by -  https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1588

Since 1588 is merged, closing issue
