### ISSUE TITLE
network tests : reset host and peer ip configs when there is link failure (CI)

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1592]
Some times due to crash or real link problem.. you will not be able to ping the test interface.. so have an alternate way to reset when test fails/pass too

the next test can take care of only host interface MTU set.. but cannot set on peer .. becuase when a previous test has left peer interface at MTU 6000 ,, you will never be able to ping/ssh until you either change it manually

for CI continuity we need this reset module ...else the test is blocked at failed test

have a reset_config module in utils which takes public ip, private interface name and private ip, mtu

**Comment by smruti77** [comment]
@abdhaleegit without having reset_config module in utils we can handle this.

**Comment by smruti77** [comment]
shall i do like this,it will be fine if i will chnage in teardown? @manvanthar @narasimhan-v 
```remotehost_public = RemoteHost(self.peer_public_ip, self.peer_user,
                               password=self.peer_password)
self.peer_public_networkinterface = NetworkInterface(self.peer_interface, remotehost_public)

try:
    self.peer_networkinterface.set_mtu('1500')
except:
    if self.peer_public_networkinterface.set_mtu('1500') is not None:
        self.cancel("Failed to set mtu in peer")
```

**Comment by narasimhan-v** [comment]
@smruti77 I think just setting the original IP and mtu to test interface in tearDown() should be enough. No need of cancel or anything else in tearDown()

**Comment by smruti77** [comment]
> @smruti77 I think just setting the original IP and mtu to test interface in tearDown() should be enough. No need of cancel or anything else in tearDown()

@narasimhan-v ok but i am asking through public ip i need to set original mtu in teardown if it is fail through private ip.

**Comment by narasimhan-v** [comment]
yes, thats a good way. But do we get public IP in all tests ?

**Comment by smruti77** [comment]
> yes, thats a good way. But do we get public IP in all tests ?

no,need add one parameter in yaml.

**Comment by narasimhan-v** [comment]
Ah ok

**Comment by narasimhan-v** [comment]
@smruti77 is this done ?

**Comment by smruti77** [comment]
@narasimhan-v this one already merged.

**Comment by narasimhan-v** [comment]
@smruti77 please paste PR link also

**Comment by smruti77** [comment]
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1639
