### ISSUE TITLE
Arm64 Server with 128Gb ram cannot pass memory/numa_test.py case 3: test_thp_compare #3668

### ISSUE THREAD

**Issue by ZYV037** [avocado-framework-tests/avocado-misc-tests#1595]
memory/numa_test.py case 3: test_thp_compare

cpu arch: arm64
kernel: linux4.19.0-arm64-server
server with 128Gb ram cannot pass this check.

root@uos-PC:/home/uos/zhangya/avocado-misc-tests/memory/numa_test.py.data# ./bench_movepages -n 100
src node = 0 and dest node = 1
THP migration time(seconds) (Non THP = 0) = 0.008513
Base migration time(seconds) (Non THP = 1) = 0.016090
Base page migration took more time
[job-2020-03-23T23.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4385158/job-2020-03-23T23.zip)

**Comment by harish-24** [comment]
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1591 Should fix this.

**Comment by PraveenPenguin** [comment]
closing this as the fix is in, @ZYV037 if you still face issue feel free to reopen the issue

**Comment by ZYV037** [comment]
> closing this as the fix is in, @ZYV037 if you still face issue feel free to reopen the issue

applogize. we tested and issue fixed.
