### ISSUE TITLE
DLPAR for veth: write a new test code for dlpar veth 

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1605]
https://github.com/avocado-framework-tests/avocado-misc-tests/tree/master/io/net/virt-net/dlpar_veth.py

**Comment by smruti77** [comment]
@abdhaleegit this new test or need to add in dlpar  ..?

**Comment by abdhaleegit** [comment]
@narasimhan-v planning to have dlpar common test for virtual devices

**Comment by narasimhan-v** [comment]
@abdhaleegit I would recommend having one dlpar test for virtual network (vNIC and veth), and one for virtual storage (vFC and vscsi).

**Comment by smruti77** [comment]
#1620
