### ISSUE TITLE
all disks test : make sure the disks are not part of multipath

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1612]
stop multipath before starting tests on block device /dev/sdX

**Comment by narasimhan-v** [comment]
@Naresh-ibm please look into the issue and suggest ways to solve this.

**Comment by Naresh-ibm** [comment]
@abdhaleegit @narasimhan-v 
if we are using single path name of a multipath disk then it complains this saying disk is in use and cannot run mount it.

That is the reason we have moved all our test from /dev/sdx input to /dev/mapper/mpathX
if any script is using the /dev/sdX, for and if your formatting the disk then "yes" we have flush the multipath and run the test.

please point out if we have any such test which uses /dev/sdX from FC/vFC side.
other block devices I am not sure if they are configuring multipath or not.
NVMe is without multipath AFAIK and IPR/LSI  we have to check which tests are with multipath and which tests are without multipath

**Comment by narasimhan-v** [comment]
Perfectly summarised @Naresh-ibm

**Comment by abdhaleegit** [comment]
closing as in case of mulitpath enabled make use of dev/mapper instead of sdx
