### ISSUE TITLE
After run perf_sdt_probe.py, it shows "SDT marker sdt_libc:memory_mallopt_mmap_max not available", which makes the result FAIL

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1629]
【Test Result】
After run perf_sdt_probe.py, it shows "SDT marker sdt_libc:memory_mallopt_mmap_max not available", which makes the result FAIL. SOL-log like below:

(1/1) perf_sdt_probe.py:PerfSDT.test: FAIL: SDT marker sdt_libc:memory_mallopt_mmap_max not available (5.00 s)
RESULTS : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0 

After re-test it by manual, the result is similar.

【Expect Result】
After run perf_sdt_probe.py, it should show PASS. 

【Test Steps】
Run perf_sdt_probe.py via cmd "avocado run perf_sdt_probe.py"

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.5.1.el8_1.ppc64le

[FW configuration]
BMC: op940.00.mih-5-0-g86f9791c2
PNOR: OP9-v2.4-4.37-prod 

[HW configuration]
CPU DD2.3 16core *2
Micron (MTA36ASF4G72PZ-2G6D1) 32G *16
Seagate Jaguar 400GB *2
PSU ACBEL 2000w *2 

【Test log】
[Test log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4507204/Test.log.zip)

**Comment by PraveenPenguin** [comment]
seems me a bug @nasastry can you please confirm

**Comment by nasastry** [comment]
@PraveenPenguin I have gone through the code and 8.1/8.2 machine ... seems need to load `libc.so` also ... asked interns to do the code changes. 
Thanks!!

**Comment by Gene-Lo** [comment]
@PraveenPenguin @nasastry 
After re-test it in Rhel8.1 with Avocado (Version: 79), the result is PASS.
[20200605-perf_sdt_probe-JOB_LOG.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4733566/20200605-perf_sdt_probe-JOB_LOG.zip)
Many thanks for your help!!
