### ISSUE TITLE
After run perftool.py in Rhel8.1 with Avocado(version:77.0), it shows "CANCEL: gcc-g++ is needed for the test to be run", which makes the result FAIL

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1630]
【Test Result】
After run perftool.py in Rhel8.1 with Avocado(version:77.0), it shows "CANCEL: gcc-g++ is needed for the test to be run", which makes the result FAIL. SOL-log is like below:

(1/1) perftool.py:Perftool.test: CANCEL: gcc-g++ is needed for the test to be run (9.69 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1

However, we can't install "gcc-g++" in Rhel8.1 so far. Please check if Rhel8.1 supports "gcc-g++" and the test of perftool.py.

【Expect Result】
After run perftool.py, it should show PASS. 

【Test Steps】
Run perftool.py via cmd "avocado run perftool.py"

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.5.1.el8_1.ppc64le

[FW configuration]
BMC: op940.00.mih-5-0-g86f9791c2
PNOR: OP9-v2.4-4.37-prod 

[HW configuration]
CPU DD2.3 20core *2
Hynix (HMA82GR7CJR4N-VKT3/F) 16G *32
Seagate Jaguar 400GB *1
PSU ACBEL 2000w *2

【Test log】
[Test log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4507238/Test.log.zip)

**Comment by nasastry** [comment]
@Gene-Lo Thanks for the information. On RHEL 8.1 and above it's `gcc-c++` not the `gcc-g++` will get it corrected and soon send a patch to fix this error.

**Comment by PraveenPenguin** [comment]
closing as the fix is in

**Comment by Gene-Lo** [comment]
Dear @PraveenPenguin 
Excuse me that after we run perftool.py in Rhel8.1 with Avocado(version:79.0), it still shows FAIL.
Please kindly support us. Many thanks!!

《SOL log》
 (1/1) perftool.py:Perftool.test: FAIL: 270 Test failed (1712.12 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

《job log》- Take some logs for example:
L0439 DEBUG| [stdout] -- [ FAIL ] -- perf_buildid :: test_buildid-cache :: update file test (output regexp parsing)
L0439 DEBUG| [stdout] ## [ FAIL ] ## perf_buildid :: test_buildid-cache SUMMARY :: 1 failures found
L0439 DEBUG| [stdout] -- [ FAIL ] -- perf_c2c :: test_basic :: invalid args (command exitcode)
L0439 DEBUG| [stdout] ## [ FAIL ] ## perf_c2c :: test_basic SUMMARY :: 1 failures found
L0439 DEBUG| [stdout] -- [ FAIL ] -- perf_probe :: test_adding_kernel :: listing added probe :: perf probe -l (output regexp parsing)
L0439 DEBUG| [stdout] -- [ FAIL ] -- perf_probe :: test_adding_kernel :: using added probe (output regexp parsing)
[20200601-perftool-JOB_LOG.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4710329/20200601-perftool-JOB_LOG.zip)

《Test log》
[20200601-perftool-JOB_LOG.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4715538/20200601-perftool-JOB_LOG.zip)


【Expect Result】
After run perftool.py, it should show PASS.


【Test Steps】
Run perftool.py via below cmd:
$ yum install gcc-c++
$ avocado run perftool.py


【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.8.1.el8_1.ppc64le

[FW config]
BMC: op940.15.mih-2-0-ga72988e66
PNOR: OP9-v2.4-4.49-prod

[HW config]
CPU DD2.3 20core *2
Micron (MTA18ASF2G72PZ-2G9E1) 16G *4
Seagate Jaguar 400GB *1
PSU ACBEL 2000w *1
Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports *1 @ slot5
Samsung PM1643 (SSD; 3840GB; 2.5"; SAS; 12Gb/s; 1 DWPD; NonSED) *2

**Comment by Gene-Lo** [comment]
After we re-test perftool.py in Rhel8.2 with Avocado (Version: 80), it shows similar fail:

 (1/1) perftool.py:Perftool.test:  FAIL: 262 Test failed (3080.83 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

【Test log】
[20200812-Distro-perftool-job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5081859/20200812-Distro-perftool-job.log)

【Configuration】

[Rhel8.2 Kernel]
4.18.0-193.14.3.el8_2.ppc64le

[FW config]
BMC: op940.00.mih-5-0-g86f9791c2
PNOR: OP9-v2.4-4.37-prod

[HW config]
CPU DD2.3 20core *2
Micron (MTA18ASF2G72PZ-2G9E1) 16G *16
Samsung PM985 960GB *1
PSU ACBEL 2000w *2
Broadcom 9300-8i SAS/SATA HBA PCIe Gen3 x8 LP @ slot5

**Comment by nasastry** [comment]
> After we re-test perftool.py in Rhel8.2 with Avocado (Version: 80), it shows similar fail:
> 
> (1/1) perftool.py:Perftool.test: FAIL: 262 Test failed (3080.83 s)
> RESULTS : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> 
> 【Test log】
> [20200812-Distro-perftool-job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5081859/20200812-Distro-perftool-job.log)
> 
> 【Configuration】
> 
> [Rhel8.2 Kernel]
> 4.18.0-193.14.3.el8_2.ppc64le
> 
> [FW config]
> BMC: op940.00.mih-5-0-g86f9791c2
> PNOR: OP9-v2.4-4.37-prod
> 
> [HW config]
> CPU DD2.3 20core *2
> Micron (MTA18ASF2G72PZ-2G9E1) 16G *16
> Samsung PM985 960GB *1
> PSU ACBEL 2000w *2
> Broadcom 9300-8i SAS/SATA HBA PCIe Gen3 x8 LP @ slot5

@Gene-Lo the above failure is not from the test script. The test script uses test cases from 'https://github.com/rfmvh/perftool-testsuite/', the failures you are seeing in the above are from this test suite. I am working with the maintainer to resolve the failures on ppc64le architecture. Since these tests are for other architecture also that's the reason why it's taking time to resolve. Thanks!!
