### ISSUE TITLE
After run flail.py in Rhel8.1 with Avocado(version:77.0), it shows " ERROR: Command 'sed -i 's/.*-lm.*/& -lm' Makefile' failed.\nstdout: b''\nstderr: b"sed: -e expression #1, char 15: unterminated `s' command\n"\nadditional_info: None ", which makes the result FAIL

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1632]
【Test Result】
After run flail.py in Rhel8.1 with Avocado(version:77.0), it shows " ERROR: Command 'sed -i 's/.*-lm.*/& -lm' Makefile' failed.\nstdout: b''\nstderr: b"sed: -e expression #1, char 15: unterminated `s' command\n"\nadditional_info: None ", which makes the result FAIL. SOL-log is like below:

(1/2) flail.py:Flail.test;xfs-5cf2: ERROR: Command 'sed -i 's/.*-lm.*/& -lm' Makefile' failed.\nstdout: b''\nstderr: b"sed: -e expression #1, char 15: unterminated `s' command\n"\nadditional_info: None (0.92 s)
 (2/2) flail.py:Flail.test;ext4-7988: ERROR: Command 'sed -i 's/.*-lm.*/& -lm' Makefile' failed.\nstdout: b''\nstderr: b"sed: -e expression #1, char 15: unterminated `s' command\n"\nadditional_info: None (0.92 s)
RESULTS    : PASS 0 | ERROR 2 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

【Expect Result】
After run flail.py, it should show PASS. 

【Test Steps】
Run flail.py via cmd "avocado run flail.py -m flail.py.data/flail.yaml"

※ When we adopt the original flail.yaml (containing “ext4” and “xfs”) to run flail.py, the result will be failed. Therefore, we change to test “ext4” and “xfs” in sequence by editing flail.yaml, but all results are still failed. For more details, please refer to below documents:
《20200408_flail.py_Test-SOP & job-logs》
[20200408_flail.py_Test-SOP & job-logs.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4507962/20200408_flail.py_Test-SOP.job-logs.zip)

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.5.1.el8_1.ppc64le

[FW configuration]
BMC: op940.15.mih-1-0-g7983355f4
PNOR: OP9-v2.4-4.40-prod

[HW configuration]
CPU DD2.3 20core *2
Samsung (M393A2K40BB2-CTD) 16G *32
Seagate Jaguar 400GB *2
PSU ACBEL 2000w *2
Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports *1 @ slot10
SSD_Micron 5100 PRO_3840GB; 2.5"; SATA; 6Gb/s; 2.5 DWPD; NonSED *8

**Comment by Gene-Lo** [comment]
Dear @PraveenPenguin 
Today I installed the latest Avocado and re-tested it again, but it still showed FAIL like below:

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 (1/2) flail.py:Flail.test;xfs-5cf2: ERROR: Command 'sed -i 's/.*-lm.*/& -lm' Makefile' failed.\nstdout: b''\nstderr: b"sed: -e expression #1, char 15: unterminated `s' command\n"\nadditional_info: None (0.75 s)
 (2/2) flail.py:Flail.test;ext4-7988: ERROR: Command 'sed -i 's/.*-lm.*/& -lm' Makefile' failed.\nstdout: b''\nstderr: b"sed: -e expression #1, char 15: unterminated `s' command\n"\nadditional_info: None (0.75 s)
RESULTS    : PASS 0 | ERROR 2 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
[20200529_flail_JOB-LOG.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4700018/20200529_flail_JOB-LOG.zip)

Is there anything I have to notice?

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.8.1.el8_1.ppc64le

[FW config]
BMC: op940.15.mih-2-0-ga72988e66
PNOR: OP9-v2.4-4.49-prod

[HW config]
CPU DD2.3 20core *2
Micron (MTA18ASF2G72PZ-2G9E1) 16G *4
Seagate Jaguar 400GB *1
PSU ACBEL 2000w *1
Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports *1 @ slot5
Samsung PM1643 (SSD; 3840GB; 2.5"; SAS; 12Gb/s; 1 DWPD; NonSED) *2

**Comment by Gene-Lo** [comment]
Dear @PraveenPenguin ,
After we re-test it in Rhel8.1 with Avocado(version:80.0), it still shows "ERROR: Command 'sed -i 's/.*-lm.*/& -lm' Makefile' failed."
[20200615_flail_JOB-LOG.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4778516/20200615_flail_JOB-LOG.zip)

1. We view flail.py, and find that the script lacks below section:
https://github.com/PraveenPenguin/avocado-misc-tests/commit/64df53c192d352a3663289636034cfda052963c9
![image](https://user-images.githubusercontent.com/63998174/84627609-c6a58180-af19-11ea-96df-5ef81ed0da02.png)
Hence, we manually add the section in flail.py and then run it, but it still shows "ERROR: Command 'sed -i 's/.*-lm.*/& -lm' Makefile' failed."

2. We try to manually test it by enter "/root/tests/tests/avocado-misc-tests/fs/flail.py.data/flail-0.2.0" and then input "./flail", it will show message but automatically reboot without any kdump log:
[Manual-Test_log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4778614/Manual-Test_log.txt)

Please kindly help us check the issue. Many thanks!!


【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.8.1.el8_1.ppc64le

[FW config]
BMC: op940.15.mih-2-0-ga72988e66
PNOR: OP9-v2.4-4.49-prod

[HW config]
CPU DD2.3 20core *2
Micron (MTA18ASF2G72PZ-2G9E1) 16G *4
Seagate Jaguar 400GB *1
PSU ACBEL 2000w *1
Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports *1 @ slot10
Samsung PM1643 (SSD; 3840GB; 2.5"; SAS; 12Gb/s; 1 DWPD; NonSED) *2

**Comment by Gene-Lo** [comment]
@narasimhan-v @PraveenPenguin 
Today we re-install the latest Avocado (Version: 80.0), and run flail.py again. However, the results are still FAIL.
We run flail.py for 4 times, and weirdly we get 4 different results:

1. Hangup 
After run flail.py, it shows "Hangup", while no "Avocado-Result (PASS ? | ERROR ? | FAIL ? | ...)" shows up.
![Hangup](https://user-images.githubusercontent.com/63998174/89506905-65ee4300-d7fe-11ea-9a57-321b1d0dc779.jpg)
[1.Hangup_SOL-log&Job-log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5033412/1.Hangup_SOL-log.Job-log.zip)

2. Manual-Stop
After run flail.py, it shows "Interrupt requested. Waiting 2 seconds for test to finish (ignoring new Ctrl+C until then)", while "Avocado-Result" shows below:
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 2 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/tests/results/job-2020-08-06T14.25-f2c16c9/results.html
JOB TIME   : 516.25 s
[2.Manual-Stop_SOL-log&Job-log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5033428/2.Manual-Stop_SOL-log.Job-log.zip)

3. Auto-Reboot
After run flail.py, it automatically reboot, while no kernel-log generates.
[3.Auto-Reboot_SOL-log&Job-log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5033438/3.Auto-Reboot_SOL-log.Job-log.zip)

4. Manual-Stop
After run flail.py, it shows "Interrupt requested. Waiting 2 seconds for test to finish (ignoring new Ctrl+C until then)".
"Avocado-Result" shows below, which is different from the result of "2. Manual-Stop":
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 2 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/tests/results/job-2020-08-06T14.25-f2c16c9/results.html
JOB TIME   : 516.25 s
[2.Manual-Stop_SOL-log&Job-log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5033453/2.Manual-Stop_SOL-log.Job-log.zip)


【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.8.1.el8_1.ppc64le

[FW config]
BMC: op940.15.mih-2-0-ga72988e66
PNOR: OP9-v2.4-4.49-prod

[HW config]
CPU DD2.3 20core *2
Micron_36ASF4G72PZ-2G6D1 (32GB) x8
M.2 SAMSUNG PM983 *1
PSU ACBEL 2000w *2
Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports *1 @ slot10
Seagate Skybolt (HDD; 600GB; 2.5"; 10k; SAS; 12Gb/s; 4Kn/512e; SED) *8

**Comment by Gene-Lo** [comment]
Here are sosreport of "3.【Auto-Reboot】" and "4.【Manual-Stop】":
[3.Auto-Reboot_sosreport.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5033592/3.Auto-Reboot_sosreport.zip)
[4.Manual-Stop_sosreport.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5033593/4.Manual-Stop_sosreport.zip)

**Comment by narasimhan-v** [comment]
@Gene-Lo This is new issue, can you please open a new issue and assign to @PraveenPenguin 

Reason being: the original issue here was Makefile editing, which is fixed and thus this issue is closed.

**Comment by Gene-Lo** [comment]
@narasimhan-v @PraveenPenguin 
We have opened a new issue at #1853 
Many thanks for all your kindly support!!
