### ISSUE TITLE
After run network.sh in Rhel8.1, it shows “No such file or directory”, which makes the result FAIL

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1633]
【Test Result】
After run network.sh in Rhel8.1, it shows “No such file or directory”, which makes the result FAIL
After we copy some files to their correct path by manual, the errors of "No such file or directory" never happen. However, there are still some other errors happen, which still make the test-result FAIL.

【Expect Result】
After run network.sh, it should show PASS. 

【Test Steps】
Install LTP, edit network.sh, and then run it via cmd "./network.sh -6mnrstcdaebiTUDSRMF".
For more details about how we install network.sh and adjust files’ path, please refer to below documents:
《20200414_SOP of network.sh Test & SOL-log》
[20200414_SOP of network.sh Test & SOL-log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4508041/20200414_SOP.of.network.sh.Test.SOL-log.zip)

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.8.1.el8_1.ppc64le

[FW configuration]
BMC: op940.15.mih-1-0-g7983355f4
PNOR: OP9-v2.4-4.40-prod

[HW configuration]
CPU DD2.3 20core *2
Micron (MTA18ASF2G72PZ-2G9E1) 16G *32
Seagate Jaguar 400GB *1
PSU ACBEL 2000w *2

**Comment by narasimhan-v** [comment]
@Gene-Lo If this issue is in LTP tests, please open against https://github.com/linux-test-project/ltp
