### ISSUE TITLE
LPM:  test is passing after Errors Warnings were seen in dmesg

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1634]
Please add a check for dmesg and fail the test

**Comment by narasimhan-v** [comment]
depends on v2 of https://github.com/avocado-framework/avocado/pull/2642
Deferring it until then.

**Comment by PraveenPenguin** [comment]
@abdhaleegit  Basic utility added here https://github.com/avocado-framework/avocado/blob/master/avocado/utils/dmesg.py please make use of it, if  you need more functionality feel free to add or list down here we can try to add

**Comment by abdhaleegit** [comment]
The request has been included https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/io/net/virt-net/lpm.py  closing
