### ISSUE TITLE
avocado-misc-tests/io/disk/iozone.py: ERROR: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1642]
https://ltc-jenkins.aus.stglabs.ibm.com/job/ioci/150//consoleText/

iozone is failing with error

 (1/2) avocado-misc-tests/io/disk/iozone.py:IOZone.test;1-args-previous_results-dir-0627:  ERROR: write() argument must be str, not bytes (151.21 s)

**Comment by PraveenPenguin** [comment]
@abdhaleegit #1644 should fix the issue if it works please close this issue

**Comment by PraveenPenguin** [comment]
closing as fix is in
