### ISSUE TITLE
avocado-misc-tests/io/disk/ssd/nvmetest.py : test suite compilation failed

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1643]
make' failed.\nstdout: b'    CC nvme-print.o\n    CC nvme-ioctl.o\n    CC nvme-lightnvm.o\n    CC fabrics.o\n    CC nvme-models.o\n    CC plugin.o\n    CC nvme-status.o\n    CC nvme-filters.o\n    CC nvme-topology.o\n    CC plugins/intel/intel-nvm

https://ltc-jenkins.aus.stglabs.ibm.com/job/ioci/150//consoleText/

**Comment by narasimhan-v** [comment]
Have sent a patch to remove the test for now, will look into the actual failure.

**Comment by narasimhan-v** [comment]
Ignore the above.

Raised an issue https://github.com/linux-nvme/nvme-cli/issues/716
Worked around that in the test and sent a fix
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1743

**Comment by narasimhan-v** [comment]
Fixed via https://github.com/linux-nvme/nvme-cli/issues/716
