### ISSUE TITLE
After run xfstests.py in Rhel8.1 with Avocado(version:77.0), it shows "FAIL: One or more tests failed. Please check the logs", which makes the result failed.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1654]
【Test Result】
After run xfstests.py in Rhel8.1 with Avocado(version:77.0), it shows "FAIL: One or more tests failed. Please check the logs", which makes the result failed. SOL-log is like below:

(1/1) xfstests.py:Xfstests.test;disk_type-fs_ext4-8fdd:  FAIL: One or more tests failed. Please check the logs. (23406.87 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 23406.98 s

After re-test it by manual, the result is like below:

[root@sut4 ~]# ./check  -E /var/tmp/avocado_1cducpr5/exclude -g auto
Warning: need to define parameters for host sut4
       or set variables:
        TEST_DIR TEST_DEV
[root@sut4 ~]#

【Expect Result】
After run xfstests.py, it should show PASS. 

【Test Steps】
Install 2 SSD drives in the SUT, and then run xfstests.py via below cmd:

cd /home
userdel 123456-fsgqa
userdel fsgqa
rm -rf 123456-fsgqa fsgqa
cd /root/tests/tests/avocado-misc-tests/fs
avocado run xfstests.py -m xfstests.py.data/xfstests.yaml

※ When we adopt the original xfstests.yaml (containing “ext4” and “xfs”) to run xfstests.py, the result will be failed. Therefore, we change to test “ext4” and “xfs” in sequence by editing xfstests.yaml, but all results are still failed. For more details, please refer to below documents:
《20200413_xfstests.py_Test-SOP, job-log, Manual-Test-log》
[20200413_xfstests.py_Test-SOP, job-log, Manual-Test-log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4538956/20200413_xfstests.py_Test-SOP.job-log.Manual-Test-log.zip)

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.5.1.el8_1.ppc64le

[FW configuration]
BMC: op940.15.mih-1-0-g7983355f4
PNOR: OP9-v2.4-4.40-prod

[HW configuration]
CPU DD2.3 16 core *2
Micron (MTA18ASF2G72PZ-2G9E1) 16G *32
Seagate Jaguar 400GB *2
PSU ACBEL 2000w *2
Broadcom 9300-8i SAS/SATA HBA PCIe Gen3 x8 LP *1 @ slot1
Micron 5100 PRO (SSD; 3840GB; 2.5"; SATA; 6Gb/s; 2.5 DWPD; NonSED) *2

**Comment by PraveenPenguin** [comment]
@Gene-Lo that should be reported against distro either can be distro issue or test suite  issue, hence closing this
