### ISSUE TITLE
[RFC] Make disk related tests like fio, tiobench, htx, ltp_fs run on a combination of LVs, FSs, RAIDs, raw disks

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework-tests/avocado-misc-tests#1674]

**Comment by narasimhan-v** [comment]
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1675

**Comment by Naresh-ibm** [comment]
@narasimhan-v good thought, we should start working on it.

**Comment by narasimhan-v** [comment]
Please check the PR in the previous comments

**Comment by narasimhan-v** [comment]
Software raid utils: https://github.com/avocado-framework/avocado/pull/3951
Software raid test: https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1783

**Comment by narasimhan-v** [comment]
Software raid enablement for fio: https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1821

**Comment by smruti77** [comment]
lv and software raid for tiobench,bonnie,ltp_fs : #1830

**Comment by Naresh-ibm** [comment]
if we are including the software raid here then in software raid test script we have to keep only SRaid options only. and not any other features. And I feel no need of more yaml files there.

@narasimhan-v  we can also leverage these option for even disktest, rawread, fsstress. I could see htx and ltp_fs is already in list.

**Comment by narasimhan-v** [comment]
Sure @Naresh-ibm we can get this into fsstress and disk test. Rawread should be run only on raw disk, so we can ignore that.

**Comment by narasimhan-v** [comment]
@smruti77 Please work on getting this integrated into disktest and fsstress also, once the other tests are done.

**Comment by smruti77** [comment]
@narasimhan-v ok

**Comment by smruti77** [comment]
FS,LV and Software raid for dbench,fs_mark, iozone,ltp_fsstress : #1834

**Comment by smruti77** [comment]
LV, Software Raid for disktest : #1844

**Comment by smruti77** [comment]
LV,Software Raid for htx_block_devices: #1849

**Comment by PraveenPenguin** [comment]
for raw , read we will create new issue , closing this issue as most of work done
