### ISSUE TITLE
netwok_test : the ip configuration is messing user ip config

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1681]
I have an interface enP19p96s0f2 and I have sysfs ip configuration ifcfg-enP19p96s0f0 created with 
all IP configurations

TYPE=Ethernet
BOOTPROTO=none
NAME=enP19p96s0f0
DEVICE=enP19p96s0f0
ONBOOT=yes
IPADDR=102.10.10.188
NETMASK=255.255.255.0
HWADDR=98:be:94:07:3a:68

After running some network test, the new interface.py utils is messing my config file and in some cases it is deleting my config file. making the interface down

even a Reboot is not restoring my ip config.. which blocks the CI runs

Please make sure the configurations are restored back once the tests are done

**Comment by PraveenPenguin** [comment]
now we have lib avilable we need to adopt in our test

**Comment by smruti77** [comment]
@abdhaleegit this one done.

**Comment by smruti77** [comment]
#1694

**Comment by abdhaleegit** [comment]
closing this as fixed
