### ISSUE TITLE
bridge.py: br0 interface did not clean up after the test

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1682]
br0 bridge interface is not removed at the end of test resulting 

making the interface config messed up, results in next test failures

[root@ltc-zz1b-lp2 network-scripts]# ls
ifcfg-br0 

ip a
8: br0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 42:c5:f0:75:a1:4c brd ff:ff:ff:ff:ff:ff
    inet 102.10.10.188/24 brd 102.10.10.255 scope global noprefixroute br0
       valid_lft forever preferred_lft forever
3: enP19p96s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 98:be:94:07:3a:68 brd ff:ff:ff:ff:ff:ff
    inet 102.10.10.188/24 brd 102.10.10.255 scope global noprefixroute enP19p96s0f0
       valid_lft forever preferred_lft forever
    inet6 fe80::9abe:94ff:fe07:3a68/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

**Comment by smruti77** [comment]
@abdhaleegit i am not getting this issue.

**Comment by abdhaleegit** [comment]
after deleting br0,,  ifup is bringing up the bridge interface

**Comment by abdhaleegit** [comment]
please delete br0 script in  /etc/sysconfig/network-scripts/ifcfg-br0
in teardown

**Comment by smruti77** [comment]
#1701

**Comment by abdhaleegit** [comment]
closing this
