### ISSUE TITLE
io/driver/driver_parameter.py.data: add driver parameter yaml file for all the adapter drivers

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1698]
Please add the yaml file with parameters for all remaining IO cards

1. ibmveth driver 
2. bnx2x 
3. ibmvnic
4. spark ibmnvme
5. ipr 
6. ibmvscsi
7. ibmvfc
8. lpfc
9. qla2xxx
10. be2net

**Comment by vaishnavibhat** [comment]
I have added the yaml files for below NIC adapters till date. 
Slate
Shiner
Austin

**Comment by abdhaleegit** [comment]
closing it as it is already https://github.com/avocado-framework-tests/avocado-misc-tests/issues/1716
