### ISSUE TITLE
ethtool_test.py:Ethtool.test_ethtool;Get-phy-tunable fails (shinner/bnx2x)

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1708]
[root@ltc-zz1b-lp1 ~]# ethtool --get-phy-tunable enP16p1s0f0 downshift
Cannot Get PHY downshift count: Operation not supported
[root@ltc-zz1b-lp1 ~]# echo $?
87

**Comment by smruti77** [comment]
#1740
