### ISSUE TITLE
driver_parameter.py: Handle different driver parameter in a common yaml

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1716]
Each driver/adapter has unique parameters and creating separate yaml for each driver will result in complexity in handling multiple cfgs

so find a common way to handle all the adapter parameter in single yaml

as these params are static and unique include them in yaml for respective driver

**Comment by abdhaleegit** [comment]
@vaishnavibhat this is dependent on https://github.com/avocado-framework-tests/avocado-misc-tests/issues/1698

**Comment by abdhaleegit** [comment]
@vaishnavibhat  Are you working on this ?

**Comment by vaishnavibhat** [comment]
> @vaishnavibhat this is dependent on #1698

Hi Abdul. 
I have executions on 32tb brazos machine this week. I havent started working on the list you provided yet.
ibmveth driver
bnx2x
ibmvnic
spark ibmnvme
ipr
ibmvscsi
ibmvfc
lpfc
qla2xxx
be2net

**Comment by manvanthar** [comment]
This needs some design approach before implementation,  If we merge all of this together.
1.   We will have multiple run skips ,  basically with the current framework it just attempts everthing on the yaml.
2.   How do we differential what driver we are covering,  System may have different config/drivers.

Atleast different yaml helps to customise cfg based on the system/config we have.

Not in the favour of merging all of them into single yaml as this will also affect scenario based approach.

**Comment by narasimhan-v** [comment]
I am also not in favour of merging all yamls. Unnecessary `cancel`s, too bulky test log.

If any of avocado's features solves this issue for us, we can go with it. Else, it is not going to look good, IMO.

I am thinking of solving this problem at a different layer, since this problem originates from there.
avocado-wrapper cfg files is the place where it originates.

**Comment by abdhaleegit** [comment]
One approach would be

1. Remove driver specific test from all the buckets

2. Create driver specific bucket ex :` lpfc.cfg, qla2xx.cfg, austin_tg3.cfg` and add all driver specific test to this bucket

3. Alll driver generic tests should go to a common bucket ex: io_network will have all nic common tests

4. when running test choose  common` io_network`  and driver specific `io_tg3`

**Comment by abdhaleegit** [comment]
@smruti77 will you be taking up this and create yaml for all listed drivers ?

**Comment by PraveenPenguin** [comment]
@abdhaleegit, first of all, I did not really understand the requirement as why we need this as per I know the different system has a different configuration  and  yaml  definition a choice of user as what we have in upstream just a snapshot how a user can leverage test so I don't feel this requirement suitable for upstream @narasimhan-v your thought, please

**Comment by smruti77** [comment]
> @smruti77 will you be taking up this and create yaml for all listed drivers ?

ok

**Comment by narasimhan-v** [comment]
@PraveenPenguin The requirement comes from test cfg files. 
Each IO component can have multiple drivers (which means, driver based tests withhmultiple yamls). To tackle this in test cfgs, we simply can not have multiple runs of same test with different yamls. That would have a huge number of CANCELs, or even run for adapters we don't want to run (DANGEROUS).

So, the solution is to have different cfgs for driver based tests.

**Comment by abdhaleegit** [comment]
@vaishnavibhat is working on this

**Comment by abdhaleegit** [comment]
we do have separate cfgs and yamls created for all different drivers
