### ISSUE TITLE
EEH error injection test for SRIOV VF [CI/newtest]

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1719]

**Comment by smruti77** [comment]
@abdhaleegit @narasimhan-v @vaishnavibhat this will be new test or need to include in existing EEH test.

**Comment by smruti77** [comment]
@abdhaleegit @narasimhan-v @vaishnavibhat @manvanthar  where need to automate this test whether in misc-tests or op-test..?

**Comment by vaishnavibhat** [comment]
Hi @smruti77 , EEH for sriov VF is not supported. We used to do it initially with a hmc macro but after that went deprecated, there has been no new way for EEH for sriov vf

**Comment by narasimhan-v** [comment]
Thanks for the update @vaishnavibhat. I am closing the issue.
