### ISSUE TITLE
LRO test fails for non vnic devices 

### ISSUE THREAD

**Issue by vaishnavibhat** [avocado-framework-tests/avocado-misc-tests#1734]
In test_lro(self) , path = '/sys/class/net/%s/device/name' % self.iface is not available for nic devices.  

(19/99) network_test.py:NetworkTest.test_lro;1500-7aab:  ERROR: [Errno 2] No such file or directory: '/sys/class/net/enP16385p1s0f0/device/name' (69.25 s)
 (20/99) network_test.py:NetworkTest.test_lro;2000-20e2:  ERROR: [Errno 2] No such file or directory: '/sys/class/net/enP16385p1s0f0/device/name' (69.33 s)
 (21/99) network_test.py:NetworkTest.test_lro;3000-dccd:  ERROR: [Errno 2] No such file or directory: '/sys/class/net/enP16385p1s0f0/device/name' (69.24 s)
 (22/99) network_test.py:NetworkTest.test_lro;4000-f420:  ERROR: [Errno 2] No such file or directory: '/sys/class/net/enP16385p1s0f0/device/name' (69.17 s)
 (23/99) network_test.py:NetworkTest.test_lro;5000-3e7c:  ERROR: [Errno 2] No such file or directory: '/sys/class/net/enP16385p1s0f0/device/name' (69.18 s)
 (24/99) network_test.py:NetworkTest.test_lro;6000-d342:  ERROR: [Errno 2] No such file or directory: '/sys/class/net/enP16385p1s0f0/device/name' (69.25 s)
 (25/99) network_test.py:NetworkTest.test_lro;7000-7846:  ERROR: [Errno 2] No such file or directory: '/sys/class/net/enP16385p1s0f0/device/name' (69.25 s)
 (26/99) network_test.py:NetworkTest.test_lro;8000-959a:  ERROR: [Errno 2] No such file or directory: '/sys/class/net/enP16385p1s0f0/device/name' (69.25 s)
 (27/99) network_test.py:NetworkTest.test_lro;9000-a586:  ERROR: [Errno 2] No such file or directory: '/sys/class/net/enP16385p1s0f0/device/name' (69.25 s)

**Comment by abdhaleegit** [comment]
already fixed https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1709

**Comment by abdhaleegit** [comment]
close this @vaishnavibhat
