### ISSUE TITLE
lvsetup failing to find the disk

### ISSUE THREAD

**Issue by Naresh-ibm** [avocado-framework-tests/avocado-misc-tests#1748]
15:25:40 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/disk/lvsetup.py -m /tmp/mux/io_fc_lvsetup_lvsetup.yaml --force-job-id 4c1fb61bdab8aa547d67243516d6f85802fde01e  --job-results-dir /home/ioci/logs/io_fc/results
/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/plugins/run.py:286: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast and keep-tmp. 
  FutureWarning)
Error running method "pre_tests" of plugin "fetchasset": 'Attribute' object has no attribute 'id'
JOB ID     : 4c1fb61bdab8aa547d67243516d6f85802fde01e
JOB LOG    : /home/ioci/logs/io_fc/results/job-2020-05-15T15.25-4c1fb61/job.log
 (01/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test;ext2-3e4c:  ERROR: Error in finding disk space (0.79 s)
 (02/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test;ext3-8c04:  ERROR: Error in finding disk space (0.77 s)
 (03/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test;ext4-96e9:  ERROR: Error in finding disk space (0.71 s)
 (04/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test;xfs-410e:  ERROR: Error in finding disk space (2.03 s)
 (05/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test;btrfs-9546:  CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.31 s)
 (06/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_vg_recreate;ext2-3e4c:  ERROR: Error in finding disk space (0.70 s)
 (07/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_vg_recreate;ext3-8c04:  ERROR: Error in finding disk space (0.76 s)
 (08/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_vg_recreate;ext4-96e9:  ERROR: Error in finding disk space (0.78 s)
 (09/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_vg_recreate;xfs-410e:  ERROR: Error in finding disk space (1.89 s)
 (10/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_vg_recreate;btrfs-9546:  CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.31 s)
 (11/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_lv_snapshot;ext2-3e4c:  ERROR: Error in finding disk space (0.75 s)
 (12/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_lv_snapshot;ext3-8c04:  ERROR: Error in finding disk space (0.77 s)
 (13/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_lv_snapshot;ext4-96e9:  ERROR: Error in finding disk space (0.80 s)
 (14/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_lv_snapshot;xfs-410e:  ERROR: Error in finding disk space (2.06 s)
 (15/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_lv_snapshot;btrfs-9546:  CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.31 s)
 (16/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_create_lv;ext2-3e4c:  ERROR: Error in finding disk space (0.72 s)
 (17/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_create_lv;ext3-8c04:  ERROR: Error in finding disk space (0.73 s)
 (18/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_create_lv;ext4-96e9:  ERROR: Error in finding disk space (0.87 s)
 (19/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_create_lv;xfs-410e:  ERROR: Error in finding disk space (1.95 s)
 (20/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_create_lv;btrfs-9546:  CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.31 s)
 (21/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_delete_lv;ext2-3e4c:  ERROR: Error in finding disk space (0.33 s)
 (22/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_delete_lv;ext3-8c04:  ERROR: Error in finding disk space (0.32 s)
 (23/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_delete_lv;ext4-96e9:  ERROR: Error in finding disk space (0.33 s)
 (24/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_delete_lv;xfs-410e:  ERROR: Error in finding disk space (1.48 s)
 (25/25) avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test_delete_lv;btrfs-9546:  CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.31 s)
RESULTS    : PASS 0 | ERROR 20 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 5
JOB TIME   : 22.10 s
JOB HTML   : /home/ioci/logs/io_fc/results/job-2020-05-15T15.25-4c1fb61/results.html

**Comment by narasimhan-v** [comment]
@Naresh-ibm job.log will help here to debug

**Comment by narasimhan-v** [comment]
@Naresh-ibm With this latest patch
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1784

will close this.
Let me know if this still does not work for you

**Comment by Naresh-ibm** [comment]
working fine. hence closing.
