### ISSUE TITLE
After run dma_memtest.py in Rhel8.1 with Avocado(version:79.0), it shows " FAIL: DMA memory test failed ”

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1751]
【Test Result】
After run dma_memtest.py in Rhel8.1 with Avocado(version:79.0), it shows " FAIL: DMA memory test failed ". 

《SOL-log》
(1/1) dma_memtest.py:DmaMemtest.test;default-default-de9f:  FAIL: DMA memory test failed. (1866.33 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

【Expect Result】
After run dma_memtest.py, it should show PASS. 

【Test Steps】
1. Mount SSD via below cmd:
[root@sut1 memory]# mkfs.ext3 /dev/sda
[root@sut1 memory]# mount /dev/sda /tmp
[root@sut1 memory]# lsblk
NAME          MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0           7:0    0   6.4G  0 loop /opt1
sda             8:0    0   3.5T  0 disk /tmp
nvme0n1       259:0    0 372.6G  0 disk
├─nvme0n1p1   259:1    0     4M  0 part
├─nvme0n1p2   259:2    0     1G  0 part /boot
└─nvme0n1p3   259:3    0 371.6G  0 part
  ├─rhel-root 253:0    0    50G  0 lvm  /
  ├─rhel-swap 253:1    0     4G  0 lvm  [SWAP]
  └─rhel-home 253:2    0 317.6G  0 lvm  /home

2. Change ulimit via cmd “ulimit -n 8192”
3. Run dma_memtest.py via cmd “avocado run dma_memtest.py -m dma_memtest.py.data/dma_memtest.yaml”.

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.8.1.el8_1.ppc64le

[FW configuration]
BMC: op940.15.mih-2-0-ga72988e66
PNOR: OP9-v2.4-4.49-prod

[HW configuration]
CPU DD2.3 20 core *2
DIMM(Micron_MTA18ASF2G72PZ-2G9E1,DDR4,16GB)*4
Seagate Jaguar 400GB *2
PSU ACBEL 2000w *2
Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports *1 @ slot10
Micron 5100 PRO (SSD; 3840GB; 2.5"; SATA; 6Gb/s; 2.5 DWPD; NonSED) *1

【Test log】: job-log
[20200520_Avocado79_dma_memtest_JOB-LOG.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4686110/20200520_Avocado79_dma_memtest_JOB-LOG.txt)

**Comment by harish-24** [comment]
#1752 should fix this issue, It was a hidden python2 -> python3 issue.

**Comment by harish-24** [comment]
This can be closed.

**Comment by narasimhan-v** [comment]
> This can be closed.

Thanks. Closing
