### ISSUE TITLE
Removing main imports from all tests

### ISSUE THREAD

**Issue by harish-24** [avocado-framework-tests/avocado-misc-tests#1767]
After the clarification from https://github.com/avocado-framework/avocado/issues/3897, it is advised that main import and its usage should be removed from all test cases.

Post that none of the tests can be used as standalone. Assuming we are already using avocado command line for all the tests, can we go ahead and remove the main usages from all scripts?

@narasimhan-v @PraveenPenguin Your thoughts here please.

**Comment by narasimhan-v** [comment]
@harish-24 yes please. Would you mind sending a patch ?

**Comment by PraveenPenguin** [comment]
@harish-24 yes please

**Comment by harish-24** [comment]
Closing in favor of #1769
