### ISSUE TITLE
After run avago9361.py in Rhel8.1 with Avocado(version:79.0), it shows " FAIL: Failed to set to off for usefdeonlyencrypt ”

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1776]
【Test Result】
After run avago9361.py in Rhel8.1 with Avocado(version:79.0), it shows " FAIL: Failed to set to off for usefdeonlyencrypt ". 

《SOL-log》
 (1/3) avago9361.py:Avago9361.test_display;cenario-ae06: PASS (2.43 s)
 (2/3) avago9361.py:Avago9361.test_adjustablerates;cenario-ae06: PASS (1.51 s)
 (3/3) avago9361.py:Avago9361.test_set_on_off;cenario-ae06: FAIL: Failed to set to off for usefdeonlyencrypt (1.96 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

After we re-test it by manual, we found that there are 5 cmd are not support:
/root/storcli64 /c0 set copyback=off
/root/storcli64 /c0 set copyback=on
/root/storcli64 /c0 set eghs=off
/root/storcli64 /c0 set eghs=on
/root/storcli64 /c0 show supportssdpatrolread

If we still key in above cmd, the wrong message will show like below:
![Err](https://user-images.githubusercontent.com/63998174/84881495-82a0b100-b0c0-11ea-920a-4c7e6930c9c6.png)

【Expect Result】
After run avago9361.py, it should show PASS. 

【Test Steps】
Put storcli63 in “/root”, and then run avago9361.py via cmd “avocado run avago9361.py -m avago9361.py.data/avago9361.yaml”.

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.5.1.el8_1.ppc64le

[FW configuration]
BMC: op940.15.mih-2-0-ga72988e66
PNOR: OP9-v2.4-4.49-prod

[HW configuration]
CPU DD2.3 16 core *2
DIMM (Micron_MTA18ASF2G72PZ-2G9E1) 16G *4
Seagate Jaguar 400GB *2
PSU ACBEL 2000w *2
Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller *1 @ slot10
Seagate Skybolt(HDD; 600GB; 2.5"; 10k; SAS; 12Gb/s; 4Kn/512e; SED) *8

【Test log】: job-log & Manual-Test-log & storcli64
[avago9361 Test-log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4791535/avago9361.Test-log.zip)

**Comment by narasimhan-v** [comment]
@Gene-Lo 

> After we re-test it by manual, we found that there are 5 cmd are not support:
> /root/storcli64 /c0 set copyback=off
> /root/storcli64 /c0 set copyback=on
> /root/storcli64 /c0 set eghs=off
> /root/storcli64 /c0 set eghs=on
> /root/storcli64 /c0 show supportssdpatrolread

We developed this test code with a certain version of storcli64 binary, and maybe there is a difference with that or certain commands may be outdated or to be run with new options. Can you confirm with Broadcom that this commands are in fact not supported ?
If confirmed, it would help improve the test code with appropriate changes.

>  After run avago9361.py, it should show PASS.

I am not sure, since it is failing manually too.
May be this is a bug ? Checking with Broadcom will help ?

```
[root@sut2 ~]# /root/storcli64 /c0 show usefdeonlyencrypt
Controller = 0
Status = Success
Description = None


Controller Properties :
=====================

---------------------------
Ctrl_Prop            Value 
---------------------------
Use FDE Only Encrypt ON    
---------------------------


[root@sut2 ~]# /root/storcli64 /c0 set usefdeonlyencrypt=off
Controller = 0
Status = Failure
Description = None

Detailed Status :
===============

-----------------------------------------------------------
Ctrl Status Ctrl_Prop Value ErrMsg                   ErrCd 
-----------------------------------------------------------
   0 Failed -         -     endCtlrPropUpdate failed    50 
-----------------------------------------------------------
```

**Comment by Gene-Lo** [comment]
@narasimhan-v 
After search information in Broadcom's website, below commands are incomplete:
![image](https://user-images.githubusercontent.com/63998174/84995281-65cab300-b17e-11ea-8646-e17e5cba1147.png)

Here is the information we found in website:

【For "set copyback"】
※Complete commands:
./storcli64 /c0 show copyback
./storcli64 /c0 copyback=off type=all
./storcli64 /c0 set copyback=on type=all

※Reference: https://www.broadcom.cn/support/knowledgebase/1211161502838/megaraid-controller-still-beeps-after-rebuild-completes-and-vd-i

※Test log:
[set copyback.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4797227/set.copyback.txt)


【For "set eghs"】
※Complete commands:
./storcli64 /c0 show eghs
./storcli64 /c0 set eghs state=off
./storcli64 /c0 set eghs state=on

※Test log:
[set eghs.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4797231/set.eghs.txt)


【For "supportssdpatrolread"】
※No "show" option are found so far, but below commands can work:
./storcli64 /c0 set supportssdpatrolread=on
./storcli64 /c0 set supportssdpatrolread=off

※Test log:
[supportssdpatrolread.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4797250/supportssdpatrolread.txt)

**Comment by narasimhan-v** [comment]
@Gene-Lo Thanks for the report. Please let us know if #1778 works for you.
We currently do not have the avago 9361 adapter.

Please do let us know what happens with `usefdeonlyencrypt`.

Also, adding a bio would help us know you better, and adding mail ID will help get you report and test credit :-)

**Comment by narasimhan-v** [comment]
@Gene-Lo did you get a chance to verify #1778 ?
