### ISSUE TITLE
After run avago9361_vd.py in Rhel8.1 with Avocado(version:79.0), it shows " ERROR: a bytes-like object is required, not 'str' " 

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1777]
【Test Result】
After run avago9361_vd.py in Rhel8.1 with Avocado(version:79.0), it shows " ERROR: a bytes-like object is required, not 'str' ". SOL-log is like below:

 (01/18) avago9361_vd.py:Avago9361.test_createall;Scenario-r0-76fd: PASS (62.25 s)
 (02/18) avago9361_vd.py:Avago9361.test_createall;Scenario-r1-7dbf: PASS (59.94 s)
 (03/18) avago9361_vd.py:Avago9361.test_maxvd;Scenario-r0-76fd: PASS (123.49 s)
 (04/18) avago9361_vd.py:Avago9361.test_maxvd;Scenario-r1-7dbf: PASS (76.05 s)
 **(05/18) avago9361_vd.py:Avago9361.test_init;Scenario-r0-76fd: ERROR: a bytes-like object is required, not 'str' (2.17 s) → It should be PASS.**
 **(06/18) avago9361_vd.py:Avago9361.test_init;Scenario-r1-7dbf: ERROR: a bytes-like object is required, not 'str' (2.45 s) → It should be PASS**.
 (07/18) avago9361_vd.py:Avago9361.test_cc;Scenario-r0-76fd: CANCEL: Test not applicable for Raid0 (0.34 s) → It is expected because our HW doesn’t support the function..
 **(08/18) avago9361_vd.py:Avago9361.test_cc;Scenario-r1-7dbf: ERROR: a bytes-like object is required, not 'str' (2.45 s) → It should be PASS.**
 (09/18) avago9361_vd.py:Avago9361.test_online_offline;Scenario-r0-76fd: CANCEL: Test not applicable for Raid0 (0.33 s) → It is expected because our HW doesn’t support the function..
 **(10/18) avago9361_vd.py:Avago9361.test_online_offline;Scenario-r1-7dbf: ERROR: a bytes-like object is required, not 'str' (2.11 s) → It should be PASS.**
 (11/18) avago9361_vd.py:Avago9361.test_ghs_dhs;Scenario-r0-76fd: CANCEL: Test not applicable for Raid0 (0.36 s) → It is expected because our HW doesn’t support the function..
 **(12/18) avago9361_vd.py:Avago9361.test_ghs_dhs;Scenario-r1-7dbf: ERROR: a bytes-like object is required, not 'str' (2.17 s) → It should be PASS.**
 (13/18) avago9361_vd.py:Avago9361.test_rebuild;Scenario-r0-76fd: CANCEL: Test not applicable for Raid0 (0.35 s) → It is expected because our HW doesn’t support the function..
 **(14/18) avago9361_vd.py:Avago9361.test_rebuild;Scenario-r1-7dbf: ERROR: a bytes-like object is required, not 'str' (2.06 s) → It should be PASS.**
 (15/18) avago9361_vd.py:Avago9361.test_patrolread;Scenario-r0-76fd: PASS (52.37 s)
 (16/18) avago9361_vd.py:Avago9361.test_patrolread;Scenario-r1-7dbf: PASS (52.18 s)
 **(17/18) avago9361_vd.py:Avago9361.test_migrate;Scenario-r0-76fd: ERROR: a bytes-like object is required, not 'str' (4.66 s) → It should be PASS.**
 (18/18) avago9361_vd.py:Avago9361.test_migrate;Scenario-r1-7dbf: CANCEL: Script runs for raid0 (0.62 s) → It is expected because our HW doesn’t support the function..
RESULTS    : PASS 6 | ERROR 7 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 5

After we checked its cmd in job.log, we found that some of them are strange like below:
/root/storcli64 /c0 set offline
/root/storcli64 /c0/15124 show rebuild
/root/storcli64 /c0/15124 add hotsparedrive
/root/storcli64 /c0/15123 set offline
/root/storcli64 /c0/15124 show rebuild
/root/storcli64 /c0/15123 set offline
/root/storcli64 /c0/15124 show rebuild

Here are the parameters we set in avago9361_vd.yaml:
![yaml](https://user-images.githubusercontent.com/63998174/84882318-a1ec0e00-b0c1-11ea-9726-c6d5af62c591.png)

After we re-test above cmd by manual, these cmd are not supported. Please refer to “20200504_avago9361-vd_Manual_Test.txt” in attachment.

【Expect Result】
After run avago9361_vd.py, it should show PASS. 

【Test Steps】
Put storcli63 in “/root”, and then run avago9361_vd.py via cmd “avocado run avago9361_vd.py -m avago9361_vd.py.data/avago9361_vd.yaml”.

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.5.1.el8_1.ppc64le

[FW configuration]
BMC: op940.15.mih-2-0-ga72988e66
PNOR: OP9-v2.4-4.49-prod

[HW configuration]
CPU DD2.3 16 core *2
DIMM (Micron_MTA18ASF2G72PZ-2G9E1) 16G *4
Seagate Jaguar 400GB *2
PSU ACBEL 2000w *2
Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller *1 @ slot10
Seagate Skybolt(HDD; 600GB; 2.5"; 10k; SAS; 12Gb/s; 4Kn/512e; SED) *8

【Test log】: job-log & Manual-Test-log & storcli64
[avago9361_vd Test-log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4791614/avago9361_vd.Test-log.zip)

**Comment by narasimhan-v** [comment]
@Gene-Lo Please check if https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1779 works fine for you.

**Comment by Gene-Lo** [comment]
Dear @narasimhan-v 

After we run avago9361_vd.py in Rhel8.1 with Avocado(version:80.0), the previous bug " ERROR: a bytes-like object is required, not 'str' " is successfully fixed:
![SOL-log](https://user-images.githubusercontent.com/63998174/86901153-cbd3a600-c13e-11ea-87db-c5ed51ef37d8.png)
※Note: The **CANCEL items** "Test not applicable for Raid0" are expected because our HW doesn’t support the function.


However, **Item 17** shows "FAIL: Failed to migrate". We try to re-test it by manual, but the result is still fail.
【Test log】: job-log & Manual-Test-log
[Test log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4889768/Test.log.zip)

Please kindly check why **Item 17** fails. Many thanks!!


【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.8.1.el8_1.ppc64le

[FW configuration]
BMC: op940.15.mih-2-0-ga72988e66
PNOR: OP9-v2.4-4.49-prod

[HW configuration]
CPU DD2.3 20 core *2
DIMM (Micron_MTA18ASF2G72PZ-2G9E1) 16G *16
Seagate Jaguar 400GB *2
PSU ACBEL 2000w *2
Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller *1 @ slot10
Seagate Skybolt(HDD; 600GB; 2.5"; 10k; SAS; 12Gb/s; 4Kn/512e; SED) *7

**Comment by narasimhan-v** [comment]
> However, **Item 17** shows "FAIL: Failed to migrate". We try to re-test it by manual, but the result is still fail.
> 【Test log】: job-log & Manual-Test-log
> [Test log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4889768/Test.log.zip)
> 
> Please kindly check why **Item 17** fails. Many thanks!!

@Gene-Lo If a test works manually, and fails via automation, then we can check it.
If it fails manually too, then it can be a bug. Please check with the vendor of the adapter.

**Comment by Gene-Lo** [comment]
@narasimhan-v 
Today we manually tested it again, and found something strange:

(1) When it just finished "migrate", we input "/root/storcli64 /c0/v0 start migrate type=raid5                    option=add drives=252:5", and the result showed fail:
![image](https://user-images.githubusercontent.com/63998174/86994059-13f2d700-c1d8-11ea-90ab-949d3d4666e0.png)

(2) However, after 2~3 minutes, we input "/root/storcli64 /c0/v0 start migrate type=raid5                    option=add drives=252:5" again, and the result became Success:
![image](https://user-images.githubusercontent.com/63998174/86994166-54eaeb80-c1d8-11ea-9e9d-9caa38bc6dbb.png)

Here is today;s Manual-Test-Log:
[20200709_Manual-Test.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4894361/20200709_Manual-Test.zip)

Please kindly check if the operation of our Manual-Test is corresponding to the operation of avago9361_vd.py.
And please evaluate if the waiting time in the operation of avago9361_vd.py should prolong, in order to make it have enough time to finish "migrate".

Many thanks!!

**Comment by narasimhan-v** [comment]
@Gene-Lo This needs more discussion. Can you open a separate issue for this please.

**Comment by Gene-Lo** [comment]
@narasimhan-v 
The new issue is open: #1817
