### ISSUE TITLE
test return code shouldn't be cancel when feature doesn't exist

### ISSUE THREAD

**Issue by tfauck** [avocado-framework-tests/avocado-misc-tests#1782]
When a feature is not present test should return skip instead of cancel/fail so we can easily track outputs.

**Comment by narasimhan-v** [comment]
@tfauck is there a specific test you have this issue with ?

Also, skip and cancel should mean the same.

**Comment by tfauck** [comment]
let's take a simple example: memory/migrate_pages.py
Code says 
        nodes = memory.numa_nodes_with_memory()
        if len(nodes) < 2:
            self.cancel('Test requires two numa nodes to run.'
                        'Node list with memory: %s' % nodes)
I would prefer to have a return code like skip instead of cancel because the condition to run is not there - The need is to more easily analyse results (using scirpts python or others ) and not spend time on tests which won't run because of the environment....

**Comment by narasimhan-v** [comment]
@tfauck self.skip() is deprecated.

```
commit fc173b9f48c3f7330470c4064683baa4192fff1a
Author: Cleber Rosa <crosa@redhat.com>
Date:   Wed Mar 7 21:14:19 2018 -0500

    Test: remove deprecated skip() method
    
    The skip() method has been deprecated for quite some time.  Let's
    remove it for good and have users using the decorators and cancel()
    instead.
    
    Signed-off-by: Cleber Rosa <crosa@redhat.com>
```

Is there anything specific you want to do in this or list of tests to indicate the states better ?
Please feel free to send a patch for the same.

@PraveenPenguin @harish-24 Your thoughts please.

**Comment by PraveenPenguin** [comment]
i think `skip` and `cancel` denote  same meaning for me on the test run prospective again it is a personal  opinion, user perception how he/she perceive this but I can guaranty one thing as this repository we have adopted same way as `skip` got deprecated long back so maybe string message can be altered but we can continue to use `cancel`

**Comment by harish-24** [comment]
As others already mentioned, skip and cancel are considered same. It ideally means environment is not ready to run the test. It could be because a feature is not supported, a package not able to be installed or even not enough nodes present etc.. 

So all of them are under same category of "environment not ready". If there is any specific use case which is not related to environment, let know here.
