### ISSUE TITLE
bootlist test failing for vfc multipath devices

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1803]
[root@1b-lp1 avocado-fvt-wrapper]# python avocado-setup.py --run-suite host_io_vfc --output-dir /home/ioci/logs/io_vfc --no-deps-check --input-file /root/korg-zz1b-lp1-input.txt
06:06:03 INFO    : Check for environment
06:06:03 INFO    : Creating temporary mux dir
06:06:44 INFO    : 
06:06:44 INFO    : Running Host Tests Suite io_vfc_bootlist_test_bootlist_test_disk
06:06:44 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/common/bootlist_test.py -m /tmp/mux/io_vfc_bootlist_test_bootlist_test_disk.yaml --force-job-id c9d97938098f078d895266bcdfb880b513724a67  --job-results-dir /home/ioci/logs/io_vfc/results
/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/plugins/run.py:285: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast and keep-tmp. 
  FutureWarning)
JOB ID     : c9d97938098f078d895266bcdfb880b513724a67
JOB LOG    : /home/ioci/logs/io_vfc/results/job-2020-07-01T06.06-c9d9793/job.log
 (1/3) avocado-misc-tests/io/common/bootlist_test.py:BootlisTest.test_normal_mode;run-d34e: FAIL: normal bootlist fail (4.95 s)
 (2/3) avocado-misc-tests/io/common/bootlist_test.py:BootlisTest.test_service_mode;run-d34e: FAIL: service bootlist fail (4.91 s)
 (3/3) avocado-misc-tests/io/common/bootlist_test.py:BootlisTest.test_both_mode;run-d34e: FAIL: both bootlist fail (4.86 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 3 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/ioci/logs/io_vfc/results/job-2020-07-01T06.06-c9d9793/results.html
JOB TIME   : 14.87 s

**Comment by Naresh-ibm** [comment]
working fine. below are the supporting logs.





13:00:06 INFO    : Running Host Tests Suite io_vfc_stress_bootlist_test_bootlist_test_disk
13:00:06 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/common/bootlist_test.py -m /tmp/mux/io_vfc_stress_bootlist_test_bootlist_test_disk.yaml --force-job-id 85c2caf3846b6d3e72c33ff7c0db92714d71c9c3  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : 85c2caf3846b6d3e72c33ff7c0db92714d71c9c3
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-02-15T13.00-85c2caf/job.log
 (1/3) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/common/bootlist_test.py:BootlisTest.test_normal_mode;run-bf66: STARTED
 (1/3) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/common/bootlist_test.py:BootlisTest.test_normal_mode;run-bf66: PASS (1.42 s)
 (2/3) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/common/bootlist_test.py:BootlisTest.test_service_mode;run-bf66: STARTED
 (2/3) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/common/bootlist_test.py:BootlisTest.test_service_mode;run-bf66: PASS (1.57 s)
 (3/3) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/common/bootlist_test.py:BootlisTest.test_both_mode;run-bf66: STARTED
 (3/3) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/common/bootlist_test.py:BootlisTest.test_both_mode;run-bf66: PASS (2.05 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-02-15T13.00-85c2caf/results.html
JOB TIME   : 91.68 s
13:01:41 INFO    : 
13:01:41 INFO    :
