### ISSUE TITLE
After run avago9361_vd.py in Rhel8.1 with Avocado(version:80.0), it shows "FAIL: Failed to migrate"

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1817]
After run avago9361_vd.py in Rhel8.1 with Avocado(version:80.0), it shows "FAIL: Failed to migrate"

![1](https://user-images.githubusercontent.com/63998174/87009636-05b4b300-c1f8-11ea-96fe-ac26ad9b1213.png)
※Note: The CANCEL items "Test not applicable for Raid0" are expected because our HW doesn’t support the function.

《job.log》
[20200708-avago9361_vd-JOB_LOG.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4895178/20200708-avago9361_vd-JOB_LOG.zip)

When we manually tested it again, something strange was found:

(1) When it just finished "migrate", we input "/root/storcli64 /c0/v0 start migrate type=raid5 option=add drives=252:5", and the result showed fail:
![2](https://user-images.githubusercontent.com/63998174/87009838-51675c80-c1f8-11ea-97b6-a959aadbbc22.png)

(2) However, after 2~3 minutes, we input "/root/storcli64 /c0/v0 start migrate type=raid5 option=add drives=252:5" again, and the result became Success:
![3](https://user-images.githubusercontent.com/63998174/87009886-62b06900-c1f8-11ea-9be9-6ee3e725bb46.png)

《Manual-Test-Log》
[20200709_Manual-Test.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4895169/20200709_Manual-Test.zip)

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.8.1.el8_1.ppc64le

[FW configuration]
BMC: op940.15.mih-2-0-ga72988e66
PNOR: OP9-v2.4-4.49-prod

[HW configuration]
CPU DD2.3 20 core *2
DIMM (Micron_MTA18ASF2G72PZ-2G9E1) 16G *16
Seagate Jaguar 400GB *2
PSU ACBEL 2000w *2
Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller *1 @ slot10
Seagate Skybolt(HDD; 600GB; 2.5"; 10k; SAS; 12Gb/s; 4Kn/512e; SED) *7

**Comment by manvanthar** [comment]
No this is not an test script issue.  script is doing it right by checking the progress before reporting it as an failed /Pass.     We do not add random sleep.   Even if we did it wont serve the purpose.

This should be an storcli or firmware issue, please check with LSI on expectation of using the drive for migration.

If consistency check is in progress, the right status should be in-progress for Migration and not Failed.    

We haven't seen this problem in the past,  could be the drive type used is either way to big or taking time to complete its consistency check operation.  If it is an pre-requisite for Migrate to check if there are no consistency check in progress, only then it can be added as an condition before Migrate.   But need an confirmation from LSI.

**Comment by Gene-Lo** [comment]
@manvanthar 
Today we alternatively used "**Micron 5100 PRO; SSD; 960GB; 2.5"; SATA; 6Gb/s; 2.5 DWPD; NonSED**" to test avago9361_vd.py again, and the result of **Item 17** still had the same issue, which means that after it finished "migrate", it is necessary to wait for 2~3 minutes, so that the command "**/root/storcli64 /c0/v0 start migrate type=raid5 option=add drives=252:5**" would become Success.

Here is Manual-Test log:
![Manual-log](https://user-images.githubusercontent.com/63998174/87111797-d1df9900-c29c-11ea-96a9-6866e0669760.JPG)
[20200710-avago9361_vd-Micro_5100_PRO_960GB-Manual-Test.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4900566/20200710-avago9361_vd-Micro_5100_PRO_960GB-Manual-Test.zip)

Here is JOB log of avago9361_vd.py:
[20200710-avago9361_vd-Micro_5100_PRO_960GB-JOB.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4900572/20200710-avago9361_vd-Micro_5100_PRO_960GB-JOB.zip)
![JOB-log](https://user-images.githubusercontent.com/63998174/87111881-04899180-c29d-11ea-8d3b-33331fed6bb9.JPG)
※Note:
1. The **CANCEL** items "Test not applicable for Raid0" are expected because our HW doesn’t support the function.
2. It generates 2 new issues "FAIL: Failed to start PR" in **Item 15** & **Item16**. Please check if the issues happen is because we used SSD to test.

In addition, regarding to the comment you replied yesterday "...We haven't seen this problem in the past...". Could you provide the drive-type you used before? So that we would have more references to discuss with LSI. Many thanks!!

**Comment by Naresh-ibm** [comment]
working now. please check and report a new issue if still persistence in your env
