### ISSUE TITLE
Using software_manager.build_dep method for package dependencies 

### ISSUE THREAD

**Issue by harish-24** [avocado-framework-tests/avocado-misc-tests#1822]
Idea is to make use of the `software_manager.build_dep` method to install build dependencies of packages which need building. We usually keep appending package list (for build dependencies) to each test that requires package building. Using this would reduce the overhead of maintaining the packages.

Eg:
```
            deps.extend(['gcc', 'make', 'automake', 'autoconf'])
            if self.dist.name == 'SuSE':
                deps.extend(['libtool',
                             'libkmod-devel', 'libudev-devel', 'systemd-devel',
                             'libuuid-devel-static', 'libjson-c-devel',
                             'keyutils-devel', 'kmod-bash-completion'])
            elif self.dist.name == 'rhel':
                deps.extend(['libtool',
                             'kmod-devel', 'libuuid-devel', 'json-c-devel',
                             'systemd-devel', 'keyutils-libs-devel', 'jq',
                             'parted', 'libtool'])
            for pkg in deps:
                if not self.smm.check_installed(pkg) and not \
                        self.smm.install(pkg):
                    self.cancel('%s is needed for the test to be run' % pkg)
```
gets replaced by
```
        if not self.smm.build_dep('ndctl'):
            self.cancel("Build dependency fail, check source repo config")
```

This would help us easily maintain dependencies, only add-on is to have source repo configured. 
Note: This means that we are leveraging distributions build dependencies for upstream package building.

@narasimhan-v @PraveenPenguin Your thoughts here would be helpful.

**Comment by narasimhan-v** [comment]
@harish-24  `smm.install()` uses native distro package install method, which should take care of dependencies, right ?

**Comment by harish-24** [comment]
@narasimhan-v Those are dependencies of the package, What I meant is dependencies for building the package.

**Comment by narasimhan-v** [comment]
@harish-24 Can you elaborate please. I am not able to understand the problem exactly.

**Comment by harish-24** [comment]
> @harish-24 Can you elaborate please. I am not able to understand the problem exactly.

As indicated in the snippet of description, let us say we have to build a ndctl binary from upstream source and hence we need those set of packages to be installed beforehand for building the binary. Using the `smm.build_dep` we will be able to leverage the SPEC file from the source of the package to find the list of build dependencies of the same (with source repository configured).

Thus avoiding the list of packages to be maintained as part of test. Was I clear?

**Comment by narasimhan-v** [comment]
@harish-24 Yes, very clear in that. So this is just in a small number of tests, right ?

**Comment by harish-24** [comment]
@narasimhan-v yes, but most of those tests have a lot of dependencies.

**Comment by narasimhan-v** [comment]
@harish-24 
If is is easier for test maintenance, we can do this to those specific tests. But we need to make sure this is:

1. Documented in Readme clearly
2. When this is run in an environment like CI, we need some control over the repositories that should be set up. @PraveenPenguin Your take here ?

**Comment by harish-24** [comment]
@narasimhan-v Sound good to me.

**Comment by PraveenPenguin** [comment]
closing this as an avocado resolver addressing this requirement in some cases , as we don't have activity so long
