### ISSUE TITLE
dlpar for veth interface 

### ISSUE THREAD

**Issue by vaishnavibhat** [avocado-framework-tests/avocado-misc-tests#1852]
I have two veth interface on my OS. Based on the dlpar script, I ran the commands manually and see this on my Error. 

SVEA   Physloc
------ --------------------------------------------
ent5   U9040.MR9.133CF0X-V200-C3-T1

SEA                 NO SHARED ETHERNET ADAPTER FOUND

SVEA   Physloc
------ --------------------------------------------
ent9   U9040.MR9.133CF0X-V200-C4-T1

SEA                   ent10
Backing device        ent7
Status                Available
Physloc               U78D4.ND1.CSS10M1-P1-C3-T1

# rmdev -l ent7
Method error (/usr/lib/methods/ucfgcommo):
        0514-062 Cannot perform the requested function because the
                 specified device is busy.

(0) root @ ltczep5-vios2: /home/padmin
# rmdev -l ent9
Method error (/usr/lib/methods/ucfgcommo):
        0514-062 Cannot perform the requested function because the
                 specified device is busy.

(0) root @ ltczep5-vios2: /home/padmin
# rmdev -l ent10
Method error (/usr/lib/methods/ucfgcommo):
        0514-062 Cannot perform the requested function because the
                 specified device is busy.

**Comment by abdhaleegit** [comment]
@vaishnavi it is a phype issue, please open a cq

```
this looks to be phyp issue
# rmdev -l ent10
Method error (/usr/lib/methods/ucfgcommo):
        0514-062 Cannot perform the requested function because the
                 specified device is busy.
```
as the same commands work fine for my similar CI setup


```
SVEA   Physloc
------ --------------------------------------------
ent5   U9009.42A.13C6F1W-V100-C3-T1
SEA                   ent8
Backing device        ent1
Status                Available
Physloc               U78D2.001.WZS01DT-P1-C5-T2
SVEA   Physloc
------ --------------------------------------------
(0) padmin @ ltc-zz1b-vios1: /home/padmin
$ oem_setup_env
(0) root @ ltc-zz1b-vios1: /home/padmin
# rmdev -l ent8
ent8 Defined
(0) root @ ltc-zz1b-vios1: /home/padmin
# mkdev -l ent8
ent8 Available
```

**Comment by abdhaleegit** [comment]
please close this issue
