### ISSUE TITLE
After run flail.py in Rhel8.1 with Avocado(version: 80.0), it can't complete test and shows different results

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1853]
After we install the latest Avocado (Version: 80.0) to run flail.py, it can't complete test. We run flail.py for 4 times, and weirdly we get 4 different results:

1.【Hangup】
　After run flail.py, it shows "Hangup", while no "Avocado-Result (PASS ? | ERROR ? | FAIL ? | ...)" shows up.
![1](https://user-images.githubusercontent.com/63998174/89598967-c5952e80-d890-11ea-96c4-6b333cb655e6.jpg)
[1.Hangup_SOL-log.Job-log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5038817/1.Hangup_SOL-log.Job-log.zip)

2.【Manual-Stop】
　After run flail.py, it shows "Interrupt requested. Waiting 2 seconds for test to finish (ignoring new Ctrl+C until then)". Therefore, we manually stop it.
　"Avocado-Result" shows below:
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
RESULTS : PASS 0 | ERROR 0 | FAIL 0 | SKIP 2 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML : /root/tests/results/job-2020-08-06T14.25-f2c16c9/results.html
JOB TIME : 516.25 s
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
![1](https://user-images.githubusercontent.com/63998174/89599003-e067a300-d890-11ea-9d17-739a8af134e6.jpg)
[2.Manual-Stop_SOL-log.Job-log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5038819/2.Manual-Stop_SOL-log.Job-log.zip)

3.【Auto-Reboot】
　After run flail.py, it automatically reboot, while no kernel-log generates.
[3.Auto-Reboot_SOL-log.Job-log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5038820/3.Auto-Reboot_SOL-log.Job-log.zip)
[3.Auto-Reboot_sosreport.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5038822/3.Auto-Reboot_sosreport.zip)

4.【Manual-Stop】
　After run flail.py, it shows "Interrupt requested. Waiting 2 seconds for test to finish (ignoring new Ctrl+C until then)". Therefore, we manually stop it.
　"Avocado-Result" shows below, which is different from the result of "2.【Auto-Reboot】":
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
RESULTS : PASS 0 | ERROR 0 | FAIL 0 | SKIP 2 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML : /root/tests/results/job-2020-08-06T14.25-f2c16c9/results.html
JOB TIME : 516.25 s
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
![1](https://user-images.githubusercontent.com/63998174/89599084-19077c80-d891-11ea-9352-aca661283550.jpg)
[4.Manual-Stop_SOL-log.Job-log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5038824/4.Manual-Stop_SOL-log.Job-log.zip)
[4.Manual-Stop_sosreport.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5038825/4.Manual-Stop_sosreport.zip)

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.8.1.el8_1.ppc64le

[FW config]
BMC: op940.15.mih-2-0-ga72988e66
PNOR: OP9-v2.4-4.49-prod

[HW config]
CPU DD2.3 20core *2
Micron_36ASF4G72PZ-2G6D1 (32GB) x8
M.2 SAMSUNG PM983 *1
PSU ACBEL 2000w *2
Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports *1 @ slot10
Seagate Skybolt (HDD; 600GB; 2.5"; 10k; SAS; 12Gb/s; 4Kn/512e; SED) *8

**Comment by PraveenPenguin** [comment]
Flail test is expected a lot of systems resources some if resources are not available in system it will starve and the system will be unresponsive, flail is kind of stress test of the system as flail  test suite has multiple config that can be run as default what test has is disk test, Here I think we can do two this 
1- we can add ReadME for Test listing how many configs we have 
2- in YAML also list the same test config having commented

**Comment by PraveenPenguin** [comment]
closing this as it works as design
