### ISSUE TITLE
Can I add a new test script?

### ISSUE THREAD

**Issue by bych-github** [avocado-framework-tests/avocado-misc-tests#1871]
Can I add a new test script? About the test of some basic commands,such as rmdir cp mv ...

**Comment by harish-24** [comment]
These tests are already covered in LTP here - https://github.com/linux-test-project/ltp/tree/master/testcases/commands. As it can be run through https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/generic/ltp.py it is better not to replicate. But if you think the scenario to test is different you can certainly send it. As long as the test is unique and provides some newer value, it is welcome!

**Comment by bych-github** [comment]
ok thanks!
