### ISSUE TITLE
After run numa_test.py in Rhel8.2 with Avocado(version: 81.0), it shows FAIL and ask to check logs for failure

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1882]
After run numa_test.py in Rhel8.2 with Avocado(version: 81.0), it shows FAIL and ask to check logs for failure.

《SOL log》
![image](https://user-images.githubusercontent.com/63998174/93047979-59c49380-f690-11ea-9f0a-c0a6fe42c977.png)

《job log》
![image](https://user-images.githubusercontent.com/63998174/93047903-297cf500-f690-11ea-83f8-5eecb39f2860.png)

《Test log》: JOB-log & Manual-Test-log
[Test log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5216378/Test.log.zip)

【Configuration】

[Rhel8.2 Kernel]
4.18.0-193.19.1.el8_2.ppc64le

[FW config]
BMC: op940.00.mih-5-0-g86f9791c2
PNOR: OP9-v2.4-4.37-prod

[HW config]
CPU DD2.3 20core *2
Micron (M393A8K40B22-CWD6Y) 64G *16
Samsung PM985 960GB *1
PSU ACBEL 2000w *2
Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports *1 @ slot10

**Comment by harish-24** [comment]
@Gene-Lo This looks to a bug, please raise against the distribution.

**Comment by PraveenPenguin** [comment]
closing this as it is Os defect please track there
