### ISSUE TITLE
After run pjdfstest.py in Rhel8.2 with Avocado(version: 81.0), it shows "failed: Command 'prove -rv tests' failed"

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1885]
After run pjdfstest.py in Rhel8.2 with Avocado(version: 81.0), it shows "failed: Command 'prove -rv tests' failed"

《SOL log》
![image](https://user-images.githubusercontent.com/63998174/93059025-bd57bc80-f6a2-11ea-89f8-60dd6f38a23d.png)

《job log》
![image](https://user-images.githubusercontent.com/63998174/93059754-c4cb9580-f6a3-11ea-9f56-573815f495d4.png)

《Test log》: job-log & Manual-Test-log
[Test-log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5216965/Test-log.zip)

《Configuration》

[Rhel8.2 Kernel]
4.18.0-193.19.1.el8_2.ppc64le

[FW config]
BMC: op940.00.mih-5-0-g86f9791c2
PNOR: OP9-v2.4-4.37-prod

[HW config]
CPU DD2.3 20core *2
Micron (M393A8K40B22-CWD6Y) 64G *16
Samsung PM985 960GB *1
PSU ACBEL 2000w *2
Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports *1 @ slot10

**Comment by PraveenPenguin** [comment]
@Gene-Lo I think this is Distro  defect please raise against Distro,  as a misc test just run this test suite if test suite failed it use to report test fail

**Comment by Gene-Lo** [comment]
@PraveenPenguin 
Could you give me the link of "Distro"? Thanks!!
