### ISSUE TITLE
After run perf_c2c.py in Rhel8.2 with Avocado(version: 81.0), it shows " Command perf c2c report -c pid,tid,iaddr,dso failed "

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1887]
After run perf_c2c.py in Rhel8.2 with Avocado(version: 81.0), it shows " Command perf c2c report -c pid,tid,iaddr,dso failed: Command 'perf c2c report -c pid,tid,iaddr,dso' failed. "

《SOL log》
![1](https://user-images.githubusercontent.com/63998174/93151925-dfe3e700-f72f-11ea-8afa-e471109c4150.jpg)
![2](https://user-images.githubusercontent.com/63998174/93151930-e4100480-f72f-11ea-8e1c-c86c85fee4a4.jpg)

《job log》
![image](https://user-images.githubusercontent.com/63998174/93152844-5255c680-f732-11ea-9552-1d67e8347fa3.png)
![image](https://user-images.githubusercontent.com/63998174/93152865-68638700-f732-11ea-8bf8-ad8a764d9474.png)
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5221856/job.log)

《Configuration》
[Rhel8.2 Kernel]
4.18.0-193.19.1.el8_2.ppc64le

[FW config]
BMC: op940.00.mih-5-0-g86f9791c2
PNOR: OP9-v2.4-4.37-prod

[HW config]
CPU DD2.3 12core *2
Micron (MTA18ASF2G72PZ-2G9E1) 16G *4
Samsung PM985 960GB *1
PSU ACBEL 2000w *2
Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER
Slot2: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER
Slot4: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot5: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER
Slot7: Marvell QUAD E'NET (2X1 + 2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER SFP+ SR COPPER)

**Comment by Gene-Lo** [comment]
After run perf_c2c.py in Rhel8.2 with Avocado(version: 82.0), it still shows " FAIL: Command perf c2c report -c pid,tid,iaddr,dso failed "

【SOL-log】
JOB ID     : 80c8323db8b9fcbc6899a512b874df16448a84da
JOB LOG    : /root/tests/results/job-2020-10-15T11.10-80c8323/job.log
 (001/210) perf_c2c.py:perf_c2c.test_c2c;run-c2c-record-event_load-report-coalesce-2788:  FAIL: Command perf c2c report -c pid,tid,iaddr,dso failed: Command 'perf c2c report -c pid,tid,iaddr,dso' failed.\nstdout: b''\nstderr: b"failed to open perf.data: No such file or directory  (try 'perf record' first)\n"\nadditional_info: None (128.11 s)
 (002/210) perf_c2c.py:perf_c2c.test_c2c;run-c2c-record-event_load-report-coalesce_full-4245:  FAIL: Command perf c2c report --coalesce pid,tid,iaddr,dso failed: Command 'perf c2c report --coalesce pid,tid,iaddr,dso' failed.\nstdout: b''\nstderr: b"failed to open perf.data: No such file or directory  (try 'perf record' first)\n"\nadditional_info: None (126.25 s)
 (003/210) perf_c2c.py:perf_c2c.test_c2c;run-c2c-record-event_load-report-display-lcl-18ca:  FAIL: Command perf c2c report -d lcl failed: Command 'perf c2c report -d lcl' failed.\nstdout: b''\nstderr: b"failed to open perf.data: No such file or directory  (try 'perf record' first)\n"\nadditional_info: None (127.65 s)
（．．．SKIP LOG．．．）
 (208/210) perf_c2c.py:perf_c2c.test_c2c;run-c2c-record-all_user_full-report-show-all-d515:  FAIL: Command perf c2c report --show-all failed: Command 'perf c2c report --show-all' failed.\nstdout: b''\nstderr: b"failed to open perf.data: No such file or directory  (try 'perf record' first)\n"\nadditional_info: None (122.00 s)
 (209/210) perf_c2c.py:perf_c2c.test_c2c;run-c2c-record-all_user_full-report-stats-005f:  FAIL: Command perf c2c report --stats failed: Command 'perf c2c report --stats' failed.\nstdout: b''\nstderr: b"failed to open perf.data: No such file or directory  (try 'perf record' first)\n"\nadditional_info: None (121.13 s)
 (210/210) perf_c2c.py:perf_c2c.test_c2c;run-c2c-record-all_user_full-report-stdio-6bc5:  FAIL: Command perf c2c report --stdio failed: Command 'perf c2c report --stdio' failed.\nstdout: b''\nstderr: b"failed to open perf.data: No such file or directory  (try 'perf record' first)\n"\nadditional_info: None (122.30 s)
RESULTS    : PASS 20 | ERROR 0 | FAIL 190 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/tests/results/job-2020-10-15T11.10-80c8323/results.html

【job.log】
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5388683/job.log)
《INIT 001-perf_c2c.py:perf_c2c.test_c2c》
L0604 INFO | Running 'perf c2c report -c pid,tid,iaddr,dso'
L0686 INFO | Command 'perf c2c report -c pid,tid,iaddr,dso' finished with 255 after 0.005411863327026367s
L0416 DEBUG| [stderr] failed to open perf.data: No such file or directory  (try 'perf record' first)
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:767
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/perf/perf_c2c.py", line 87, in run_cmd
L0045 ERROR|     process.run(cmd, ignore_status=False, sudo=True)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1037, in run
L0045 ERROR|     raise CmdError(cmd, sp.result)
L0045 ERROR| avocado.utils.process.CmdError: Command 'perf c2c report -c pid,tid,iaddr,dso' failed.
L0045 ERROR| stdout: b''
L0045 ERROR| stderr: b"failed to open perf.data: No such file or directory  (try 'perf record' first)\n"
L0045 ERROR| additional_info: None

《INIT 002-perf_c2c.py:perf_c2c.test_c2c》
L0604 INFO | Running 'perf c2c report --coalesce pid,tid,iaddr,dso'
L0686 INFO | Command 'perf c2c report --coalesce pid,tid,iaddr,dso' finished with 255 after 0.006104946136474609s
L0416 DEBUG| [stderr] failed to open perf.data: No such file or directory  (try 'perf record' first)
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:767
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/perf/perf_c2c.py", line 87, in run_cmd
L0045 ERROR|     process.run(cmd, ignore_status=False, sudo=True)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1037, in run
L0045 ERROR|     raise CmdError(cmd, sp.result)
L0045 ERROR| avocado.utils.process.CmdError: Command 'perf c2c report --coalesce pid,tid,iaddr,dso' failed.
L0045 ERROR| stdout: b''
L0045 ERROR| stderr: b"failed to open perf.data: No such file or directory  (try 'perf record' first)\n"
L0045 ERROR| additional_info: None

《INIT 003-perf_c2c.py:perf_c2c.test_c2c》
L0604 INFO | Running 'perf c2c report -d lcl'
L0686 INFO | Command 'perf c2c report -d lcl' finished with 255 after 0.0060880184173583984s
L0416 DEBUG| [stderr] failed to open perf.data: No such file or directory  (try 'perf record' first)
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:767
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/perf/perf_c2c.py", line 87, in run_cmd
L0045 ERROR|     process.run(cmd, ignore_status=False, sudo=True)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1037, in run
L0045 ERROR|     raise CmdError(cmd, sp.result)
L0045 ERROR| avocado.utils.process.CmdError: Command 'perf c2c report -d lcl' failed.
L0045 ERROR| stdout: b''
L0045 ERROR| stderr: b"failed to open perf.data: No such file or directory  (try 'perf record' first)\n"
L0045 ERROR| additional_info: None
L0045 ERROR| 
L0045 ERROR| During handling of the above exception, another exception occurred:

【Manual-Test】
[Manual-Test-log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5388695/Manual-Test-log.txt)
For "**START 001-perf_c2c.py:perf_c2c.test_c2c**", when we run the command "perf c2c report -c pid,tid,iaddr,dso" by manual, it shows below image.
If necessary, please illustrate how to test it by manual, so that we could do manual-test for you to check.
![Manual-Test-Photo](https://user-images.githubusercontent.com/63998174/96202990-507e5d80-0f93-11eb-9677-796dc1696cd0.png)

【Configuration】
[Kernel]
4.18.0-193.19.1.el8_2.ppc64le

[FW Config] 
BMC: op940.00.mih-5-0-g86f9791c2
Pnor: OP9-v2.4-4.37-prod

[HW Config]
CPU DD2.3 20 core *2
Samsung Electronics(M393A8K40B22-CWD)64GiB x16
Samsung PM985 960GB *1
PSU ACBEL 2000w *2
Slot1: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER

**Comment by PraveenPenguin** [comment]
@nasastry can you please have look on this issue

**Comment by nasastry** [comment]
> @nasastry can you please have look on this issue

@PraveenPenguin this issue is with Avocado base library. After running process.systemoutput though issuing decode, the output is not decoded .. this happens with 'perf c2c' command. One work around is 'perf c2c -o perf.data' but with this we can't test 'perf c2c' with all the options. So need fix at Avocado base library.
Thanks!!

**Comment by PraveenPenguin** [comment]
as recent code base has fix , @Gene-Lo please try with latest code base and if facing issue please open new issue
