### ISSUE TITLE
After run sosreport.py in Rhel8.2 with Avocado(version: 82.0), it shows "ERROR: [Errno 2] No such file or directory: 'sosreport build tree is located at : /var/tmp/sosreport-mowgli6-2020-10-28-xbtzwte' (478.43 s)"

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1942]
After run sosreport.py in Rhel8.2 with Avocado(version: 82.0), it shows "ERROR: [Errno 2] No such file or directory: 'sosreport build tree is located at : /var/tmp/sosreport-mowgli6-2020-10-28-xbtzwte' (478.43 s)"

**【SOL log】**
JOB ID     : 349e3a97ac730181c8a0d84e9e1eeb7b230c370d
JOB LOG    : /root/tests/results/job-2020-10-28T08.07-349e3a9/job.log
 (1/6) sosreport.py:Sosreport.test_short;run-17c1:  PASS (515.47 s)
 (2/6) sosreport.py:Sosreport.test_user;run-17c1:  PASS (1267.91 s)
 (3/6) sosreport.py:Sosreport.test_plugins;run-17c1:  PASS (364.78 s)
 (4/6) sosreport.py:Sosreport.test_others;run-17c1:  ERROR: [Errno 2] No such file or directory: 'sosreport build tree is located at : /var/tmp/sosreport-mowgli6-2020-10-28-xbtzwte' (478.43 s)
 (5/6) sosreport.py:Sosreport.test_archive;run-17c1:  PASS (534.88 s)
 (6/6) sosreport.py:Sosreport.test_PPC;run-17c1:  PASS (19.56 s)
RESULTS    : PASS 5 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/tests/results/job-2020-10-28T08.07-349e3a9/results.html
JOB TIME   : 3182.29 s

**【job.log】**
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5457179/job.log)
L0604 INFO | Running 'sosreport --no-report --batch --build'
L0416 DEBUG| [stdout] 
L0416 DEBUG| [stdout] sosreport (version 3.8)
L0416 DEBUG| [stdout] 
L0416 DEBUG| [stdout] This command will collect diagnostic and configuration information from
L0416 DEBUG| [stdout] this Red Hat Enterprise Linux system and installed applications.
L0416 DEBUG| [stdout] 
L0416 DEBUG| [stdout] An archive containing the collected information will be generated in
L0416 DEBUG| [stdout] /var/tmp/sos.5wxp6pdj and may be provided to a Red Hat support
L0416 DEBUG| [stdout] representative.
L0416 DEBUG| [stdout] 
L0416 DEBUG| [stdout] Any information provided to Red Hat will be treated in accordance with
L0416 DEBUG| [stdout] the published support policies at:
L0416 DEBUG| [stdout] 
L0416 DEBUG| [stdout]   https://access.redhat.com/support/
L0416 DEBUG| [stdout] 
L0416 DEBUG| [stdout] The generated archive may contain data considered sensitive and its
L0416 DEBUG| [stdout] content should be reviewed by the originating organization before being
L0416 DEBUG| [stdout] passed to any third party.
L0416 DEBUG| [stdout] 
L0416 DEBUG| [stdout] No changes will be made to system configuration.
L0416 DEBUG| [stdout] 
L0416 DEBUG| [stdout] 
L0416 DEBUG| [stdout]  Setting up archive ...
L0416 DEBUG| [stdout]  Setting up plugins ...
L0416 DEBUG| [stdout] [plugin:networking] skipped command 'ip -s macsec show': required kernel modules or services not present (kmods=[macsec] services=[]). Use '--allow-system-changes' to enable collection.
L0416 DEBUG| [stdout] [plugin:networking] skipped command 'ss -peaonmi': required kernel modules or services not present (kmods=[tcp_diag,udp_diag,inet_diag,unix_diag,netlink_diag,af_packet_diag] services=[]). Use '--allow-system-changes' to enable collection.
L0416 DEBUG| [stdout]  Running plugins. Please wait ...
L0416 DEBUG| [stdout] 
L0416 DEBUG| [stdout]   Starting 1/124 abrt            [Running: abrt]
L0416 DEBUG| [stdout]   Starting 2/124 alternatives    [Running: abrt alternatives]
L0416 DEBUG| [stdout]   Starting 3/124 anaconda        [Running: abrt alternatives anaconda]

（．．．SKIP log．．．）

L0416 DEBUG| [stdout]   Starting 122/124 xen             [Running: networking systemd systemtap xen]
L0416 DEBUG| [stdout]   Starting 123/124 xfs             [Running: networking systemd systemtap xfs]
L0416 DEBUG| [stdout]   Finishing plugins              [Running: networking systemtap xfs]
L0416 DEBUG| [stdout]   Starting 124/124 yum             [Running: networking systemtap xfs yum]
L0416 DEBUG| [stdout]   Finishing plugins              [Running: networking systemtap yum]
L0416 DEBUG| [stdout]   Finishing plugins              [Running: networking systemtap]
L0416 DEBUG| [stdout]   Finishing plugins              [Running: networking]
L0416 DEBUG| [stdout] 
L0416 DEBUG| [stdout]   Finished running plugins
L0416 DEBUG| [stdout] 
L0416 DEBUG| [stdout] 
L0416 DEBUG| [stdout] sosreport build tree is located at : /var/tmp/sosreport-mowgli6-2020-10-28-xbtzwte
L0416 DEBUG| [stdout] 
L0416 DEBUG| [stdout] 
L0686 INFO | Command 'sosreport --no-report --batch --build' finished with 0 after 105.40309381484985s
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:767
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/ras/sosreport.py", line 193, in test_others
L0045 ERROR|     if os.listdir(dir_name) == []:
L0045 ERROR| FileNotFoundError: [Errno 2] No such file or directory: 'sosreport build tree is located at : /var/tmp/sosreport-mowgli6-2020-10-28-xbtzwte'

**【Manual-Test-log】**
[Manual-Test-log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5457201/Manual-Test-log.txt)

**【Configuration】**
[Rhel8.2 Kernel]
4.18.0-193.28.1.el8_2.ppc64le

[FW configuration]
BMC: op940.hmc-1-0-g37543ab60
PNOR: IBM-mowgli-OP9_v2.5_4.101

[HW configuration]
CPU DD2.11 6core x1
M393A4K40BB2-CTD 16G x4
SAS 1800GB x1
PSU 900w x2
Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP x1

**Comment by harish-24** [comment]
@Pavithra1602 Could you take a look at this ? Seems like new change is not working here

L192: 
`dir_name = self.run_cmd_search("sosreport --no-report --batch --build", '/var/tmp/sosreport')`

has returned `sosreport build tree is located at : /var/tmp/sosreport-mowgli6-2020-10-28-xbtzwte`
```
2020-10-28 08:50:55,072 process          L0686 INFO | Command 'sosreport --no-report --batch --build' finished with 0 after 105.40309381484985s
2020-10-28 08:50:55,075 stacktrace       L0039 ERROR| 
2020-10-28 08:50:55,075 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:767
2020-10-28 08:50:55,076 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-10-28 08:50:55,076 stacktrace       L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/ras/sosreport.py", line 193, in test_others
2020-10-28 08:50:55,076 stacktrace       L0045 ERROR|     if os.listdir(dir_name) == []:
2020-10-28 08:50:55,076 stacktrace       L0045 ERROR| FileNotFoundError: [Errno 2] No such file or directory: 'sosreport build tree is located at : /var/tmp/sosreport-mowgli6-2020-10-28-xbtzwte'
```

**Comment by PraveenPenguin** [comment]
@Gene-Lo please try with latest code base as issue should fixed , closing now if facing any issue please raise new issue
