### ISSUE TITLE
After running disk_info.py of Avocado (Version: 85.0) in Rhel8.2, it shows "ERROR: list index out of range"

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2022]
When we equip **only 1 USB (/dev/sdc)** in Mowgli system, and then run **disk_info.py** of **Avocado (Version: 85.0)** in **Rhel8.2**, the result is **FAIL**:

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
(1/4) disk_info.py:DiskInfo.test_commands;run-filesystem-ext4-3741: PASS (5.52 s)
(2/4) disk_info.py:DiskInfo.test_commands;run-filesystem-xfs-2903: PASS (2.86 s)
**(3/4) disk_info.py:DiskInfo.test;run-filesystem-ext4-3741: ERROR: list index out of range (19.47 s)**
(4/4) disk_info.py:DiskInfo.test;run-filesystem-xfs-2903: PASS (6.56 s)
RESULTS    : PASS 3 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

However, if we equip **other 3 USBs** in Mowgli system, and then run **disk_info.py** to test the **original USB (/dev/sdc)**, the result becomes **PASS**:

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
(1/4) disk_info.py:DiskInfo.test_commands;run-filesystem-ext4-3741: PASS (3.04 s)
(2/4) disk_info.py:DiskInfo.test_commands;run-filesystem-xfs-2903: PASS (3.04 s)
**(3/4) disk_info.py:DiskInfo.test;run-filesystem-ext4-3741: PASS (19.44 s)**
(4/4) disk_info.py:DiskInfo.test;run-filesystem-xfs-2903: PASS (11.08 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

As a result, we consider that the root cause should come from **script issue**. Here is our analysis:

1. When we equip **only 1 USB (/dev/sdc)** in Mowgli system, the information of “**lsblk**” and “**lshw -c disk | nl**” are like below:
(Note: **sda** & **sdb** are **HDD**, while **sdc** is the **USB** we want to test)

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
[root@mowgli-SUT5 disk]# lsblk
NAME          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0           7:0    0  6.8G  0 loop /opt1
sda             8:0    0  1.7T  0 disk
├─sda1          8:1    0    4M  0 part
├─sda2          8:2    0    1G  0 part /boot
└─sda3          8:3    0  1.7T  0 part
  ├─rhel-root 253:0    0   50G  0 lvm  /
  ├─rhel-swap 253:1    0    4G  0 lvm  [SWAP]
  └─rhel-home 253:2    0  1.6T  0 lvm  /home
sdb             8:16   0  1.7T  0 disk
**sdc             8:32   1 28.7G  0 disk** 　→ **Note: It is the USB we want to test.**
[root@mowgli-SUT5 disk]# lshw -c disk | nl
     1    *-disk:0
     2         description: SCSI Disk
     3         product: ST1800MM0139  E
     4         vendor: IBM-ESXS
     5         physical id: 2.0.0
     6         bus info: scsi@0:2.0.0
     7         logical name: /dev/sda
     8         version: E5C3
     9         serial: WBN3B4SC0000K0345CVA
    10         size: 1676GiB (1800GB)
    11         capacity: 7052GiB (7572GB)
    12         capabilities: 10000rpm partitioned partitioned:dos
    13         configuration: ansiversion=6 logicalsectorsize=4096 sectorsize=4096
    14    *-disk:1
    15         description: SCSI Disk
    16         product: ST1800MM0139  E
    17         vendor: IBM-ESXS
    18         physical id: 2.1.0
    19         bus info: scsi@0:2.1.0
    20         logical name: /dev/sdb
    21         version: E5C3
    22         serial: WBN3B4MD0000K0295WXQ
    23         size: 1676GiB (1800GB)
    24         capacity: 7098GiB (7621GB)
    25         capabilities: 10000rpm
    26         configuration: ansiversion=6 logicalsectorsize=4096 sectorsize=4096
    _27    *-disk_
    28         description: SCSI Disk
    29         product: Ultra USB 3.0
    30         vendor: SanDisk
    31         physical id: 0.0.0
    32         bus info: scsi@1:0.0.0
    _33         logical name: /dev/sdc_
    34         version: 1.00
    35         serial: 0501deb6d0b8332d7048
    36         size: 28GiB (30GB)
    37         capabilities: removable
    38         configuration: ansiversion=6 logicalsectorsize=512 sectorsize=512
    39       *-medium
    40            physical id: 0
    41            logical name: /dev/sdc
    42            size: 28GiB (30GB)
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

After we run **disk_info.py** to test **USB (/dev/sdc)**, the result is FAIL, while its **job.log** shows below message:

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
L0604 INFO | Running 'lshw -c disk | grep -n "/dev/sdc" | cut -d ":" -f 1'
**L0416 DEBUG| [stdout] 33**
L0686 INFO | Command 'lshw -c disk | grep -n "/dev/sdc" | cut -d ":" -f 1' finished with 0 after 0.8960604667663574s
L0604 INFO | Running 'lshw -c disk | grep -n "\-disk" | cut -d ":" -f 1'
L0416 DEBUG| [stdout] 1
L0686 INFO | Command 'lshw -c disk | grep -n "\-disk" | cut -d ":" -f 1' finished with 0 after 0.8731276988983154s
L0416 DEBUG| [stdout] 14
**L0416 DEBUG| [stdout] 27**
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:767
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/io/disk/disk_info.py", line 271, in test
L0045 ERROR|     high = lst[index+1]
L0045 ERROR| IndexError: list index out of range
L0046 ERROR| 
L0772 DEBUG| Local variables:
L0775 DEBUG|  -> low <class 'str'>: 27
L0775 DEBUG|  -> index <class 'int'>: 3
L0775 DEBUG|  -> lst <class 'list'>: ['1', '14', '27', '33']
L0775 DEBUG|  -> total <class 'str'>: 1
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

We guess that because the first number “**[stdout] 33**” is larger than the last number “**[stdout] 27**”, the error message shows “**ERROR: list index out of range**”.

2. When we equip **other 3 USBs** in Mowgli system, the information of “**lsblk**” and “**lshw -c disk | nl**” are like below:

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
[root@mowgli-SUT5 disk]# lsblk
NAME          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0           7:0    0  6.8G  0 loop /opt1
sda             8:0    0  1.7T  0 disk
├─sda1          8:1    0    4M  0 part
├─sda2          8:2    0    1G  0 part /boot
└─sda3          8:3    0  1.7T  0 part
  ├─rhel-root 253:0    0   50G  0 lvm  /
  ├─rhel-swap 253:1    0    4G  0 lvm  [SWAP]
  └─rhel-home 253:2    0  1.6T  0 lvm  /home
sdb             8:16   0  1.7T  0 disk
**sdc**             8:32   1 28.7G  0 disk　**→ Note: It is the USB we want to test.**
sdd             8:48   1 28.7G  0 disk　**→ Note: It is the additional USB.**
sde             8:64   1 14.3G  0 disk　**→ Note: It is the additional USB.**
sdf             8:80   1 28.7G  0 disk　**→ Note: It is the additional USB.**
[root@mowgli-SUT5 disk]# lshw -c disk | nl
     1    *-disk:0
     2         description: SCSI Disk
     3         product: ST1800MM0139  E
     4         vendor: IBM-ESXS
     5         physical id: 2.0.0
     6         bus info: scsi@0:2.0.0
     7         logical name: /dev/sda
     8         version: E5C3
     9         serial: WBN3B4SC0000K0345CVA
    10         size: 1676GiB (1800GB)
    11         capacity: 7052GiB (7572GB)
    12         capabilities: 10000rpm partitioned partitioned:dos
    13         configuration: ansiversion=6 logicalsectorsize=4096 sectorsize=4096
    14    *-disk:1
    15         description: SCSI Disk
    16         product: ST1800MM0139  E
    17         vendor: IBM-ESXS
    18         physical id: 2.1.0
    19         bus info: scsi@0:2.1.0
    20         logical name: /dev/sdb
    21         version: E5C3
    22         serial: WBN3B4MD0000K0295WXQ
    23         size: 1676GiB (1800GB)
    24         capacity: 7098GiB (7621GB)
    25         capabilities: 10000rpm
    26         configuration: ansiversion=6 logicalsectorsize=4096 sectorsize=4096
    27    *-disk
    28         description: SCSI Disk
    29         product: Ultra USB 3.0
    30         vendor: SanDisk
    31         physical id: 0.0.0
    32         bus info: scsi@2:0.0.0
    33         logical name: /dev/sdd
    34         version: 1.00
    35         serial: 0501d8804046e3297582
    36         size: 28GiB (30GB)
    37         capabilities: removable
    38         configuration: ansiversion=6 logicalsectorsize=512 sectorsize=512
    39       *-medium
    40            physical id: 0
    41            logical name: /dev/sdd
    42            size: 28GiB (30GB)
    43    *-disk
    44         description: SCSI Disk
    45         product: Ultra USB 3.0
    46         vendor: SanDisk
    47         physical id: 0.0.0
    48         bus info: scsi@1:0.0.0
    _49         logical name: /dev/sdc_
    50         version: 1.00
    51         serial: 0501deb6d0b8332d7048
    52         size: 28GiB (30GB)
    53         capabilities: removable
    54         configuration: ansiversion=6 logicalsectorsize=512 sectorsize=512
    55       *-medium
    56            physical id: 0
    57            logical name: /dev/sdc
    58            size: 28GiB (30GB)
    59    *-disk
    60         description: SCSI Disk
    61         product: SanDisk 3.2Gen1
    62         vendor: USB
    63         physical id: 0.0.0
    64         bus info: scsi@3:0.0.0
    65         logical name: /dev/sde
    66         version: 1.00
    67         serial: 00008102100820111748
    68         size: 14GiB (15GB)
    69         capabilities: removable
    70         configuration: ansiversion=6 logicalsectorsize=512 sectorsize=512
    _71       *-medium_
    72            physical id: 0
    73            logical name: /dev/sde
    74            size: 14GiB (15GB)
    _75    *-disk_
    76         description: SCSI Disk
    77         product: Ultra USB 3.0
    78         vendor: SanDisk
    79         physical id: 0.0.0
    80         bus info: scsi@4:0.0.0
    _81         logical name: /dev/sdf_
    82         version: 1.00
    83         serial: 0501ebbc2d1dfdcb2079
    84         size: 28GiB (30GB)
    85         capabilities: removable
    86         configuration: ansiversion=6 logicalsectorsize=512 sectorsize=512
    87       *-medium
    88            physical id: 0
    89            logical name: /dev/sdf
    90            size: 28GiB (30GB)
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

After we run **disk_info.py** to test **USB (/dev/sdc)**, the result becomes PASS, while its **job.log** shows below message:

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
L0604 INFO | Running 'lshw -c disk | grep -n "/dev/sdc" | cut -d ":" -f 1'
**L0416 DEBUG| [stdout] 49**
L0686 INFO | Command 'lshw -c disk | grep -n "/dev/sdc" | cut -d ":" -f 1' finished with 0 after 0.8997969627380371s
L0604 INFO | Running 'lshw -c disk | grep -n "\-disk" | cut -d ":" -f 1'
L0416 DEBUG| [stdout] 1
L0686 INFO | Command 'lshw -c disk | grep -n "\-disk" | cut -d ":" -f 1' finished with 0 after 0.9085581302642822s
L0416 DEBUG| [stdout] 14
L0416 DEBUG| [stdout] 27
L0416 DEBUG| [stdout] 43
L0416 DEBUG| [stdout] 55
**L0416 DEBUG| [stdout] 71**
L0604 INFO | Running 'lshw -c disk |sed -n '43, 55p''
L0416 DEBUG| [stdout]   *-disk
L0686 INFO | Command 'lshw -c disk |sed -n '43, 55p'' finished with 0 after 0.9167447090148926s
L0416 DEBUG| [stdout]        description: SCSI Disk
L0416 DEBUG| [stdout]        product: Ultra USB 3.0
L0416 DEBUG| [stdout]        vendor: SanDisk
L0416 DEBUG| [stdout]        physical id: 0.0.0
L0416 DEBUG| [stdout]        bus info: scsi@1:0.0.0
L0416 DEBUG| [stdout]        logical name: /dev/sdc
L0416 DEBUG| [stdout]        version: 1.00
L0416 DEBUG| [stdout]        serial: 0501deb6d0b8332d7048
L0416 DEBUG| [stdout]        size: 28GiB (30GB)
L0416 DEBUG| [stdout]        capabilities: removable
L0416 DEBUG| [stdout]        configuration: ansiversion=6 logicalsectorsize=512 sectorsize=512
L0416 DEBUG| [stdout]   *-disk
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

We guess that because the first number “**[stdout] 49**” is less than the last number “**[stdout] 71**”, the message shows no error.

However, when we change to test the **last USB (/dev/sdf)** via running **disk_info.py**, the result becomes **FAIL**:

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
(1/4) disk_info.py:DiskInfo.test_commands;run-filesystem-ext4-c135: PASS (3.18 s)
(2/4) disk_info.py:DiskInfo.test_commands;run-filesystem-xfs-80af: PASS (3.17 s)
**(3/4) disk_info.py:DiskInfo.test;run-filesystem-ext4-c135: ERROR: list index out of range (41.60 s)**
(4/4) disk_info.py:DiskInfo.test;run-filesystem-xfs-80af: PASS (6.74 s)
RESULTS    : PASS 3 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

And its **job.log** shows below message:

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
L0604 INFO | Running 'lshw -c disk | grep -n "/dev/sdf" | cut -d ":" -f 1'
**L0416 DEBUG| [stdout] 81**
L0686 INFO | Command 'lshw -c disk | grep -n "/dev/sdf" | cut -d ":" -f 1' finished with 0 after 0.9153280258178711s
L0604 INFO | Running 'lshw -c disk | grep -n "\-disk" | cut -d ":" -f 1'
L0416 DEBUG| [stdout] 1
L0416 DEBUG| [stdout] 14
L0416 DEBUG| [stdout] 27
L0416 DEBUG| [stdout] 43
L0416 DEBUG| [stdout] 59
**L0416 DEBUG| [stdout] 75**
L0686 INFO | Command 'lshw -c disk | grep -n "\-disk" | cut -d ":" -f 1' finished with 0 after 0.9398491382598877s
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:767
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/io/disk/disk_info.py", line 271, in test
L0045 ERROR|     high = lst[index+1]
L0045 ERROR| IndexError: list index out of range
L0046 ERROR| 
L0772 DEBUG| Local variables:
L0775 DEBUG|  -> low <class 'str'>: 75
L0775 DEBUG|  -> index <class 'int'>: 6
L0775 DEBUG|  -> lst <class 'list'>: ['1', '14', '27', '43', '59', '75', '81']
L0775 DEBUG|  -> total <class 'str'>: 1
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

We guess that because the first number “**[stdout] 81**” is larger than the last number “**[stdout] 75**”, the error message shows “**ERROR: list index out of range**”.

※ According to above, we guess that the **sequence** of USB in “**lshw -c disk | nl**” would affect **disk_info.py** to judge the list of USB information. For more information, please refer to our test-logs:
[20210312-Single_USB-disk_info-sdc_FAIL-job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6128102/20210312-Single_USB-disk_info-sdc_FAIL-job.log)
[20210312-Multiple-USB-disk_info-sdc_PASS-job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6128103/20210312-Multiple-USB-disk_info-sdc_PASS-job.log)
[20210312-Multiple-USB-disk_info-sdf_FAIL-job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6128104/20210312-Multiple-USB-disk_info-sdf_FAIL-job.log)

※  In addition, our issue is similar to below one. Maybe you could check if both root causes are the same.
https://github.com/avocado-framework-tests/avocado-misc-tests/issues/1804

**Comment by smruti77** [comment]
@Gene-Lo can you try with this,
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/2025

**Comment by Gene-Lo** [comment]
After we install Avocado (Version: **86.0**) in Rhel8.2, and equip only **1 USB (/dev/sdc)** to test via disk_info.py, the result is still FAIL:
![Result](https://user-images.githubusercontent.com/63998174/111568180-416a3880-87db-11eb-94e6-67888028bae5.jpg)

Here is our configuration, while **/dev/sdc** is the USB we want to test:
![Config](https://user-images.githubusercontent.com/63998174/111568246-5e9f0700-87db-11eb-84df-5e788c4f00d8.jpg)

And here is the **job.log** and current **lshw info**.:
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6161055/job.log)
[lshw.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6161057/lshw.txt)

Next, after we equip another **USB (/dev/sdd)**, and then still test the **USB (/dev/sdc)** via disk_info.py, the result becomes PASS;.
Here is the **job.log** and current **lshw info**.:
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6161074/job.log)
[lshw.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6161075/lshw.txt)

However, after we change to test **USB (/dev/sdd)** via disk_info.py, the result is FAIL:
![Result](https://user-images.githubusercontent.com/63998174/111569318-5942bc00-87dd-11eb-81cd-70f7c843958c.jpg)

Here is the **job.log**:
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6161110/job.log)

From above test, the script issue should not be fixed in Avocado (Version: **86.0**).
Please kindly check. Thanks!!

**Comment by smruti77** [comment]
@Gene-Lo can you please check this patch #2025 it have the fix, it is still not merged.

**Comment by Gene-Lo** [comment]
Since the issue is solved in #2144. so close it.
