### ISSUE TITLE
After running systemtap.py in Rhel8.2 with Avocado(version: 86.0), it shows "CANCEL: simple systemtap test failed,kernel debuginfo package may be missing"

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2027]
After running systemtap.py in Rhel8.2 with Avocado(version: 86.0), it shows "CANCEL: simple systemtap test failed,kernel debuginfo package may be missing"
 **(1/1) systemtap.py:Systemtap.test;run-2bb3: CANCEL: simple systemtap test failed,kernel debuginfo package may be missing** 

**【Pre-preparation】**
Before running systemtap.py, we did install below packages:

[root@mowgli-SUT5 ~]# uname -a
Linux mowgli-SUT5 4.18.0-193.28.1.el8_2.ppc64le #1 SMP Fri Oct 16 13:43:44 EDT 2020 ppc64le ppc64le ppc64le GNU/Linux
[root@mowgli-SUT5 ~]# rpm -ivh **kernel-debuginfo-common-ppc64le-4.18.0-193.28.1.el8_2.ppc64le.rpm**
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
        package kernel-debuginfo-common-ppc64le-4.18.0-193.28.1.el8_2.ppc64le is already installed
[root@mowgli-SUT5 ~]# rpm -ivh **kernel-debug-debuginfo-4.18.0-193.28.1.el8_2.ppc64le.rpm**
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
        package kernel-debug-debuginfo-4.18.0-193.28.1.el8_2.ppc64le is already installed
[root@mowgli-SUT5 ~]# rpm -ivh **kernel-debuginfo-4.18.0-193.28.1.el8_2.ppc64le.rpm**
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
        package kernel-debuginfo-4.18.0-193.28.1.el8_2.ppc64le is already installed
[root@mowgli-SUT5 ~]# rpm -ivh **kernel-debug-4.18.0-193.28.1.el8_2.ppc64le.rpm**
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
        package kernel-debug-4.18.0-193.28.1.el8_2.ppc64le is already installed
[root@mowgli-SUT5 ~]# rpm -ivh **kernel-debug-devel-4.18.0-193.28.1.el8_2.ppc64le.rpm**
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
        package kernel-debug-devel-4.18.0-193.28.1.el8_2.ppc64le is already installed
[root@mowgli-SUT5 ~]# rpm -ivh **kernel-4.18.0-193.28.1.el8_2.ppc64le.rpm**
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
        package kernel-4.18.0-193.28.1.el8_2.ppc64le is already installed
[root@mowgli-SUT5 ~]#

**【job.log】**
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6162306/job.log)
L0686 INFO | Command 'make install' finished with 0 after 16.129849195480347s
L0604 INFO | Running 'PATH=%s/bin:$PATH stap -v /bin/true -e 'probe vfs.read { exit() }''
**L0416 DEBUG| [stderr] Checking "/lib/modules/4.18.0-193.28.1.el8_2.ppc64le/build/.config" failed with error: No such file or directory**
L0686 INFO | Command 'PATH=%s/bin:$PATH stap -v /bin/true -e 'probe vfs.read { exit() }'' finished with 1 after 0.0045855045318603516s
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:742
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/home/ooo/tests/tests/avocado-misc-tests/toolchain/systemtap.py", line 74, in setUp
L0045 ERROR|     self.cancel("simple systemtap test failed,"
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 972, in cancel
L0045 ERROR|     raise exceptions.TestCancel(message)
L0045 ERROR| avocado.core.exceptions.TestCancel: simple systemtap test failed,kernel debuginfo package may be missing

**【Manual Test Log】**
[Manual-Test-log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6162315/Manual-Test-log.txt)

**【Configuration】**
[Kernel]
4.18.0-193.28.1.el8_2.ppc64le

[FW Config]
BMC:  op940.hmc-4-cfm-0-g22c99ea49 
Pnor: IBM-mowgli-ibm-OP9_v2.5_4.109-prod

[HW Config]
CPU DD2.1 6 core *1
PSU 900w *2
Samsung Electronics(M393A4K40BB2-CTD)32GiB x4
Slot1: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
HDD - 00VN502 - Seagate Skybolt - HDD 1800GB SAS *2

**Comment by PraveenPenguin** [comment]
@Gene-Lo please install kernel-debug info or have repo setup it will resolve the issue
