### ISSUE TITLE
Running network tests on some virtual interfaces

### ISSUE THREAD

**Issue by vaishnavibhat** [avocado-framework-tests/avocado-misc-tests#2031]
HNV interfaces use nmcli command for its configuration rather than ip commands. 
The network related tests use ip commands form the utility  /utils/network/interfaces.py for its configuration. These commands are not supported for hnv interface. 
Alternative approach would be to use the yaml parm  `ip_config = False` in these tests that will basically skip the interface config and run the tests directly on already configured hnv interface.

**Comment by abdhaleegit** [comment]
now network utility supports both nmcli and ip sysfs static config
