### ISSUE TITLE
After running lvsetup.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Command 'vgcreate avocado_vg /dev/sda' failed”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2154]
After running lvsetup.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Command 'vgcreate avocado_vg /dev/sda' failed”.

**《yaml-File》**
![lvsetup_yaml](https://user-images.githubusercontent.com/63998174/140678019-c961d5f9-bde5-4f6d-8cb5-327a16bb6cc2.png)

**《SOL-Log》**
![lvsetup_SOL](https://user-images.githubusercontent.com/63998174/140678256-3dd3530b-be80-4048-9c35-ca4c1a771bf7.png)

**《Debug-Log of UID 1》**
[stdlog] 2021-11-05 00:39:23,771 process          L0658 INFO | Running 'vgdisplay avocado_vg'
[stdlog] 2021-11-05 00:39:23,789 process          L0470 DEBUG| [stderr]   Volume group "avocado_vg" not found
[stdlog] 2021-11-05 00:39:23,789 process          L0470 DEBUG| [stderr]   Cannot process volume group avocado_vg
[stdlog] 2021-11-05 00:39:23,991 process          L0740 INFO | Command 'vgdisplay avocado_vg' finished with 5 after 0.218506863s
[stdlog] 2021-11-05 00:39:23,991 lv_utils         L0280 ERROR| Command 'vgdisplay avocado_vg' failed.
[stdlog] stdout: b''
[stdlog] stderr: b'  Volume group "avocado_vg" not found\n  Cannot process volume group avocado_vg\n'
[stdlog] additional_info: None
[stdlog] 2021-11-05 00:39:23,991 process          L0658 INFO | Running 'lvdisplay avocado_vg'
[stdlog] 2021-11-05 00:39:24,012 process          L0470 DEBUG| [stderr]   Volume group "avocado_vg" not found
[stdlog] 2021-11-05 00:39:24,012 process          L0470 DEBUG| [stderr]   Cannot process volume group avocado_vg
[stdlog] 2021-11-05 00:39:24,261 process          L0740 INFO | Command 'lvdisplay avocado_vg' finished with 5 after 0.268250722s
[stdlog] 2021-11-05 00:39:24,261 process          L0658 INFO | Running 'lvdisplay avocado_vg'
[stdlog] 2021-11-05 00:39:24,281 process          L0470 DEBUG| [stderr]   Volume group "avocado_vg" not found
[stdlog] 2021-11-05 00:39:24,281 process          L0470 DEBUG| [stderr]   Cannot process volume group avocado_vg
[stdlog] 2021-11-05 00:39:24,441 process          L0740 INFO | Command 'lvdisplay avocado_vg' finished with 5 after 0.178114711s
[stdlog] 2021-11-05 00:39:24,441 test             L0465 DEBUG| Test workdir initialized at: /var/tmp/.avocado-task04k443h4/test-results/tmp_dir7fwognfg/1-Lvsetup.test
[stdlog] 2021-11-05 00:39:24,442 process          L0658 INFO | Running 'fdisk -l /dev/sda'
[stdlog] 2021-11-05 00:39:24,446 process          L0470 DEBUG| [stdout] Disk /dev/sda: 2.2 TiB, 2400476553216 bytes, 586053846 sectors
[stdlog] 2021-11-05 00:39:24,446 process          L0470 DEBUG| [stdout] Units: sectors of 1 * 4096 = 4096 bytes
[stdlog] 2021-11-05 00:39:24,446 process          L0740 INFO | Command 'fdisk -l /dev/sda' finished with 0 after 0.003183264s
[stdlog] 2021-11-05 00:39:24,446 process          L0470 DEBUG| [stdout] Sector size (logical/physical): 4096 bytes / 4096 bytes
[stdlog] 2021-11-05 00:39:24,446 process          L0470 DEBUG| [stdout] I/O size (minimum/optimal): 4096 bytes / 4096 bytes
[stdlog] 2021-11-05 00:39:24,446 parameters       L0143 DEBUG| PARAMS (key=lv_snapshot_size, path=*, default=4608.0) => 4608.0
[stdlog] 2021-11-05 00:39:24,447 process          L0658 INFO | Running 'vgdisplay avocado_vg'
[stdlog] 2021-11-05 00:39:24,466 process          L0470 DEBUG| [stderr]   Volume group "avocado_vg" not found
[stdlog] 2021-11-05 00:39:24,466 process          L0470 DEBUG| [stderr]   
[stdlog] 2021-11-05 00:39:24,466 process          L0470 DEBUG| [stderr] Cannot process volume group avocado_vg
[stdlog] 2021-11-05 00:39:24,641 process          L0740 INFO | Command 'vgdisplay avocado_vg' finished with 5 after 0.192953637s
[stdlog] 2021-11-05 00:39:24,641 lv_utils         L0280 ERROR| Command 'vgdisplay avocado_vg' failed.
[stdlog] stdout: b''
[stdlog] stderr: b'  Volume group "avocado_vg" not found\n  Cannot process volume group avocado_vg\n'
[stdlog] additional_info: None

**《Linux Test Log》**
However, when we run Linux commands, the result is PASS.
[lvsetup-Linux_Command_Test.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7494010/lvsetup-Linux_Command_Test.txt)

**《Avocado Test Log》**
[20211104-Storage3-lvsetup.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7494011/20211104-Storage3-lvsetup.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by Naresh-ibm** [comment]
@Gene-Lo this is happening with avocado version 92. which has nrunner. nrunner has effect on most of the test cases not only lvsetup which will be resolved in near future. till that, please use the avocado version 90. it will work without any issue.

**Comment by PraveenPenguin** [comment]
> @Gene-Lo this is happening with avocado version 92. which has nrunner. nrunner has effect on most of the test cases not only lvsetup which will be resolved in near future. till that, please use the avocado version 90. it will work without any issue.

@Gene-Lo just add on as suggested in another issue please pass `runner` avocado command-line argument

**Comment by Gene-Lo** [comment]
@PraveenPenguin 
Excuse me that how to install specific version (ex. 90) of Avocado in Rhel8.4?
Since when we install Avocado via below commands, we would always get the latest version of Avocado:

yum erase python2 -y
yum install python3 python3-devel -y
ln -s /usr/bin/python3 /usr/bin/python
ln -s /usr/bin/pip3 /usr/bin/pip
pip install pexpect

curl https://avocado-project.org/data/repos/avocado-el.repo -o /etc/yum.repos.d/avocado.repo
yum install python36-devel xz-devel numactl openssl-devel enchant -y
git clone https://github.com/open-power-host-os/tests 
cd tests
python avocado-setup.py --bootstrap

**Comment by PraveenPenguin** [comment]
> yum erase python2 -y yum install python3 python3-devel -y ln -s /usr/bin/python3 /usr/bin/python ln -s /usr/bin/pip3 /usr/bin/pip pip install pexpect

@Gene-Lo below steps will help you 

```
**Using avocado upstream path  :**

git clone https://github.com/avocado-framework/avocado
cd  avocado
git checkout 90.0
python setup.py --install

**Using Test repo :**


git clone https://github.com/open-power-host-os/tests
cd tests

**mandatory steps** 
### modify env.conf file as having below entry 
cat config/wrapper/env.conf | grep base
base = [('avocado-framework', '90.0'), ('avocado-framework-plugin-varianter-yaml-to-mux', '90.0')]

cat config/wrapper/env.conf | grep optional
optional = [('avocado-framework-plugin-result-html', '90.0')]


python avocado-setup.py --bootstrap
```

Regards
Praveen

**Comment by Gene-Lo** [comment]
Dear @PraveenPenguin 

Thanks for your kindly help !!

Excuse me that we have some questions hope to check with you:

1. When we run "python setup.py --install", it shows FAIL like below:
![1](https://user-images.githubusercontent.com/63998174/143812689-09c5391d-6331-4562-a920-674776f4bd4f.png)

2. However, when we edit "env.conf" and then run "python avocado-setup.py --bootstrap", it can successfully install Ver. 90 of Avocado:
![2](https://user-images.githubusercontent.com/63998174/143812814-1c079e35-7393-4939-a15c-4674a18d03cb.png)

After we run "pci_info_lsvpd.py" and then check its job.log, it really shows "Avocado version: 90.0".
![3](https://user-images.githubusercontent.com/63998174/143812953-4f3b2054-ae1c-4bd4-bf80-f95b5bd32e28.png)

**※ Regarding to the issue that we run "python setup.py --install" FAIL, could you give us other correct commands to run it? Or could we neglect the issue?**

Many thanks!!

**Comment by PraveenPenguin** [comment]
> 1. python setup.py --install

ah yes command is just 
```
python setup.py install

```

**Comment by Gene-Lo** [comment]
We can run "python setup.py install" successfully. Many thanks for your help !!
We will use Ver. 90 of Avocado to re-test the issues we raised on GitHub these days.
Thanks !!

**Comment by PraveenPenguin** [comment]
@Gene-Lo i suggest use Test repo like 
```
git clone https://github.com/open-power-host-os/tests
cd tests
**have added test config file in 
/config/tests/host/test.config
and have added Test in config fle**
python avocado-setup.py --bootstrap
python avocado-setup.py --run-suite host_test >> **note test is name what is config file name** 
```

**Comment by Naresh-ibm** [comment]
@Gene-Lo hope it is working for you after changing to avocado version 90 or by adding runner option to the command.
hope we can close this now?

**Comment by Gene-Lo** [comment]
After we change to use Avocado version 90 to run lvsetup.py, the result becomes PASS.

《Avocado Test Log》
[20211130-SUT1.11-Storage3-lvsetup.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7631790/20211130-SUT1.11-Storage3-lvsetup.zip)

Excuse me that we have different types of Network-Cards and Storage-Cards need to use  Avocado version 90 to re-test, we will     complete these tests and close GitHub issues as soon as possible. Many thanks for your kindly help !!
