### ISSUE TITLE
After running softwareraid.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: Failed to create”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2155]
After running softwareraid.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: Failed to create”.

**《yaml-File》**
![yaml](https://user-images.githubusercontent.com/63998174/140679054-48bbc625-d80d-425e-a6c2-2b4d8b14a2e1.png)

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/140679078-d1e8694a-8533-4891-80f2-851175ddcd74.png)

**《Debug-Log of UID 1》**
L0740 INFO | Command 'mdadm --create --assume-clean /dev/md/mdsraid --level=linear --raid-devices=7 /dev/sda /dev/sdb /dev/sdc /dev/sdd /dev/sde /dev/sdf /dev/sdg --metadata=0.9 --verbose --force' finished with 1 after 0.003456717s
L0470 DEBUG| [stderr] mdadm: super0.90 cannot open /dev/sdg: Device or resource busy
L0470 DEBUG| [stderr] mdadm: /dev/sdg is not suitable for this array.
L0470 DEBUG| [stderr] mdadm: create aborted
L0658 INFO | Running 'mdadm --detail /dev/md/mdsraid'
L0470 DEBUG| [stderr] mdadm: cannot open /dev/md/mdsraid: No such device
L0740 INFO | Command 'mdadm --detail /dev/md/mdsraid' finished with 1 after 0.002042820s
L0039 ERROR|
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:793
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/io/disk/softwareraid.py", line 75, in test
L0045 ERROR|     self.fail("Failed to create")
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 979, in fail
L0045 ERROR|     raise exceptions.TestFail(message)
L0045 ERROR| avocado.core.exceptions.TestFail: Failed to create

**《Linux Test Log》**
However, when we run Linux commands, the result is PASS.
[softwareraid-Linux_Command_Test.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7494056/softwareraid-Linux_Command_Test.txt)

**《Avocado Test Log》**
[20211104-Storage3-softwareraid.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7494059/20211104-Storage3-softwareraid.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by PraveenPenguin** [comment]
@manvanthar can you please have look on above issue

**Comment by Gene-Lo** [comment]
After use 90 version of Avocado to re-test, the result becomes PASS. Thanks!!
