### ISSUE TITLE
After running hwinfo.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: hwinfo: --save-config option failed”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2156]
After running hwinfo.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: hwinfo: --save-config option failed”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/140875837-87223e82-d6da-4faa-b49f-dc4e69964c05.png)

**《Debug-Log of UID 13》**
L0658 INFO | Running 'hwinfo --disk --only  | grep 'Unique' | head -1 | cut -d':' -f2'
L0470 DEBUG| [stderr] Usage: hwinfo [OPTIONS]
L0470 DEBUG| [stderr] Probe for hardware.
L0470 DEBUG| [stderr] Options:
L0470 DEBUG| [stderr]     --<HARDWARE_ITEM>
L0470 DEBUG| [stderr]         This option can be given more than once. Probe for a particular
L0740 INFO | Command 'hwinfo --disk --only  | grep 'Unique' | head -1 | cut -d':' -f2' finished with 0 after 0.001935595s
L0470 DEBUG| [stderr]         HARDWARE_ITEM. Available hardware items are:
L0470 DEBUG| [stderr]         all, arch, bios, block, bluetooth, braille, bridge, camera,
L0470 DEBUG| [stderr]         cdrom, chipcard, cpu, disk, dsl, dvb, fingerprint, floppy,
L0470 DEBUG| [stderr]         framebuffer, gfxcard, hub, ide, isapnp, isdn, joystick, keyboard,
L0470 DEBUG| [stderr]         memory, mmc-ctrl, modem, monitor, mouse, netcard, network, partition,
L0470 DEBUG| [stderr]         pci, pcmcia, pcmcia-ctrl, pppoe, printer, redasd,
L0470 DEBUG| [stderr]         reallyall, scanner, scsi, smp, sound, storage-ctrl, sys, tape,
L0470 DEBUG| [stderr]         tv, uml, usb, usb-ctrl, vbe, wlan, xen, zip
L0470 DEBUG| [stderr]     --short
L0470 DEBUG| [stderr]         Show only a summary. Use this option in addition to a hardware
L0470 DEBUG| [stderr]         probing option.
L0470 DEBUG| [stderr]     --listmd
L0470 DEBUG| [stderr]         Normally hwinfo does not report RAID devices. Add this option to
L0470 DEBUG| [stderr]         see them.
L0470 DEBUG| [stderr]     --only DEVNAME
L0470 DEBUG| [stderr]         This option can be given more than once. If you add this option
L0470 DEBUG| [stderr]         only entries in the device list matching DEVNAME will be shown.
L0470 DEBUG| [stderr]         Note that you also have to specify --<HARDWARE_ITEM> to trigger
L0470 DEBUG| [stderr]         any device probing.
L0470 DEBUG| [stderr]     --save-config SPEC
L0470 DEBUG| [stderr]         Store config  for a particular device below /var/lib/hardware.
L0470 DEBUG| [stderr]         SPEC can be a device name, an UDI, or 'all'. This option must be
L0470 DEBUG| [stderr]         given in addition to a hardware probing option.
L0470 DEBUG| [stderr]     --show-config UDI
L0470 DEBUG| [stderr]         Show saved config data for a particular device.
L0470 DEBUG| [stderr]     --map
L0470 DEBUG| [stderr]         If disk names have  changed (e.g. after a kernel update) this
L0470 DEBUG| [stderr]         prints a list of disk name mappings. Note  that  you must have
L0470 DEBUG| [stderr]         used --save-config at some point before for this can work.
L0470 DEBUG| [stderr]     --debug N
L0470 DEBUG| [stderr]         Set debug level to N. The debug info is shown only in the log
L0470 DEBUG| [stderr]         file. If you specify a log file, the debug level is implicitly
L0470 DEBUG| [stderr]         set to a reasonable value (N is a bitmask of individual flags).
L0470 DEBUG| [stderr]     --verbose
L0470 DEBUG| [stderr]         Increase verbosity. Only together with --map.
L0470 DEBUG| [stderr]     --log FILE
L0470 DEBUG| [stderr]         Write log info to FILE.
L0470 DEBUG| [stderr]         Don't forget to also specify --<HARDWARE_ITEM> to trigger any
L0470 DEBUG| [stderr]         device probing.
L0470 DEBUG| [stderr]     --dump-db N
L0470 DEBUG| [stderr]         Dump hardware data base. N is either 0 for the external data
L0470 DEBUG| [stderr]         base in /var/lib/hardware, or 1 for the internal data base.
L0470 DEBUG| [stderr]     --version
L0470 DEBUG| [stderr]         Print libhd version.
L0470 DEBUG| [stderr]     --help
L0470 DEBUG| [stderr]         Print usage.

※ According to above log, please check if it is script’s issue.

**《Test Log》**
[20211108-SUT1-RAS-hwinfo.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7502633/20211108-SUT1-RAS-hwinfo.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by PraveenPenguin** [comment]
it fixed in latest code base @Gene-Lo please try and if facing issue please raise a new issue
