### ISSUE TITLE
After running sosreport.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: 1 command(s) failed in sosreport tool verification”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2160]
After running sosreport.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: 1 command(s) failed in sosreport tool verification”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/140878091-8fbe0ef9-eaa2-4b3a-a5fe-131d0fbee439.png)

**《Debug-Log of UID 3》**
L0658 INFO | Running 'sos report --batch --tmp-dir=/var/tmp/tmpx8ofsk0y -e sendmail | grep sendmail'
L0470 DEBUG| [stdout]   Starting 99/127 sendmail        [Running: insights ipmitool selinux sendmail]
L0470 DEBUG| [stdout]   Starting 100/127 services        [Running: insights ipmitool sendmail services]
L0470 DEBUG| [stdout]   Starting 101/127 smartcard       [Running: insights ipmitool sendmail smartcard]
L0470 DEBUG| [stdout]   Starting 102/127 snmp            [Running: insights ipmitool sendmail snmp]
L0470 DEBUG| [stdout]   Starting 103/127 soundcard       [Running: insights ipmitool sendmail soundcard]
L0470 DEBUG| [stdout]   Starting 104/127 ssh             [Running: insights ipmitool sendmail ssh]
L0470 DEBUG| [stdout]   Starting 105/127 sssd            [Running: insights ipmitool sendmail sssd]
L0470 DEBUG| [stdout]   Starting 106/127 subscription_manager [Running: insights ipmitool sendmail subscription_manager]
L0740 INFO | Command 'sos report --batch --tmp-dir=/var/tmp/tmpx8ofsk0y -e sendmail | grep sendmail' finished with 0 after 238.667210128s
L0658 INFO | Running 'sos report --batch --tmp-dir=/var/tmp/tmpx8ofsk0y -o cups | grep cups'
L0740 INFO | Command 'sos report --batch --tmp-dir=/var/tmp/tmpx8ofsk0y -o cups | grep cups' finished with 0 after 4.308040717s
L0470 DEBUG| [stdout]   Starting 1/1   cups            [Running: cups]
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:793
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/ras/sosreport.py", line 146, in test_plugins
L0045 ERROR|     self.fail("%s command(s) failed in sosreport tool verification" % self.is_fail)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 979, in fail
L0045 ERROR|     raise exceptions.TestFail(message)
L0045 ERROR| avocado.core.exceptions.TestFail: 1 command(s) failed in sosreport tool verification
L0046 ERROR|

**※ Note: When run cmd "sosreport" by **sosreport.py  of Avocado-script**, it is suspended at No.106 and shows FAIL.**

**《Manual Test Log》**
**However, when run cmd "sosreport" manual, it can run completely and generate logs.**
**Since Manual-Test is PASS, please check if it is script's issue.**
[Manual-Test-Log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7502689/Manual-Test-Log.txt)
![Manual](https://user-images.githubusercontent.com/63998174/146753795-1f0e6181-ff63-4a22-803e-2ae7fea401f6.png)

**《Avocado Test Log》**
[20211105-SUT1-RAS-sosreport.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7502691/20211105-SUT1-RAS-sosreport.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by Gene-Lo** [comment]
Recently we use **Version 80 of Avocado** to run sosreport.py in **Rhel8.4**, and it still shows " FAIL: 1 command(s) failed in sosreport tool verification "

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/145152575-b8e8fc0f-2919-4efd-8a7c-1ad0102ae3ae.png)

**《Avocado Test Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/145152602-ef07686b-a77a-42ff-9325-a407e2098186.png)

Since in the past we could use **Version 80 of Avocado** to run sosreport.py in **Rhel8.2**, and the result was PASS, please check if it is Rhel8.4's limit to run sosreport.py. Thanks!!

**《Configuration》**
[Kernel]
4.18.0-305.el8.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Samsung Electronics(M393A4K40BB2-CTD)32GiB x8
PSU ACBEL 2000w *2
Slot1: Broadcom 9300-8i SAS/SATA HBA PCIe Gen3 x8 LP
00VN500 - Seagate Skybolt - HDD 600GB SAS *1

**Comment by PraveenPenguin** [comment]
@Pavithra1602 is this still a issue , as i see we have patches  goes in in recent past

**Comment by Pavithra1602** [comment]
Please use latest avocado misc tests suit, it is working fine.

[root@ltc-zz189-lp1 ras]# uname -a
Linux ltc-zz189-lp1.aus.stglabs.ibm.com 4.18.0-305.el8.ppc64le #1 SMP Thu Apr 29 08:53:15 EDT 2021 ppc64le ppc64le ppc64le GNU/Linux
yaml --max-parallel-tasks=1vocado run sosreport.py -m sosreport.py.data/options.y
JOB ID     : 71935d196862a7ec90ac57837ad34e1ca6872181
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-02-24T01.03-71935d1/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/local/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (01/22) sosreport.py:Sosreport.test_short;run-filesystem-ext4-e656: STARTED
 (01/22) sosreport.py:Sosreport.test_short;run-filesystem-ext4-e656:  PASS (355.02 s)
 (02/22) sosreport.py:Sosreport.test_short;run-filesystem-xfs-4133: STARTED
 (02/22) sosreport.py:Sosreport.test_short;run-filesystem-xfs-4133:  PASS (299.50 s)
 (03/22) sosreport.py:Sosreport.test_user;run-filesystem-ext4-e656: STARTED
 (03/22) sosreport.py:Sosreport.test_user;run-filesystem-ext4-e656:  PASS (947.82 s)
 (04/22) sosreport.py:Sosreport.test_user;run-filesystem-xfs-4133: STARTED
 (04/22) sosreport.py:Sosreport.test_user;run-filesystem-xfs-4133:  PASS (947.94 s)
 (05/22) sosreport.py:Sosreport.test_plugins;run-filesystem-ext4-e656: STARTED
 (05/22) sosreport.py:Sosreport.test_plugins;run-filesystem-ext4-e656:  PASS (293.66 s)
 (06/22) sosreport.py:Sosreport.test_plugins;run-filesystem-xfs-4133: STARTED
 (06/22) sosreport.py:Sosreport.test_plugins;run-filesystem-xfs-4133:  PASS (293.46 s)
 (07/22) sosreport.py:Sosreport.test_others;run-filesystem-ext4-e656: STARTED
 (07/22) sosreport.py:Sosreport.test_others;run-filesystem-ext4-e656:  PASS (478.13 s)
 (08/22) sosreport.py:Sosreport.test_others;run-filesystem-xfs-4133: STARTED
 (08/22) sosreport.py:Sosreport.test_others;run-filesystem-xfs-4133:  PASS (481.78 s)
 (09/22) sosreport.py:Sosreport.test_archive;run-filesystem-ext4-e656: STARTED
 (09/22) sosreport.py:Sosreport.test_archive;run-filesystem-ext4-e656:  PASS (300.70 s)
 (10/22) sosreport.py:Sosreport.test_archive;run-filesystem-xfs-4133: STARTED
 (10/22) sosreport.py:Sosreport.test_archive;run-filesystem-xfs-4133:  PASS (296.02 s)
 (11/22) sosreport.py:Sosreport.test_PPC;run-filesystem-ext4-e656: STARTED
 (11/22) sosreport.py:Sosreport.test_PPC;run-filesystem-ext4-e656:  PASS (18.62 s)
 (12/22) sosreport.py:Sosreport.test_PPC;run-filesystem-xfs-4133: STARTED
 (12/22) sosreport.py:Sosreport.test_PPC;run-filesystem-xfs-4133:  PASS (18.51 s)
 (13/22) sosreport.py:Sosreport.test_smtchanges;run-filesystem-ext4-e656: STARTED
 (13/22) sosreport.py:Sosreport.test_smtchanges;run-filesystem-ext4-e656:  PASS (406.77 s)
 (14/22) sosreport.py:Sosreport.test_smtchanges;run-filesystem-xfs-4133: STARTED
 (14/22) sosreport.py:Sosreport.test_smtchanges;run-filesystem-xfs-4133:  PASS (405.48 s)
 (15/22) sosreport.py:Sosreport.test_dlpar_cpu_hotplug;run-filesystem-ext4-e656: STARTED
 (15/22) sosreport.py:Sosreport.test_dlpar_cpu_hotplug;run-filesystem-ext4-e656:  PASS (109.31 s)
 (16/22) sosreport.py:Sosreport.test_dlpar_cpu_hotplug;run-filesystem-xfs-4133: STARTED
 (16/22) sosreport.py:Sosreport.test_dlpar_cpu_hotplug;run-filesystem-xfs-4133:  PASS (102.56 s)
 (17/22) sosreport.py:Sosreport.test_dlpar_mem_hotplug;run-filesystem-ext4-e656: STARTED
 (17/22) sosreport.py:Sosreport.test_dlpar_mem_hotplug;run-filesystem-ext4-e656:  PASS (103.06 s)
 (18/22) sosreport.py:Sosreport.test_dlpar_mem_hotplug;run-filesystem-xfs-4133: STARTED
[ 6461.632267] pseries-hotplug-mem: Attempting to hot-remove 1 LMB(s)
[ 6461.741053] Offlined Pages 4096
[ 6461.811681] pseries-hotplug-mem: Memory at a0000000 was hot-removed
[ 6461.822099] pseries-hotplug-mem: Attempting to hot-add 1 LMB(s)
[ 6461.856170] pseries-hotplug-mem: Memory at a0000000 (drc index 8000000a) was hot-added
 (18/22) sosreport.py:Sosreport.test_dlpar_mem_hotplug;run-filesystem-xfs-4133:  PASS (112.11 s)
 (19/22) sosreport.py:Sosreport.test;run-filesystem-ext4-e656: STARTED
 (19/22) sosreport.py:Sosreport.test;run-filesystem-ext4-e656:  PASS (976.63 s)
 (20/22) sosreport.py:Sosreport.test;run-filesystem-xfs-4133: STARTED
 (20/22) sosreport.py:Sosreport.test;run-filesystem-xfs-4133:  PASS (992.49 s)
 (21/22) sosreport.py:Sosreport.test_fs;run-filesystem-ext4-e656: STARTED
 (21/22) sosreport.py:Sosreport.test_fs;run-filesystem-ext4-e656:  PASS (205.65 s)
 (22/22) sosreport.py:Sosreport.test_fs;run-filesystem-xfs-4133: STARTED
 (22/22) sosreport.py:Sosreport.test_fs;run-filesystem-xfs-4133:  PASS (240.66 s)
RESULTS    : PASS 22 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-02-24T01.03-71935d1/results.html
JOB TIME   : 8409.35 s
[root@ltc-zz189-lp1 ras]#

**Comment by PraveenPenguin** [comment]
@Pavithra1602 thanks for update @Gene-Lo as Pavithra requested try with latest code , if facing issue please raise new issue
