### ISSUE TITLE
After running perf_events_test.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: There are 14 test(s) failure, please check the job.log”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2166]
After running perf_events_test.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: There are 14 test(s) failure, please check the job.log”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/141055514-82504a3a-e92c-4300-9871-8fc945bf1ef1.png)

**《Debug-Log of UID 1》**
L0470 DEBUG| [stdout] Testing "L1-dcache-stores" generalized event...            FAILED
L0470 DEBUG| [stdout]   + tests/generalized_events/l1-dcache-loads
L0470 DEBUG| [stdout] Testing exclusive eventsets...                             FAILED
L0470 DEBUG| [stdout]   + tests/attr_fields/format_id_support
L0470 DEBUG| [stdout] Testing ioctl(PERF_EVENT_IOC_PERIOD)...                    FAILED
L0470 DEBUG| [stdout]   + tests/ioctl/ioctl_5_set_output
L0470 DEBUG| [stdout] Testing PERF_EVENT_IOC_SET_OUTPUT ioctl...                 FAILED
L0470 DEBUG| [stdout]   + tests/ioctl/ioctl_6_set_filter
L0470 DEBUG| [stdout] Testing ioctl(PERF_EVENT_IOC_MODIFY_ATTRIBUTES)...         FAILED
L0470 DEBUG| [stdout] 
L0470 DEBUG| [stdout] * Checking perf_event prctl calls
L0470 DEBUG| [stdout]   + tests/prctl/prctl
L0470 DEBUG| [stdout]     
L0470 DEBUG| [stderr] ioctl didn't work Bad file descriptor
L0470 DEBUG| [stdout] Testing prctl()...                                         FAILED
L0470 DEBUG| [stdout]   + tests/prctl/prctl_child
L0470 DEBUG| [stdout] Testing EINVAL generation...                               FAILED
L0470 DEBUG| [stdout]   + tests/error_returns/emfile
L0470 DEBUG| [stdout]     Testing EPERM generation...                                FAILED
L0470 DEBUG| [stdout]   + tests/error_returns/esrch
L0470 DEBUG| [stdout] Testing PERF_SAMPLE_STACK_USER...                          FAILED
L0470 DEBUG| [stdout]   + tests/record_sample/sample_weight
L0470 DEBUG| [stdout] Testing signal after close...                              FAILED
L0470 DEBUG| [stdout] Testing OpenMP results...                                  FAILED
L0470 DEBUG| [stdout]   + tests/openmp/openmp_overflow
L0470 DEBUG| [stdout]     
L0470 DEBUG| [stdout] Testing OpenMP overflow results...                         FAILED
L0470 DEBUG| [stdout]   + tests/openmp/openmp_sample

**《Manual Test Log》**
**※ When run “./run_tests.sh” by manual, “Testing EINVAL generation...” becomes FAILED, while it was PASS by running Avocado script.**
[Manual-Test-Log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7510110/Manual-Test-Log.txt)

  + tests/generalized_events/l1-dcache-stores
    Testing "L1-dcache-stores" generalized event...            FAILED
  + tests/attr_fields/exclusive
    Testing exclusive eventsets...                             FAILED
  + tests/ioctl/ioctl_4_period
    Testing ioctl(PERF_EVENT_IOC_PERIOD)...                    FAILED
  + tests/ioctl/ioctl_5_set_output
    Testing PERF_EVENT_IOC_SET_OUTPUT ioctl...                 FAILED
  + tests/ioctl/ioctl_11_modify_attributes
    ioctl didn't work Bad file descriptor
Testing ioctl(PERF_EVENT_IOC_MODIFY_ATTRIBUTES)...         FAILED

* Checking perf_event prctl calls
  + tests/prctl/prctl
    Testing prctl()...                                         FAILED
  + tests/error_returns/eacces
    Testing EACCES generation...                               FAILED
  + tests/error_returns/einval
    Testing EINVAL generation...                               FAILED
  + tests/error_returns/eperm
    Testing EPERM generation...                                FAILED
  + tests/record_sample/sample_stack_user
    Testing PERF_SAMPLE_STACK_USER...                          FAILED
  + tests/corner_cases/signal_after_close
    Testing signal after close...                              FAILED
* Checking OpenMP support
  + tests/openmp/openmp_test
    Testing OpenMP results...                                  FAILED
  + tests/openmp/openmp_overflow
    Testing OpenMP overflow results...                         FAILED

**《Avocado Test Log》**
[20211105-SUT1-Distro-perf_events_test.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7510113/20211105-SUT1-Distro-perf_events_test.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by Gene-Lo** [comment]
Recently we use **Version 80 of Avocado** to run perf_events_test.py in **Rhel8.4**, and it still shows "FAIL: There are 14 test(s) failure, please check the job.log"

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/145151958-c4f4b5d3-93a7-4a47-96cd-41c3f0293ed4.png)

**《Avocado Test Log》**
[20211207-Avocado80-SUT5.1-perf_events_test.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7673524/20211207-Avocado80-SUT5.1-perf_events_test.zip)

Since in the past we could use **Version 80 of Avocado** to run perf_events_test.py in **Rhel8.2**, and the result was PASS, please check if it is Rhel8.4's limit to run perf_events_test.py. Thanks!!

**《Configuration》**
[Kernel]
4.18.0-305.el8.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Samsung Electronics(M393A4K40BB2-CTD)32GiB x8
PSU ACBEL 2000w *2
Slot1: Broadcom 9300-8i SAS/SATA HBA PCIe Gen3 x8 LP
00VN500 - Seagate Skybolt - HDD 600GB SAS *1

**Comment by PraveenPenguin** [comment]
this issue should be fixed @Gene-Lo can you please try with updated misc test and facing issue please log a issue
