### ISSUE TITLE
After running perftool.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: 2094 Test failed”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2169]
After running perftool.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: 2094 Test failed”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/141059983-3f664e36-f3ab-4149-85d4-d6db8531086a.png)

**《Debug-Log of UID 1》**
L0075 INFO | Test case failed is 10.4: Parsing of PMU event table metrics with fake PMUs             : FAILED!
L0075 INFO | Test case failed is 23.1: Read Only Watchpoint                                          : FAILED!
L0075 INFO | Test case failed is 23.2: Write Only Watchpoint                                         : FAILED!
L0075 INFO | Test case failed is 23.3: Read / Write Watchpoint                                       : FAILED!
L0075 INFO | Test case failed is 23.4: Modify Watchpoint                                             : FAILED!
L0075 INFO | Test case failed is 42.1: Basic BPF filtering                                           : FAILED!
L0075 INFO | Test case failed is 72: Add vfs_getname probe to get syscall args filenames             : FAILED!
L0075 INFO | Test case failed is 74: Use vfs_getname probe to get syscall args filenames             : FAILED!
L0075 INFO | Test case failed is 77: Check open filename arg using perf trace + vfs_getname          : FAILED!

**《Manual-Test-Log of UID 1》**
**※ When run “perf test” by manual, “26: Object code reading” becomes FAILED, while it was PASS by running Avocado script.**
[Manual-Test-Log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7510287/Manual-Test-Log.txt)
10.4: Parsing of PMU event table metrics with fake PMUs             : FAILED!
23.1: Read Only Watchpoint                                          : FAILED!
23.2: Write Only Watchpoint                                         : FAILED!
23.3: Read / Write Watchpoint                                       : FAILED!
23.4: Modify Watchpoint                                             : FAILED!
26: Object code reading                                             : FAILED!
42.1: Basic BPF filtering                                           : FAILED!
72: Add vfs_getname probe to get syscall args filenames             : FAILED!
74: Use vfs_getname probe to get syscall args filenames             : FAILED!
77: Check open filename arg using perf trace + vfs_getname          : FAILED!

**《Avocado Test Log》**
[20211105-SUT1-Distro-perftool.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7510291/20211105-SUT1-Distro-perftool.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by PraveenPenguin** [comment]
closing this issue as we have more patches added recently
