### ISSUE TITLE
After running posixtest.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Compressed file ended before the end-of-stream marker was reached”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2171]
After running posixtest.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Compressed file ended before the end-of-stream marker was reached”.

**《SOL-Log》**
![SOL-Log txt](https://user-images.githubusercontent.com/63998174/141227353-9d633e7f-1e39-406f-bddb-b78fd1e28fd5.png)

**《Debug-Log of UID 1》**
L0035 INFO | Commands configured by file: /root/tests/config/sysinfo/commands
L0035 INFO | Files configured by file: /root/tests/config/sysinfo/files
L0035 INFO | Fail_Commands configured by file: /root/tests/config/sysinfo/fail_commands
L0038 DEBUG| File /root/tests/config/sysinfo/fail_files does not exist.
L0109 INFO | Profilers configured by file: /root/tests/config/sysinfo/profilers
L0310 INFO | INIT 1-Posixtest.test
L0143 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
L0338 DEBUG| Test metadata:
L0340 DEBUG|   filename: /root/tests/tests/avocado-misc-tests/kernel/posixtest.py
L0346 DEBUG|   teststmpdir: /var/tmp/avocado_cnzn_pxa
L0536 INFO | START 1-Posixtest.test
L0208 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
L0199 DEBUG| Not logging /proc/pci (file not found)
L0143 DEBUG| PARAMS (key=test_type, path=*, default=THR) => 'AIO'
L0083 DEBUG| dnf version: 4.4.2
L0658 INFO | Running 'rpm -q gcc'
L0470 DEBUG| [stdout] gcc-8.5.0-4.el8_5.ppc64le
L0740 INFO | Command 'rpm -q gcc' finished with 0 after 0.012371383s
L0658 INFO | Running 'rpm -q make'
L0470 DEBUG| [stdout] make-4.2.1-10.el8.ppc64le
L0740 INFO | Command 'rpm -q make' finished with 0 after 0.010280060s
L0361 INFO | Asset not in cache, fetching it.
L0261 WARNI| No hash provided. Cannot check the asset file integrity.
L0157 INFO | Temporary asset file unavailable due to failed download attempt.
L0465 DEBUG| Test workdir initialized at: /var/tmp/.avocado-taskkcozb5b1/test-results/tmp_dirfec0hche/1-Posixtest.test

**※ According to above log, please check if it is script’s issue.**

**《Avocado Test Log》**
[20211110-SUT1.1-Distro-posixtest.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7517266/20211110-SUT1.1-Distro-posixtest.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER
Slot2: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER
Slot4: Marvell QUAD E'NET (2X1 + 2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER SFP+ SR COPPER)
Slot5: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER
Slot7: Nvidia T4 Accelerator 16GB PCIe3 x16 LP
Slot8: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
0VN497 - Seagate Skybolt - HDD 2400GB SAS *3
00VN629 - Micron 5100 PRO - SSD 3840GB SATA *4
00VN329 - Samsung PM1643 - SSD 3840GB SAS *9

**Comment by Gene-Lo** [comment]
After we use **Version 93 of Avocado** to re-test it, it still shows "ERROR: Compressed file ended before the end-of-stream marker was reached".

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/146855622-8766746c-6f9c-48cd-bb33-d843bb80f340.png)

**《Avocado Test Log》**
[20211220-Avocado93-SUT1.13-posixtest.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7748920/20211220-Avocado93-SUT1.13-posixtest.zip)

**Comment by PraveenPenguin** [comment]
works well to me , can you please update your setup and try out
