### ISSUE TITLE
After running trinity.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Command 'cp -r /var/tmp/.avocado-taskhhwp2jx_/test-results/tmp_dir2pa784xa/1-Trinity.test/trinity-master /home/trinity' failed.”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2172]
After running trinity.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Command 'cp -r /var/tmp/.avocado-taskhhwp2jx_/test-results/tmp_dir2pa784xa/1-Trinity.test/trinity-master /home/trinity' failed”.

**《SOL-Log》**
![SOL-Log txt](https://user-images.githubusercontent.com/63998174/141227567-9e29c519-51e4-44f7-b260-b65bf18f24b9.png)

**《Debug-Log of UID 2》**
L0658 INFO | Running 'cp -r /var/tmp/.avocado-taskhhwp2jx_/test-results/tmp_dir2pa784xa/1-Trinity.test/trinity-master /home/trinity'
L0470 DEBUG| [stderr] cp: cannot create directory '/home/trinity/trinity-master/.deps'
L0470 DEBUG| [stderr] : File exists
L0740 INFO | Command 'cp -r /var/tmp/.avocado-taskhhwp2jx_/test-results/tmp_dir2pa784xa/1-Trinity.test/trinity-master /home/trinity' finished with 1 after 0.069418977s
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:778
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/fuzz/trinity.py", line 69, in setUp
L0045 ERROR|     process.run('cp -r ' + self.sourcedir + ' /home/trinity')
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1093, in run
L0045 ERROR|     raise CmdError(cmd, sp.result)
L0045 ERROR| avocado.utils.process.CmdError: Command 'cp -r /var/tmp/.avocado-taskhhwp2jx_/test-results/tmp_dir2pa784xa/1-Trinity.test/trinity-master /home/trinity' failed.
L0045 ERROR| stdout: b''
L0045 ERROR| stderr: b"cp: cannot create directory '/home/trinity/trinity-master/.deps': File exists\n"
L0045 ERROR| additional_info: None

**《Manual Test Log》**
[root@sut1 trinity-master]# cp -r /var/tmp/.avocado-taskhhwp2jx_/test-results/tmp_dir2pa784xa/1-Trinity.test/trinity-master /home/trinity
[root@sut1 trinity-master]# userdel -r  trinity
userdel: user 'trinity' does not exist
[root@sut1 trinity-master]#
[Manual-Test-Log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7517269/Manual-Test-Log.txt)

**《Avocado Test Log》**
[20211110-SUT1.1-Distro-trinity.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7517283/20211110-SUT1.1-Distro-trinity.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER
Slot2: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER
Slot4: Marvell QUAD E'NET (2X1 + 2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER SFP+ SR COPPER)
Slot5: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER
Slot7: Nvidia T4 Accelerator 16GB PCIe3 x16 LP
Slot8: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
0VN497 - Seagate Skybolt - HDD 2400GB SAS *3
00VN629 - Micron 5100 PRO - SSD 3840GB SATA *4
00VN329 - Samsung PM1643 - SSD 3840GB SAS *9

**Comment by PraveenPenguin** [comment]
@Gene-Lo as we added In ReadME also please pass --test-runner runner while avocado command line as this repo test does not parallel run yet , please try with above option and still face issue let us know

**Comment by Gene-Lo** [comment]
After we try it via cmd "avocado run --test-runner runner trinity.py -m trinity.py.data/trinity.yaml", it shows "WARN: Test passed but there were warnings during execution. Check the log for details". Please check if the result is expected. Thanks!!

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/142789384-da3a10f4-476b-4319-808c-1506ba61591e.png)

**《Avocado Test Log》**
Since the file is too big, we upload it in below messages:

<test-results>
[test-results.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7577727/test-results.zip)

**Comment by Gene-Lo** [comment]
(Other Avocado-Test-Log without "test-results")
[20211118-SUT1.1-Distro-test_runner-trinity.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7577751/20211118-SUT1.1-Distro-test_runner-trinity.zip)

**Comment by Gene-Lo** [comment]
After use **Version 90 of Avocado** to test, the result becomes PASS. Thanks!!
