### ISSUE TITLE
After running ltrace.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Command '/usr/bin/git fetch -q -f -u -t git://git.debian.org/git/collab-maint/ltrace.git master:master' failed”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2174]
After running ltrace.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Command '/usr/bin/git fetch -q -f -u -t git://git.debian.org/git/collab-maint/ltrace.git master:master' failed”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/141397888-c8ff320b-448f-45e1-a73b-e07816badfc2.png)

**《Debug-Log of UID 1》**
L0114 INFO | Fetching git [REP 'git://git.debian.org/git/collab-maint/ltrace.git' BRANCH 'master'] -> /var/tmp/.avocado-task34_2xnh0/test-results/tmp_dirse1zncil/1-Ltrace.test/ltrace
L0658 INFO | Running '/usr/bin/git fetch -q -f -u -t git://git.debian.org/git/collab-maint/ltrace.git master:master'
L0470 DEBUG| [stderr] fatal: unable to connect to git.debian.org:
L0740 INFO | Command '/usr/bin/git fetch -q -f -u -t git://git.debian.org/git/collab-maint/ltrace.git master:master' finished with 128 after 5.350154883s
L0470 DEBUG| [stderr] git.debian.org[0: 194.177.211.202]: errno=Connection refused
L0470 DEBUG| [stderr] git.debian.org[1: 2001:648:2ffc:deb::211:202]: errno=Network is unreachable
L0470 DEBUG| [stderr] 
L0039 ERROR|

**《Manual Test Log》**
[root@sut1 ~]# cd /var/tmp/.avocado-task34_2xnh0/test-results/1-Ltrace.test
[root@sut1 1-Ltrace.test]# ls
data  debug.log  output  stderr  stdout  sysinfo
[root@sut1 1-Ltrace.test]# git clone git://git.debian.org/git/collab-maint/ltrace.git
Cloning into 'ltrace'...
fatal: unable to connect to git.debian.org:
git.debian.org[0: 194.177.211.202]: errno=Connection refused
git.debian.org[1: 2001:648:2ffc:deb::211:202]: errno=Network is unreachable

[root@sut1 1-Ltrace.test]#

**※ Please check if it is source’s issue.**
https://github.com/ice799/ltrace/blob/master/INSTALL

**《Avocado Test Log》**
[20211111-SUT1.2-Distro-ltrace.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7524473/20211111-SUT1.2-Distro-ltrace.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER
Slot2: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER
Slot4: Marvell QUAD E'NET (2X1 + 2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER SFP+ SR COPPER)
Slot5: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER
Slot7: Nvidia T4 Accelerator 16GB PCIe3 x16 LP
Slot8: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
0VN497 - Seagate Skybolt - HDD 2400GB SAS *3
00VN629 - Micron 5100 PRO - SSD 3840GB SATA *4
00VN329 - Samsung PM1643 - SSD 3840GB SAS *9

**Comment by PraveenPenguin** [comment]
@Gene-Lo this PR  #2176 will address the issue , can you please give a try and let us know the result

**Comment by Gene-Lo** [comment]
After we try it via cmd "avocado run --test-runner runner ltrace.py -m ltrace.py.data/ltrace.yaml", it still shows "ERROR: Command '/usr/bin/git fetch -q -f -u -t git://git.debian.org/git/collab-maint/ltrace.git master:master' failed".

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/142380787-e0236ea5-8c46-4c32-8f63-fafefabd19ae.png)

**《Avocado Test Log》**
[20211118-test_runner-ltrace.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7561318/20211118-test_runner-ltrace.zip)

**Comment by PraveenPenguin** [comment]
@Gene-Lo thanks for trying with using `runner` args that are well needed for all the tests. But in this case, as URL is wrong so #2176 addresses the same . Please try  having this command line ` --test-runner runner` and have this PR changes ,

**Comment by PraveenPenguin** [comment]
closing this issue as URL issue got fixed
