### ISSUE TITLE
After running mprotect.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: Please check the logs for debug”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2179]
After running mprotect.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: Please check the logs for debug”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/141448327-ee0751d1-b9cd-4ca4-a7bd-b3dd7efb02f1.png)

**《Debug-Log of UID 1》**
L0658 INFO | Running './mprotect 29548086 0 /dev/zero'
L0740 INFO | Command './mprotect 29548086 0 /dev/zero' finished with -9 after 96.895812857s
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:793
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/memory/mprotect.py", line 109, in test
L0045 ERROR|     self.fail("Please check the logs for debug")
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 979, in fail
L0045 ERROR|     raise exceptions.TestFail(message)
L0045 ERROR| avocado.core.exceptions.TestFail: Please check the logs for debug

**《Manual Test Log》**
[root@sut2 ~]# cd /root/tests/tests/avocado-misc-tests/memory/mprotect.py.data
[root@sut2 mprotect.py.data]# ls
Makefile  mprotect.c  mprotect.yaml
[root@sut2 mprotect.py.data]# chmod 777 *
[root@sut2 mprotect.py.data]# ls
Makefile  mprotect.c  mprotect.yaml
[root@sut2 mprotect.py.data]# make
cc mprotect.c -o mprotect
[root@sut2 mprotect.py.data]# ./mprotect 29548086 0 /dev/zero

memset -> PASS
mprotect start addr: 0x7e3cc8f00000
mprotect end addr: 0x7fffa7250000

mprotect PROT_NONE per page -> PASS

mprotect PROT_READ -> PASS
Accessing last page 0x7fffa7250000 after PROT_READ

READING LAST PAGE -> PASS
Test passed
[root@sut2 mprotect.py.data]#

**※ Since running “./mprotect 29548086 0 /dev/zero” by manual is PASS, please check if it is Avocado script’s issue.**

**《Avocado Test Log》**
[20211111-SUT2-SMT4-mprotect.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7526652/20211111-SUT2-SMT4-mprotect.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by PraveenPenguin** [comment]
@Gene-Lo as we added In ReadME also please pass --test-runner runner while avocado command line as this repo test does not parallel run yet , please try with above option and still face issue let us know

**Comment by Gene-Lo** [comment]
After we run via cmd "avocado run --test-runner runner mprotect.py -m mprotect.py.data/mprotect.yaml", the result becomes PASS. Thanks for your help !!
![SOL-Log](https://user-images.githubusercontent.com/63998174/142380397-24de72f5-8ede-4e6b-84d8-9a1eef40161d.png)
