### ISSUE TITLE
After running transparent_hugepages.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: dd command failed  dd if=/dev/zero of=/tmp/thp_mnt/12 bs=4M count=1”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2180]
After running transparent_hugepages.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: dd command failed  dd if=/dev/zero of=/tmp/thp_mnt/12 bs=4M count=1”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/141450557-3b1c2318-8f4e-4ba0-8fbf-fe66e0115e11.png)

**《Debug-Log of UID 1》**
L0536 INFO | START 1-Thp.test
L0208 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
L0199 DEBUG| Not logging /proc/pci (file not found)
L0143 DEBUG| PARAMS (key=t_dir, path=*, default=/var/tmp/avocado_hn_z3y_y/thp_space) => '/tmp/thp_mnt'
L0143 DEBUG| PARAMS (key=mem_size, path=*, default=2052607) => 100
L0143 DEBUG| PARAMS (key=dd_timeout, path=*, default=900) => 30
L0658 INFO | Running 'mount -o size=100M -t tmpfs none /tmp/thp_mnt'
L0740 INFO | Command 'mount -o size=100M -t tmpfs none /tmp/thp_mnt' finished with 0 after 0.002138246s
L0091 INFO | Stress testing using dd command
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:793
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/memory/transparent_hugepages.py", line 98, in test
L0045 ERROR|     self.fail('dd command failed  %s' % stress_cmd)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 979, in fail
L0045 ERROR|     raise exceptions.TestFail(message)
L0045 ERROR| avocado.core.exceptions.TestFail: dd command failed  dd if=/dev/zero of=/tmp/thp_mnt/12 bs=4M count=1

**《Manual Test Log》**
[root@sut2 ~]# ls /tmp | grep thp_mnt
[root@sut2 ~]# mount -o size=100M -t tmpfs none /tmp/thp_mnt
mount: /tmp/thp_mnt: mount point does not exist.
[root@sut2 ~]#

**※ Since “/tmp/thp_mnt” has never been built, please check is it is Avocado script’s issue.**

**《Avocado Test Log》**
[20211111-SUT2-SMT4-transparent_hugepages.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7526770/20211111-SUT2-SMT4-transparent_hugepages.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by PraveenPenguin** [comment]
@Gene-Lo as  we added In ReadME also please pass ` --test-runner runner` while avocado command line as this repo  test does not parallel run yet  , please try with above option and still face issue let us know

**Comment by Gene-Lo** [comment]
After we run via cmd "avocado run --test-runner runner transparent_hugepages.py -m transparent_hugepages.py.data/transparent_hugepages.yaml", the result becomes PASS. Thanks for your help !!
![SOL-Log](https://user-images.githubusercontent.com/63998174/142380071-c13c0afe-2a3b-4923-8cbf-892b785db094.png)
