### ISSUE TITLE
After running multiport_stress.py in Rhel8.4 with Avocado, it shows 'ERROR: Traceback (most recent call last):\n  File "/usr/lib64/python3.6/imp.py"'

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2191]
When we use **Version 93 of Avocado** to re-test via cmd "avocado run --test-runner runner multiport_stress.py -m multiport_stress.py.data/multiport_stress.yaml", it shows 'ERROR: Traceback (most recent call last):\n  File "/usr/lib64/python3.6/imp.py"'.

**《SOL-Log》**
![1](https://user-images.githubusercontent.com/63998174/144344051-d8753968-f5e4-40f9-b789-a105a5f64e06.png)

**《Test-Log》**
[20211201-Network7-SUT4.2_2.5-test_runner-multiport_stress.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7638358/20211201-Network7-SUT4.2_2.5-test_runner-multiport_stress.zip)

 Then we use **Version 90 of Avocado** to re-test via cmd "avocado run multiport_stress.py -m multiport_stress.py.data/multiport_stress.yaml", it still shows 'ERROR: Traceback (most recent call last):\n  File "/usr/lib64/python3.6/imp.py"'.

**《Test-Log》**
[20211201-Network7-SUT4.2_2.5-multiport_stress.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7638360/20211201-Network7-SUT4.2_2.5-multiport_stress.zip)

Finally we use **Version 80 of Avocado** to re-test via cmd "avocado run multiport_stress.py -m multiport_stress.py.data/multiport_stress.yaml", it still shows 'ERROR: Traceback (most recent call last):\n  File "/usr/lib64/python3.6/imp.py"'.

**《Test-Log》**
[20211202-Network7-SUT4.2_2.5-test_runner-multiport_stress.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7638364/20211202-Network7-SUT4.2_2.5-test_runner-multiport_stress.zip)

Since we could use **Version 80 of Avocado** to test PASS in **Rhel8.2 OS** before, please check if the issue's root cause comes from **Rhel8.4 OS**, and if there is any settings need to change. Thanks !!

**Comment by PraveenPenguin** [comment]
@Gene-Lo please install `netifaces` packages  and than give try

**Comment by Gene-Lo** [comment]
@PraveenPenguin 
After we try it, we can't search & install "python3-netifcases" successfully:
![image](https://user-images.githubusercontent.com/63998174/144366877-34c5c77b-9f44-45c8-9cc2-8cce558e6e60.png)

**《SOL-Log》**
[Install-FAIL.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7639414/Install-FAIL.log)

Please kindly check. Thanks!!

**Comment by Gene-Lo** [comment]
Finally we find methods to install "python3-netifcases".
After use **Version 90 of Avocado** to test, the result becomes PASS. Thanks!!
