### ISSUE TITLE
When using module_unload_load.py of  Avocado (version: 90.0) to test MLNX Network-Cards in Rhel8.4, it shows “ERROR: Module mlx5_fpga_tools not found”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2193]
When using module_unload_load.py of  Avocado (version: 90.0) to test MLNX Network-Cards in Rhel8.4, it shows “ERROR: Module mlx5_fpga_tools not found”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/145153482-478ff2ed-463e-42be-b7e0-ee6d1cfb7231.png)

**《Avocado-Log》**
[20211208-MLNX-module_unload_load.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7673606/20211208-MLNX-module_unload_load.zip)

**《FAIL-message in job.log》**
INFO | Running '/sbin/modinfo mlx5_fpga_tools'
DEBUG| [stderr] modinfo: ERROR: Module mlx5_fpga_tools not found.
INFO | Command '/sbin/modinfo mlx5_fpga_tools' finished with 1 after 0.0005349570055841468s
ERROR| 
ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:784
ERROR| Traceback (most recent call last):
ERROR|   File "/root/tests/tests/avocado-misc-tests/io/driver/module_unload_load.py", line 141, in test
ERROR|     self.module_load_unload(list(set(self.mod_list)))
ERROR|   File "/root/tests/tests/avocado-misc-tests/io/driver/module_unload_load.py", line 104, in module_load_unload
ERROR|     linux_modules.unload_module(mod)
ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/linux_modules.py", line 168, in unload_module
ERROR|     module_info = loaded_module_info(module_name)
ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/linux_modules.py", line 110, in loaded_module_info
ERROR|     "/sbin/modinfo %s" % module_name).decode('utf-8')
ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1212, in system_output
ERROR|     encoding=encoding)
ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1082, in run
ERROR|     raise CmdError(cmd, sp.result)
ERROR| avocado.utils.process.CmdError: Command '/sbin/modinfo mlx5_fpga_tools' failed.
ERROR| stdout: b''
ERROR| stderr: b'modinfo: ERROR: Module mlx5_fpga_tools not found.\n'
ERROR| additional_info: None

**《Test Step》**
1. Equip MLNX Network-Cards in SUT.
2. Follow below SOP document to flash MLNX Network-Cards' FW:
[Mellanox_OFED FW-Flash in Rhel8.4.docx](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7673683/Mellanox_OFED.FW-Flash.in.Rhel8.4.docx)

3. Edit Yaml-File like below:
![Yaml](https://user-images.githubusercontent.com/63998174/145155779-a63f86ff-0b95-4037-9434-90bebd675aac.png)

4. Run module_unload_load.py via cmd:
avocado run module_unload_load.py -m module_unload_load.py.data/module_unload_load.yaml

**《Manual-Test-Log》**
[Manual-Test-Log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7673708/Manual-Test-Log.txt)
![Manual](https://user-images.githubusercontent.com/63998174/145156471-2b02ed2a-dd1e-49c7-82f5-cf4092c37732.png)

**When testing it by manual, we still can't find "mlx5_fpga_tools", but we have already flashed MLNX Network-Cards' FW for Rhel8.4. Besides, if we use other types of Network-Cards (non-MLNX's), the results of module_unload_load.py become PASS.
Please check if it is MLNX Network-Cards' limit to run module_unload_load.py in Rhel8.4.**

**《Configuration》**
[Kernel]
4.18.0-305.el8.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 16 core *2
Micron Technology(36ASF4G72PZ-2G6D1)32GiB x32
Unknown NVMe 1: SAMSUNG MZ1LB960HAJQ-00007
PSU ACBEL 2000w *2
**Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER**
Slot2: Emulex LPE16002B-M6-O 2-port 16Gb Fibre Channel card PCIe3 x8 LP
**Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER**
Slot4: Marvell QUAD E'NET (2X1 + 2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER SFP+ SR COPPER)
Slot5: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
**Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER**
Slot7: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
**Slot8: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)**
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8
00VN628 - Micron 5100 PRO - SSD 1920GB SATA *8
00VN629 - Micron 5100 PRO - SSD 3840GB SATA *8

**Comment by Naresh-ibm** [comment]
it is working now. hence closing.
please open a new issue if still persistence
