### ISSUE TITLE
After running dapl.py in Rhel8.4 with Avocado (version: 90.0), it shows “Cancel: failed connecting to peer”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2194]
After running dapl.py in Rhel8.4 with Avocado (version: 90.0), it shows “Cancel: failed connecting to peer”.

**《SOL-Log》**
Before running dapl.py, we confirm that it can connect to peer:
![SOL-Log](https://user-images.githubusercontent.com/63998174/145157947-7d009887-844e-49b7-919c-7a25fa3ff6dc.png)

**《Avocado-Log》**
[20211207-Network3-SUT4.4_3.1-dapl.py.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7673772/20211207-Network3-SUT4.4_3.1-dapl.py.zip)

**《FAIL-message in job.log》**
INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -O check 192.168.10.2 '''
DEBUG| [stderr] Control socket connect(/root/.ssh/avocado-master-root@192.168.10.2:22): No such file or directory
INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -O check 192.168.10.2 ''' finished with 255 after 0.0032729829981690273s
ERROR| 
ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:766
ERROR| Traceback (most recent call last):
ERROR|   File "/root/tests/tests/avocado-misc-tests/io/net/infiniband/dapl.py", line 79, in setUp
ERROR|     self.cancel("failed connecting to peer")
ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 1002, in cancel
ERROR|     raise exceptions.TestCancel(message)
ERROR| avocado.core.exceptions.TestCancel: failed connecting to peer

**《Test Step》**
1. Equip 2 MLNX Network-Cards in 2 SUTs, and check that they can ping with each other.
2. Edit "/etc/dat.conf" by adding MLNX Network-Cards' ports (ex. enP48p1s0f0 & enP48p1s0f1):
![dat conf](https://user-images.githubusercontent.com/63998174/145158249-9790fe4a-e30e-4d7c-93b1-0905827cb448.png)

3. Edit Yaml-File like below:
![Yaml](https://user-images.githubusercontent.com/63998174/145158715-a797c831-f3ec-4669-9d29-5cd46629b3a8.png)

4. Run dapl.py via cmd: avocado run dapl.py -m dapl.py.data/dapl_infiniband.yaml

**《Manual-Test-Log》**
[Manual-Test-Log.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7673797/Manual-Test-Log.log)

**《Configuration》**
【SUT4】
[Kernel]
4.18.0-305.el8.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 16 core *2
Micron Technology(36ASF4G72PZ-2G6D1)32GiB x32
Unknown NVMe 1: SAMSUNG MZ1LB960HAJQ-00007
PSU ACBEL 2000w *2
**Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER**
Slot2: Emulex LPE16002B-M6-O 2-port 16Gb Fibre Channel card PCIe3 x8 LP
**Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER**
Slot4: Marvell QUAD E'NET (2X1 + 2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER SFP+ SR COPPER)
Slot5: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
**Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER**
Slot7: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
Slot8: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8
00VN628 - Micron 5100 PRO - SSD 1920GB SATA *8
00VN629 - Micron 5100 PRO - SSD 3840GB SATA *8

【SUT3】
[Kernel]
4.18.0-305.el8.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
SK Hynix(HMA82GR7CJR4N-VK)16GiB x16
Unknown NVMe 1: XP400HE30002
PSU ACBEL 2000w *2
**Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER**
Slot2: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER
**Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER**
Slot4: Marvell QUAD E'NET (2X1 + 2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER SFP+ SR COPPER)
Slot5: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
**Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER**
Slot7: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
Slot8: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
00VN500 - Seagate Skybolt - HDD 600GB SAS *1

**Comment by Naresh-ibm** [comment]
latest code working fine. hence closing.
