### ISSUE TITLE
When using ib_pingpong.py of Avocado (version: 90.0) to test MLNX Network-Card in Rhel8.4, it shows “FAIL: test failed”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2195]
When using ib_pingpong.py of Avocado (version: 90.0) to test MLNX Network-Card in Rhel8.4, it shows “FAIL: test failed”.

**※For MLNX Network-Card: (01FT740) 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER**

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/145159927-4d5e8d16-d827-43c1-b94c-2ed8c1a48614.png)

**《Avocado-Log》**
Since the file is too big, we only upload job.log:
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7673845/job.log)

**《FAIL-message in job.log》**
INFO | Running 'ip link set enP48p1s0f0 mtu 1500'
INFO | Command 'ip link set enP48p1s0f0 mtu 1500' finished with 0 after 0.005542855997191509s
INFO | Running 'ip -4 -j address show enP48p1s0f0'
DEBUG| [stdout] [{"ifindex":28,"ifname":"enP48p1s0f0","flags":["BROADCAST","MULTICAST","UP","LOWER_UP"],"mtu":1500,"qdisc":"mq","operstate":"UP","group":"default","txqlen":1000,"addr_info":[{"family":"inet","local":"192.168.10.1","prefixlen":24,"scope":"global","label":"enP48p1s0f0","valid_life_time":4294967295,"preferred_life_time":4294967295}]}]
INFO | Command 'ip -4 -j address show enP48p1s0f0' finished with 0 after 0.001609077000466641s
INFO | Running 'ip -4 -j address show enP48p1s0f0'
DEBUG| [stdout] [{"ifindex":28,"ifname":"enP48p1s0f0","flags":["BROADCAST","MULTICAST","UP","LOWER_UP"],"mtu":1500,"qdisc":"mq","operstate":"UP","group":"default","txqlen":1000
DEBUG| [stdout] ,"addr_info":[{"family":"inet","local":"192.168.10.1","prefixlen":24,"scope":"global","label":"enP48p1s0f0","valid_life_time":4294967295,"preferred_life_time":4294967295}]}]
INFO | Command 'ip -4 -j address show enP48p1s0f0' finished with 0 after 0.0016505509993294254s
INFO | Running 'ip -4 -j address show enP48p1s0f0'
DEBUG| [stdout] [{"ifindex":28,"ifname":"enP48p1s0f0","flags":["BROADCAST","MULTICAST","UP","LOWER_UP"],"mtu":1500,"qdisc":"mq","operstate":"UP","group":"default","txqlen":1000,"addr_info":[{"family":"inet","local":"192.168.10.1","prefixlen":24,"scope":"global","label":"enP48p1s0f0","valid_life_time":4294967295,"preferred_life_time":4294967295}]}]
INFO | Command 'ip -4 -j address show enP48p1s0f0' finished with 0 after 0.0005285779989208095s
INFO | Running '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -q 192.168.10.2 'sudo ip link set enP48p1s0f0 mtu 1500''
INFO | Command '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -q 192.168.10.2 'sudo ip link set enP48p1s0f0 mtu 1500'' finished with 0 after 1.8943258770013927s
INFO | Running '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -q 192.168.10.2 'ip -4 -j address show enP48p1s0f0''
DEBUG| [stdout] [{"ifindex":32,"ifname":"enP48p1s0f0","flags":["BROADCAST","MULTICAST","UP","LOWER_UP"],"mtu":1500,"qdisc":"mq","operstate":"UP","group":"default","txqlen":1000,"addr_info":[{"family":"inet","local":"192.168.10.2","prefixlen":24,"broadcast":"192.168.10.255","scope":"global","noprefixroute":true,"label":"enP48p1s0f0","valid_life_time":4294967295,"preferred_life_time":4294967295}]}]
INFO | Command '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -q 192.168.10.2 'ip -4 -j address show enP48p1s0f0'' finished with 0 after 0.04756331799944746s
INFO | Running '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -q 192.168.10.2 'ip -4 -j address show enP48p1s0f0''
DEBUG| [stdout] [{"ifindex":32,"ifname":"enP48p1s0f0","flags":["BROADCAST","MULTICAST","UP","LOWER_UP"],"mtu":1500,"qdisc":"mq","operstate":"UP","group":"default","txqlen":1000,"addr_info":[{"family":"inet","local":"192.168.10.2","prefixlen":24,"broadcast":"192.168.10.255","scope":"global","noprefixroute":true,"label":"enP48p1s0f0","valid_life_time":4294967295,"preferred_life_time":4294967295}]}]
INFO | Command '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -q 192.168.10.2 'ip -4 -j address show enP48p1s0f0'' finished with 0 after 0.03731337600038387s
INFO | Running '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -q 192.168.10.2 'ip -4 -j address show enP48p1s0f0''
DEBUG| [stdout] [{"ifindex":32,"ifname":"enP48p1s0f0","flags":["BROADCAST","MULTICAST","UP","LOWER_UP"],"mtu":1500,"qdisc":"mq","operstate":"UP","group":"default","txqlen":1000,"addr_info":[{"family":"inet","local":"192.168.10.2","prefixlen":24,"broadcast":"192.168.10.255","scope":"global","noprefixroute":true,"label":"enP48p1s0f0","valid_life_time":4294967295,"preferred_life_time":4294967295}]}]
INFO | Command '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -q 192.168.10.2 'ip -4 -j address show enP48p1s0f0'' finished with 0 after 0.03849156700016465s
INFO | Running '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O exit 192.168.10.2 '''
DEBUG| [stderr] Exit request sent.
INFO | Command '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O exit 192.168.10.2 ''' finished with 0 after 0.003135298000415787s
DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
INFO | Running 'kill -19 674783'
INFO | Command 'kill -19 674783' finished with 0 after 0.0016158459984580986s
INFO | Running 'kill -9 674783'
INFO | Command 'kill -9 674783' finished with 0 after 0.000614697997662006s
INFO | Running 'kill -18 674783'
INFO | Command 'kill -18 674783' finished with 0 after 0.001567289000377059s
INFO | Running 'kill -19 674788'
INFO | Command 'kill -19 674788' finished with 0 after 0.0003405169991310686s
INFO | Running 'kill -9 674788'
INFO | Command 'kill -9 674788' finished with 0 after 0.001080063000699738s
INFO | Running 'kill -18 674788'
INFO | Command 'kill -18 674788' finished with 0 after 0.0010055790007754695s
ERROR| FAIL 01-ib_pingpong.py:PingPong.test_ib_pingpong;run-Test-ud_pingpong-mtu-1500-parameters-f1cc -> TestFail: test faile

**《Test Step》**
1. Equip 2 MLNX Network-Cards in 2 SUTs, and check that they can ping with each other.
2.  Search the codes of Network-Card's ports (ex. enP48p1s0f0 & enP48p1s0f1) via cmd: ibdev2netdev
![ibdev2netdev](https://user-images.githubusercontent.com/63998174/145160608-e6192bb3-9de3-4399-9291-12adabc323d8.png)

3. Edit Yaml-File like below:
![Yaml](https://user-images.githubusercontent.com/63998174/145160806-7393f96b-acd3-4ce1-af1e-e4bfe84a16e1.png)

4. Run ib_pingpong.py via cmd: avocado run ib_pingpong.py -m ib_pingpong.py.data/ib_pingpong_infiniband.yaml

**《Manual-Test-Log》**
[Manual-Test-Log.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7673867/Manual-Test-Log.log)

**※For MLNX Network-Card: (00WT175) 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER**
**《SOL-Log》**
![SOL-Log(2)](https://user-images.githubusercontent.com/63998174/145161134-a8b705d3-667b-4c81-9aae-b78627b57d7e.png)

**《Avocado-Log》**
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7673878/job.log)

**※For MLNX Network-Card: (01FT751) 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER**
**《SOL-Log》**
![SOL-Log(3)](https://user-images.githubusercontent.com/63998174/145161556-8bf4365e-4d83-40d7-ae0a-bc4478057312.png)

**《Avocado-Log》**
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7673894/job.log)

**※Configuration**
【SUT4】
[Kernel]
4.18.0-305.el8.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 16 core *2
Micron Technology(36ASF4G72PZ-2G6D1)32GiB x32
Unknown NVMe 1: SAMSUNG MZ1LB960HAJQ-00007
PSU ACBEL 2000w *2
**Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER**
Slot2: Emulex LPE16002B-M6-O 2-port 16Gb Fibre Channel card PCIe3 x8 LP
**Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER**
Slot4: Marvell QUAD E'NET (2X1 + 2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER SFP+ SR COPPER)
Slot5: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
**Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER**
Slot7: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
Slot8: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8
00VN628 - Micron 5100 PRO - SSD 1920GB SATA *8
00VN629 - Micron 5100 PRO - SSD 3840GB SATA *8

【SUT3】
[Kernel] 4.18.0-305.el8.ppc64le
[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
SK Hynix(HMA82GR7CJR4N-VK)16GiB x16
Unknown NVMe 1: XP400HE30002
PSU ACBEL 2000w *2
**Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER**
Slot2: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER
**Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER**
Slot4: Marvell QUAD E'NET (2X1 + 2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER SFP+ SR COPPER)
Slot5: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
**Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER**
Slot7: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
Slot8: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
00VN500 - Seagate Skybolt - HDD 600GB SAS *1

**Comment by Naresh-ibm** [comment]
working fine with latest avocado version. hence closing
