### ISSUE TITLE
After running avago9361_vd.py in Rhel8.4 with Avocado (version: 93.0), it shows “FAIL: Failed to set drive to online state”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2205]
After running avago9361_vd.py in Rhel8.4 with Avocado (version: 93.0), it shows “FAIL: Failed to set drive to online state”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/146507168-177e0a1b-d796-438a-8f5f-0c28d77f71ef.png)

**《Avocado-Log》**
[20211217-Storage1-avago9361_vd.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7733361/20211217-Storage1-avago9361_vd.zip)

**《FAIL-message in job.log》**
![FAIL-Log](https://user-images.githubusercontent.com/63998174/146507402-b2c01f07-019c-4bd9-a7e2-37e839a2553b.png)

However, when we run it by manual, the result becomes PASS:

**《Manual-Test-Log》**
[Manual-Test-Log.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7733376/Manual-Test-Log.log)
![Manual-Test-Log](https://user-images.githubusercontent.com/63998174/146507501-9c09d3a6-3f7f-4f36-94af-0d970391d690.png)

Please check if it is script's issue. Thanks!!

**《Configuration》**
[Kernel]
4.18.0-305.el8.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 12 core *2
SK Hynix(HMA82GR7CJR4N-VK)16GiB x16
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER
Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER
Slot4: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot5: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER
Slot10: Broadcom 9300-8i SAS/SATA HBA PCIe Gen3 x8 LP
00VN501 - Seagate Skybolt - HDD 1200GB SAS x8

**Comment by Naresh-ibm** [comment]
it is working fine hence closing. feel free to open new issue if still persistence in your environment.
