### ISSUE TITLE
After running xfstests.py in Rhel8.4 OS with Avocado (version: 93.0), Rhel8.4 OS will automatically reboot and can't complete the test of xfstests.py.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2207]
After running xfstests.py in Rhel8.4 OS with Avocado (version: 93.0), Rhel8.4 OS will automatically reboot and can't complete the test of xfstests.py.

**《Test Step》**
1. Equip 2 Disk on SUT, create 500GB partitions on both of them, and format them to "ext3" via cmd:
$ mkfs.ext3 /dev/sda1
$ mkfs.ext3 /dev/sdb1
![lsblk](https://user-images.githubusercontent.com/63998174/146751211-ae434344-9d58-45a4-b220-b649ad1ce34c.png)

2. Enter "/home" and delete "123456-fsgqa" & "fsgqa" via cmd:
$ userdel 123456-fsgqa
$ userdel fsgqa
$ rm -rf 123456-fsgqa fsgqa

3. Edit xfstests.yaml like below:
![yaml](https://user-images.githubusercontent.com/63998174/146751460-97eb76b0-0274-4287-81f2-b4f8a4cfff05.png)

4. Run xfstests.py via cmd: avocado run --test-runner runner xfstests.py -m xfstests.py.data/xfstests.yaml

**《SOL-Log & dmesg》**
Connect to SUT via cmd: ssh root@<BMC_IP> -p 2200
And then run xfstests.py.
[SOL-Log&dmesg.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7744427/SOL-Log.dmesg.log)

**《Avocado-Test-Log》**
[job-2021-12-20T16.40-04296cf.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7744404/job-2021-12-20T16.40-04296cf.zip)

**《job.log before OS reboot》**
L0470 DEBUG| [stdout] ext4/051
L0470 DEBUG| [stdout]
L0470 DEBUG| [stdout]  78s
L0470 DEBUG| [stdout]
L0470 DEBUG| [stdout] ext4/052
L0470 DEBUG| [stdout]
L0470 DEBUG| [stdout]  13s
L0470 DEBUG| [stdout]
L0470 DEBUG| [stdout] ext4/053
L0470 DEBUG| [stdout]
L0470 DEBUG| [stdout] [not run]
L0470 DEBUG| [stdout] This test is only relevant for kernel versions 5.12 and higher
L0470 DEBUG| [stdout] ext4/054
L0470 DEBUG| [stdout]

**《Manual-Test-Log》**
**Since it shows "need to define parameters for host sut1", we can't run xfstests.py just by manual.**
[Manual-Test-Log.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7744420/Manual-Test-Log.log)

[root@sut1 ~]# useradd 123456-fsgqa
Creating mailbox file: File exists
[root@sut1 ~]# useradd fsgqa
Creating mailbox file: File exists
[root@sut1 ~]# ./check  -g auto
Warning: need to define parameters for host sut1
       or set variables:
        TEST_DIR TEST_DEV
[root@sut1 ~]#

**《Configuration》**
[Kernel]
4.18.0-305.el8.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology(18ASF2G72PZ-2G9E1)16GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot1: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
00VN629 - Micron 5100 PRO - SSD 3840GB SATA *2

**Comment by PraveenPenguin** [comment]
@disgoel is this still an issue ?

**Comment by disgoel** [comment]
> @disgoel is this still an issue ?

@PraveenPenguin can be closed, not seeing the issue with recent runs.

**Comment by PraveenPenguin** [comment]
thanks @disgoel
