### ISSUE TITLE
When using disk_info.py to test NVMe-SSD in Rhel8.2 with Avocado (version: 94.0), it shows "\nGiven disk nvme11n1 is not present in lshw -c disk  | grep -i nvme11n1\nGiven disk nvme11n1 not having uuid".

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2211]
When using disk_info.py to test NVMe-SSD in Rhel8.2 with Avocado (version: 94.0), it shows "\nGiven disk nvme11n1 is not present in lshw -c disk  | grep -i nvme11n1\nGiven disk nvme11n1 not having uuid".

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/147522486-fb8e2819-171c-473f-bf34-a993a6028665.png)

**《job.log》**
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7782494/job.log)

**《FAIL message in job.log》**
【Item 3】
18:33:36 INFO | Command 'lshw -c disk | grep -n "/dev/nvme11n1" | cut -d ":" -f 1' finished with 0 after 0.995512843s
18:33:36 ERROR| 
18:33:36 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:761
18:33:36 ERROR| Traceback (most recent call last):
18:33:36 ERROR|   File "/root/tests/tests/avocado-misc-tests/io/disk/disk_info.py", line 282, in test
18:33:36 ERROR|     self.fail("Some tests failed. Details below:\n%s" % "\n".join(msg))
18:33:36 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 892, in fail
18:33:36 ERROR|     raise exceptions.TestFail(message)
18:33:36 ERROR| avocado.core.exceptions.TestFail: Some tests failed. Details below:
18:33:36 ERROR| Given disk nvme11n1 is not present in lshw -c disk  | grep -i nvme11n1
18:33:36 ERROR| Given disk nvme11n1 not having uuid

【Item 4】
18:35:47 INFO | Running 'lshw -c disk | grep -n "/dev/nvme11n1" | cut -d ":" -f 1'
18:35:48 INFO | Command 'lshw -c disk | grep -n "/dev/nvme11n1" | cut -d ":" -f 1' finished with 0 after 0.977909272s
18:35:48 ERROR| 
18:35:48 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:761
18:35:48 ERROR| Traceback (most recent call last):
18:35:48 ERROR|   File "/root/tests/tests/avocado-misc-tests/io/disk/disk_info.py", line 282, in test
18:35:48 ERROR|     self.fail("Some tests failed. Details below:\n%s" % "\n".join(msg))
18:35:48 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 892, in fail
18:35:48 ERROR|     raise exceptions.TestFail(message)
18:35:48 ERROR| avocado.core.exceptions.TestFail: Some tests failed. Details below:
18:35:48 ERROR| Given disk nvme11n1 is not present in lshw -c disk  | grep -i nvme11n1
18:35:48 ERROR| Given disk nvme11n1 not having uuid

**《Manual-Test-log》**
[Manual-Test-log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7782503/Manual-Test-log.txt)
**※When we run "ls /dev/disk/by-uuid -l| grep -i nvme11n1", nvme11n1 and its uuid can be found.**

[root@PM ~]# ls /dev/disk/by-uuid -l| grep -i nvme11n1
lrwxrwxrwx. 1 root root 14 Dec 22 11:38 bdfdbe65-06a8-4933-96c0-b780ae03954a -> ../../nvme11n1
[root@PM ~]# blkid /dev/nvme11n1
/dev/nvme11n1: UUID="bdfdbe65-06a8-4933-96c0-b780ae03954a" TYPE="xfs"

**In addition, when we use disk_info.py to test SATA or SAS disks, no issues happened**
**Please check if it is disk_info.py's script-issue or limit to test NVMe-SSD.**

**《Configuration》**
[Kernel]
4.18.0-193.28.1.el8_2.ppc64le

[FW Config]
BMC: op940.21.mih-1-0-g62d91d0138
Pnor: IBM-mihawk-ibm-OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Samsung Electronics(M393A2K40BB2-CTD) 16GiB x8
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot4: Bear Lake card
Slot9: Bear Lake card
<JBOF>
PM1735 - SSD 800GB NVMe *24

**Comment by Naresh-ibm** [comment]
this is a feature limitation, lshw holds the logical name and not the namespace details. this has been inherited from other block device logic where we have logical names as sdX. but in case of nvme we have nvme0c0n1 but name space we are looking in this code is nvme0n1 which is not happening here.
same is tracked here

https://bugzilla.linux.ibm.com/show_bug.cgi?id=201192
