### ISSUE TITLE
When using module_unload_load.py to test NVMe-SSD in Rhel8.3 with Avocado (version: 94.0), it shows "FAIL: Failed Modules: ['nvme']". 

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2212]
When using module_unload_load.py to test NVMe-SSD in Rhel8.3 with Avocado (version: 94.0), it shows "FAIL: Failed Modules: ['nvme']". 

**《SOL Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/147531260-0070bd92-8422-4e00-ae6d-a9bd17b6a1e4.png)

**《job.log》**
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7782982/job.log)

**《FAIL message in job.log》**
avocado.utils.process INFO | Running '/sbin/modprobe -r nvme'
avocado.utils.process INFO | Command '/sbin/modprobe -r nvme' finished with 0 after 39.015583707s
avocado.utils.linux_modules INFO | Module nvme unloaded
avocado.test INFO | loading module : nvme
avocado.utils.process INFO | Running '/sbin/modprobe nvme'
avocado.utils.process INFO | Command '/sbin/modprobe nvme' finished with 0 after 0.566025001s
avocado.test ERROR|
avocado.test ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:761
avocado.test ERROR| Traceback (most recent call last):
avocado.test ERROR|   File "/root/tests/tests/avocado-misc-tests/io/driver/module_unload_load.py", line 144, in test
avocado.test ERROR|     self.fail("Failed Modules: %s" % self.error_modules)
avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 892, in fail
avocado.test ERROR|     raise exceptions.TestFail(message)
avocado.test ERROR| avocado.core.exceptions.TestFail: Failed Modules: ['nvme']

**《Manual-Test-log》**
[Manual-Test-Log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7782989/Manual-Test-Log.txt)
**※When we manually run "/sbin/modprobe -r nvme" and "/sbin/modprobe nvme", nvme module can be successfully removed and re-loaded. Please check if it is module_unload_load.py's script-issue.**

**《Configuration》**
[Kernel]
4.18.0-240.el8.ppc64le

[FW Config]
BMC: op940.21.mih-1-0-g62d91d0138
Pnor: IBM-mihawk-ibm-OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Samsung Electronics(M393A2K40BB2-CTD) 16GiB x8
SSD 2.5" 3.84TB SAS MZILT3T8HALS-MS33 *1
MEGARAID 9361-8I SAS3 CONTROLLER *1
PSU ACBEL 2000w *2
Slot4: Bear Lake card
Slot9: Bear Lake card
<JBOF>
PM1735 - SSD 800GB NVMe *24

**Comment by Naresh-ibm** [comment]
it is working fine now.


06:20:00 INFO    : Running Host Tests Suite io_nvme_module_unload_load_module_unload_load
06:20:00 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/driver/module_unload_load.py -m /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/driver/module_unload_load.py.data/module_unload_load.yaml --force-job-id 185b35c7e199f8cf07c32f3cc58a2e4e5c40ff33  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : 185b35c7e199f8cf07c32f3cc58a2e4e5c40ff33
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-01-23T06.20-185b35c/job.log
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/driver/module_unload_load.py:ModuleLoadUnload.test;run-Parameters-e326: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/driver/module_unload_load.py:ModuleLoadUnload.test;run-Parameters-e326: PASS (73.69 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-01-23T06.20-185b35c/results.html
JOB TIME   : 91.02 s
06:21:35 INFO    : 


open new issue if you still see it
