### ISSUE TITLE
When using nvme_cli_selftests.py to test NVMe-SSD in Rhel8.3 with Avocado (version: 94.0), nvme_compare_test and nvme_smart_log_test are FAIL, but Manual-Test are PASS.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2213]
When using nvme_cli_selftests.py to test NVMe-SSD in Rhel8.3 with Avocado (version: 94.0), nvme_compare_test and nvme_smart_log_test are FAIL, but Manual-Test are PASS.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/147533149-eb1ea800-cdd2-425c-a0bb-043f3c58b603.png)

**《job.log》**
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7783104/job.log)

**《FAIL message in job.log》**
【Item 2 - nvme_compare_test】
avocado.utils.process INFO | Running 'nose2 --verbose nvme_compare_test'
avocado.utils.process DEBUG| [stdout] /sys/devices/pci0003:00/0003:00:00.0/0003:01:00.0/0003:02:00.0/0003:03:00.0/0003:04:00.0/0003:05:00.0/0003:06:0a.0/0003:11:00.0/nvme/nvme11
avocado.utils.process DEBUG| [stderr] nvme_compare_test.TestNVMeCompareCmd.test_nvme_compare ...
avocado.utils.process DEBUG| [stderr] Rounding data size to fit block count (4096 bytes)
avocado.utils.process DEBUG| [stderr] write: Success
avocado.utils.process DEBUG| [stderr] Rounding data size to fit block count (4096 bytes)
avocado.utils.process DEBUG| [stderr] NVMe status: COMPARE_FAILED: The command failed due to a miscompare during a Compare command(0x285)
avocado.utils.process DEBUG| [stderr] Rounding data size to fit block count (4096 bytes)
avocado.utils.process DEBUG| [stderr] compare: Success
avocado.utils.process DEBUG| [stderr] ok
avocado.utils.process DEBUG| [stderr]
avocado.utils.process DEBUG| [stderr] ----------------------------------------------------------------------
avocado.utils.process DEBUG| [stderr] Ran 1 test in 0.032s
avocado.utils.process DEBUG| [stderr]
avocado.utils.process DEBUG| [stderr] OK
avocado.utils.process INFO | Command 'nose2 --verbose nvme_compare_test' finished with 0 after 0.849414796s
avocado.test ERROR|
avocado.test ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:761
avocado.test ERROR| Traceback (most recent call last):
avocado.test ERROR|   File "/root/tests/tests/avocado-misc-tests/io/disk/ssd/nvme_cli_selftests.py", line 84, in test_selftests
avocado.test ERROR|     self.fail("Test Failed")
avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 892, in fail
avocado.test ERROR|     raise exceptions.TestFail(message)
avocado.test ERROR| avocado.core.exceptions.TestFail: Test Failed

【Item 14 - nvme_smart_log_test】
avocado.utils.process INFO | Running 'nose2 --verbose nvme_smart_log_test'
avocado.utils.process DEBUG| [stdout] /sys/devices/pci0003:00/0003:00:00.0/0003:01:00.0/0003:02:00.0/0003:03:00.0/0003:04:00.0/0003:05:00.0/0003:06:0a.0/0003:11:00.0/nvme/nvme11
avocado.utils.process DEBUG| [stderr] nvme_smart_log_test.TestNVMeSmartLogCmd.test_smart_log ...
avocado.utils.process DEBUG| [stderr] NVMe status: INVALID_FIELD: A reserved coded value or an unsupported value in a defined field(0x2)
avocado.utils.process DEBUG| [stderr] FAIL
avocado.utils.process DEBUG| [stderr]
avocado.utils.process DEBUG| [stderr] ======================================================================
avocado.utils.process DEBUG| [stderr] FAIL: nvme_smart_log_test.TestNVMeSmartLogCmd.test_smart_log
avocado.utils.process DEBUG| [stderr] ----------------------------------------------------------------------
avocado.utils.process DEBUG| [stderr] Traceback (most recent call last):
avocado.utils.process DEBUG| [stderr]   File "/var/tmp/avocado_th6zwicy/nvme-cli-master/tests/nvme_smart_log_test.py", line 86, in test_smart_log
avocado.utils.process DEBUG| [stderr]     assert_equal(self.get_smart_log_all_ns(), 0)
avocado.utils.process DEBUG| [stderr]   File "/var/tmp/avocado_th6zwicy/nvme-cli-master/tests/nvme_smart_log_test.py", line 80, in get_smart_log_all_ns
avocado.utils.process DEBUG| [stderr]     self.get_smart_log_ns(ns_list[nsid])
avocado.utils.process DEBUG| [stderr]   File "/var/tmp/avocado_th6zwicy/nvme-cli-master/tests/nvme_smart_log_test.py", line 69, in get_smart_log_ns
avocado.utils.process DEBUG| [stderr]     return self.get_smart_log(nsid)
avocado.utils.process DEBUG| [stderr]   File "/var/tmp/avocado_th6zwicy/nvme-cli-master/tests/nvme_test.py", line 391, in get_smart_log
avocado.utils.process DEBUG| [stderr]     assert_equal(err, 0, "ERROR : nvme smart log failed")
avocado.utils.process DEBUG| [stderr] AssertionError: 22 != 0 : ERROR : nvme smart log failed
avocado.utils.process DEBUG| [stderr]
avocado.utils.process DEBUG| [stderr] ----------------------------------------------------------------------
avocado.utils.process DEBUG| [stderr] Ran 1 test in 0.016s
avocado.utils.process DEBUG| [stderr]
avocado.utils.process DEBUG| [stderr] FAILED (failures=1)

**《Manual-Test-log》**
【For Item 2 - nvme_compare_test】
When we manually test "nvme compare" by below cmds, it can successfully distinguish the file's content in NVMe-SSD:
![Manual1](https://user-images.githubusercontent.com/63998174/147533980-8687c101-1cd7-452d-a07b-9ab83e50f30e.png)

【For Item 14 - nvme_smart_log】
When we manually run cmd "nvme smart-log /dev/nvme12", it can successfully show smart-log:
![Manual2](https://user-images.githubusercontent.com/63998174/147534228-46511e89-41bc-4061-89fb-d92177e04018.png)

Please check if it is nvme_cli_selftests.py's script-script.

**《Configuration》**
[Kernel]
4.18.0-193.28.1.el8_2.ppc64le

[FW Config]
BMC: op940.21.mih-1-0-g62d91d0138
Pnor: IBM-mihawk-ibm-OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Samsung Electronics(M393A2K40BB2-CTD) 16GiB x8
SSD 2.5" 3.84TB SAS MZILT3T8HALS-MS33 *1
MEGARAID 9361-8I SAS3 CONTROLLER *1
PSU ACBEL 2000w *2
Slot4: Bear Lake card
Slot9: Bear Lake card

PM1735 - SSD 800GB NVMe *24

**Comment by Naresh-ibm** [comment]
it is working fine now.


[root@ltcever60-lp12 ssd]# avocado run --max-parallel-tasks=1 nvme_cli_selftests.py -m nvme_cli_selftests.py.data/nvme_cli_selftests.yaml
Fetching asset from nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests
JOB ID     : fe1d6cf6f634b561dc0dcac6f2261a7bbba9ef3e
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-02-20T08.57-fe1d6cf/job.log
 (01/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_id_ctrl_test-2c0b: STARTED
 (01/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_id_ctrl_test-2c0b: PASS (3.81 s)
 (02/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_compare_test-6e10: STARTED
 (02/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_compare_test-6e10: PASS (0.58 s)
 (03/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_error_log_test-59f6: STARTED
 (03/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_error_log_test-59f6: PASS (0.59 s)
 (04/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_test_logger-c135: STARTED
 (04/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_test_logger-c135: PASS (0.58 s)
 (05/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_read_write_test-199d: STARTED
 (05/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_read_write_test-199d: PASS (0.59 s)
 (06/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_simple_template_test-d152: STARTED
 (06/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_simple_template_test-d152: PASS (0.59 s)
 (07/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_id_ns_test-3978: STARTED
 (07/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_id_ns_test-3978: PASS (0.58 s)
 (08/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_fw_log_test-732d: STARTED
 (08/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_fw_log_test-732d: PASS (0.59 s)
 (09/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_flush_test-68e4: STARTED
 (09/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_flush_test-68e4: PASS (0.59 s)
 (10/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_test_io-0927: STARTED
 (10/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_test_io-0927: PASS (0.59 s)
 (11/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_get_features_test-51a4: STARTED
 (11/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_get_features_test-51a4: PASS (0.59 s)
 (12/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_writezeros_test-73a3: STARTED
 (12/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_writezeros_test-73a3: PASS (0.59 s)
 (13/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_smart_log_test-62fc: STARTED
 (13/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_smart_log_test-62fc: PASS (0.59 s)
 (14/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_test-5053: STARTED
 (14/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_test-5053: PASS (0.59 s)
RESULTS    : PASS 14 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-02-20T08.57-fe1d6cf/results.html
JOB TIME   : 20.53 s
[root@ltcever60-lp12 ssd]#

feel free to report a new issue if still seen
