### ISSUE TITLE
When using nvmetest.py to test NVMe-SSD in Rhel8.3 with Avocado (version: 94.0), it shows "ERROR: Command 'make' failed" and "CANCEL: /dev/nvme11n1 does not exist".

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2214]
When using nvmetest.py to test NVMe-SSD in Rhel8.3 with Avocado (version: 94.0), it shows "ERROR: Command 'make' failed" and "CANCEL: /dev/nvme11n1 does not exist".

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/147539920-fe86bf80-5538-42b3-bb95-628243dd040d.png)

**《Yaml Content》**
![Yaml](https://user-images.githubusercontent.com/63998174/147540045-d58fa5fe-af55-4e78-935c-264bb017238b.png)
Since we never input the parameter of "firmware_url", it is expected that 【Item 2】 shows "CANCEL: firmware url not given". However, other Test-Items should be PASS.

**《job.log》**
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7783402/job.log)

**《FAIL message in job.log》**
【Item 1】
avocado.utils.process INFO | Running './NVME-VERSION-GEN'
avocado.utils.process DEBUG| [stderr] NVME_VERSION = 1.14
avocado.utils.process INFO | Command './NVME-VERSION-GEN' finished with 0 after 0.003777728s
avocado.utils.process INFO | Running 'make'
avocado.utils.process DEBUG| [stderr] Makefile:81: *** "No libnvme found".  Stop.
avocado.utils.process INFO | Command 'make' finished with 2 after 0.040859229s
avocado.test ERROR|
avocado.test ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:746
avocado.test ERROR| Traceback (most recent call last):
avocado.test ERROR|   File "/root/tests/tests/avocado-misc-tests/io/disk/ssd/nvmetest.py", line 60, in setUp
avocado.test ERROR|     build.make(".")
avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/build.py", line 105, in make
avocado.test ERROR|     result = run_make(path, make, extra_args, kwargs)
avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/build.py", line 84, in run_make
avocado.test ERROR|     make_process = process.run(cmd, **process_kwargs)
avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1015, in run
avocado.test ERROR|     raise CmdError(cmd, sp.result)
avocado.test ERROR| avocado.utils.process.CmdError: Command 'make' failed.
avocado.test ERROR| stdout: b''
avocado.test ERROR| stderr: b'Makefile:81: *** "No libnvme found".  Stop.\n'
avocado.test ERROR| additional_info: None

【Item 3】
avocado.utils.process INFO | Running './NVME-VERSION-GEN'
avocado.utils.process INFO | Command './NVME-VERSION-GEN' finished with 0 after 0.006143952s
avocado.utils.process INFO | Running 'make'
avocado.utils.process DEBUG| [stderr] Makefile:81: *** "No libnvme found".  Stop.
avocado.utils.process INFO | Command 'make' finished with 2 after 0.035430878s
avocado.test ERROR|
avocado.test ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:746
avocado.test ERROR| Traceback (most recent call last):
avocado.test ERROR|   File "/root/tests/tests/avocado-misc-tests/io/disk/ssd/nvmetest.py", line 60, in setUp
avocado.test ERROR|     build.make(".")
avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/build.py", line 105, in make
avocado.test ERROR|     result = run_make(path, make, extra_args, kwargs)
avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/build.py", line 84, in run_make
avocado.test ERROR|     make_process = process.run(cmd, **process_kwargs)
avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1015, in run
avocado.test ERROR|     raise CmdError(cmd, sp.result)
avocado.test ERROR| avocado.utils.process.CmdError: Command 'make' failed.
avocado.test ERROR| stdout: b''
avocado.test ERROR| stderr: b'Makefile:81: *** "No libnvme found".  Stop.\n'
avocado.test ERROR| additional_info: None

【Item 5】
avocado.test INFO | START 05-nvmetest.py:NVMeTest.test_create_full_capacity_ns;run-Devices-device1-firmware_url-package-upstream-nvme-cli-b530
avocado.sysinfo DEBUG| Not logging /proc/pci (file not found)
avocado.test DEBUG| PARAMS (key=device, path=*, default=nvme0) => 'nvme11n1'
avocado.utils.process INFO | Running 'ls /dev/nvme11n1'
avocado.utils.process DEBUG| [stderr] ls: cannot access '/dev/nvme11n1': No such file or directory
avocado.utils.process INFO | Command 'ls /dev/nvme11n1' finished with 2 after 0.001491771s
avocado.test ERROR|
avocado.test ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:743
avocado.test ERROR| Traceback (most recent call last):
avocado.test ERROR|   File "/root/tests/tests/avocado-misc-tests/io/disk/ssd/nvmetest.py", line 49, in setUp
avocado.test ERROR|     self.cancel("%s does not exist" % self.device)
avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 925, in cancel
avocado.test ERROR|     raise exceptions.TestCancel(message)
avocado.test ERROR| avocado.core.exceptions.TestCancel: /dev/nvme11n1 does not exist

**《Manual-Test-log》**
[Manual-Test-Log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7783452/Manual-Test-Log.txt)
After the test of nvmetest.py completes, we find that ns of /dev/nvme11n1 is detached, which causes 【Item 5】 and other Test-Items to be canceled. Please check if it is nvmetest.py's script-issue.

**《Configuration》**
[Kernel]
4.18.0-193.28.1.el8_2.ppc64le

[FW Config]
BMC: op940.21.mih-1-0-g62d91d0138
Pnor: IBM-mihawk-ibm-OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Samsung Electronics(M393A2K40BB2-CTD) 16GiB x8
SSD 2.5" 3.84TB SAS MZILT3T8HALS-MS33 *1
MEGARAID 9361-8I SAS3 CONTROLLER *1
PSU ACBEL 2000w *2
Slot4: Bear Lake card
Slot9: Bear Lake card

PM1735 - SSD 800GB NVMe *24

**Comment by Naresh-ibm** [comment]
it is working now with latest code.
please feel free to report a new issue if you still facing it.
