### ISSUE TITLE
After running nvme_cli_selftests.py in Rhel8.4, “run-test-nvme_compare_test-1521” & “run-test-nvme_get_features_test-0994” are FAIL

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2315]
After running nvme_cli_selftests.py in Rhel8.4, “run-test-nvme_compare_test-1521” & “run-test-nvme_get_features_test-0994” are FAIL.

**I. Test nvme_cli_selftests.py with Ver.97 of Avocado**
1. Edit nvme_cli_selftests.yaml:
![image](https://user-images.githubusercontent.com/63998174/170230098-f85f6d8c-f133-4f13-9d3a-0b9dc7bde46e.png)

2. Run nvme_cli_selftests.py via cmd “avocado run nvme_cli_selftests.py -m nvme_cli_selftests.py.data/nvme_cli_selftests.yaml”.
![image](https://user-images.githubusercontent.com/63998174/170230135-dc12e600-6ce4-4a20-9ba6-b9215a1376fa.png)

◎ Job-Log: [nvme_cli_selftests-V97-run-job.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/8769748/nvme_cli_selftests-V97-run-job.zip)

3. Run nvme_cli_selftests.py via cmd “avocado run --test-runner runner nvme_cli_selftests.py -m nvme_cli_selftests.py.data/nvme_cli_selftests.yaml”.
![image](https://user-images.githubusercontent.com/63998174/170230263-9919d127-1a62-47cf-8a61-fc4f3e8d727f.png)

**II. Test nvme_cli_selftests.py with Ver.90 of Avocado**
1. Edit nvme_cli_selftests.yaml:
![image](https://user-images.githubusercontent.com/63998174/170230332-b3f9f46c-67c7-4e05-9e82-e7a03b265ddf.png)

2. Run nvme_cli_selftests.py via cmd “avocado run nvme_cli_selftests.py -m nvme_cli_selftests.py.data/nvme_cli_selftests.yaml”.
![image](https://user-images.githubusercontent.com/63998174/170230369-88a19cad-447f-4252-96d1-d841b3f7f8eb.png)

◎ Job-Log: [nvme_cli_selftests-V90-run-job.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/8769754/nvme_cli_selftests-V90-run-job.zip)

《INIT 2》
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
L0649 INFO | Running 'nose2 --verbose nvme_compare_test'
L0461 DEBUG| [stdout] /sys/devices/pci0000:00/0000:00:00.0/0000:01:00.0/0000:02:00.0/0000:03:00.0/0000:04:0a.0/0000:0f:00.0/nvme/nvme11
L0461 DEBUG| [stderr] nvme_compare_test.TestNVMeCompareCmd.test_nvme_compare
L0461 DEBUG| [stderr] Testcase main ...
L0461 DEBUG| [stderr] Rounding data size to fit block count (4096 bytes)
L0461 DEBUG| [stderr] write: Success
L0461 DEBUG| [stderr] Rounding data size to fit block count (4096 bytes)
L0461 DEBUG| [stderr] NVMe status: COMPARE_FAILED: The command failed due to a miscompare during a Compare command(0x285)
L0461 DEBUG| [stderr] Rounding data size to fit block count (4096 bytes)
L0461 DEBUG| [stderr] compare: Success
L0461 DEBUG| [stderr] ok
L0461 DEBUG| [stderr]
L0461 DEBUG| [stderr] ----------------------------------------------------------------------
L0461 DEBUG| [stderr] Ran 1 test in 0.036s
L0461 DEBUG| [stderr]
L0461 DEBUG| [stderr] OK
L0731 INFO | Command 'nose2 --verbose nvme_compare_test' finished with 0 after 0.8426409509993391s
L0039 ERROR|
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:784
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/io/disk/ssd/nvme_cli_selftests.py", line 84, in test_selftests
L0045 ERROR|     self.fail("Test Failed")
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 969, in fail
L0045 ERROR|     raise exceptions.TestFail(message)
L0045 ERROR| avocado.core.exceptions.TestFail: Test Failed
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

《INIT 12》
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
L0649 INFO | Running 'nose2 --verbose nvme_get_features_test'
L0461 DEBUG| [stdout] /sys/devices/pci0000:00/0000:00:00.0/0000:01:00.0/0000:02:00.0/0000:03:00.0/0000:04:0a.0/0000:0f:00.0/nvme/nvme11
L0461 DEBUG| [stderr] nvme_get_features_test.TestNVMeGetMandatoryFeatures.test_get_mandatory_features
L0461 DEBUG| [stderr] Testcase main ...
L0461 DEBUG| [stderr] NVMe status: INVALID_NS: The namespace or the format of that namespace is invalid(0xb)
L0461 DEBUG| [stderr] FAIL
L0461 DEBUG| [stderr]
L0461 DEBUG| [stderr] ======================================================================
L0461 DEBUG| [stderr] FAIL: nvme_get_features_test.TestNVMeGetMandatoryFeatures.test_get_mandatory_features
L0461 DEBUG| [stderr] Testcase main
L0461 DEBUG| [stderr] ----------------------------------------------------------------------
L0461 DEBUG| [stderr] Traceback (most recent call last):
L0461 DEBUG| [stderr]   File "/var/tmp/avocado_nsmqwldj/nvme-cli-master/tests/nvme_get_features_test.py", line 109, in test_get_mandatory_features
L0461 DEBUG| [stderr]     self.get_mandatory_features(feature_id)
L0461 DEBUG| [stderr]   File "/var/tmp/avocado_nsmqwldj/nvme-cli-master/tests/nvme_get_features_test.py", line 104, in get_mandatory_features
L0461 DEBUG| [stderr]     assert_equal(proc.wait(), 0)
L0461 DEBUG| [stderr] AssertionError: 22 != 0
L0461 DEBUG| [stderr]
L0461 DEBUG| [stderr] ----------------------------------------------------------------------
L0461 DEBUG| [stderr] Ran 1 test in 0.015s
L0461 DEBUG| [stderr]
L0461 DEBUG| [stderr] FAILED (failures=1)
L0461 DEBUG| [stdout] get-feature:0x01 (Arbitration), Current value:0x00000003
L0461 DEBUG| [stdout]   High Priority Weight   (HPW): 1
L0461 DEBUG| [stdout]   Medium Priority Weight (MPW): 1
L0461 DEBUG| [stdout]   Low Priority Weight    (LPW): 1
L0461 DEBUG| [stdout]   Arbitration Burst       (AB): 8
L0461 DEBUG| [stdout]
L0461 DEBUG| [stdout] get-feature:0x02 (Power Management), Current value:00000000
L0461 DEBUG| [stdout]   Workload Hint (WH): 0 - No Workload
L0461 DEBUG| [stdout]   Power State   (PS): 0
L0461 DEBUG| [stdout]
L0461 DEBUG| [stdout] get-feature:0x04 (Temperature Threshold), Current value:0x00000159
L0461 DEBUG| [stdout]   Threshold Type Select         (THSEL): 0 - Over Temperature Threshold
L0461 DEBUG| [stdout]   Threshold Temperature Select (TMPSEL): 0 - Composite Temperature
L0461 DEBUG| [stdout]   Temperature Threshold         (TMPTH): 72 C (345 Kelvin)
L0461 DEBUG| [stdout]
L0461 DEBUG| [stdout]
L0731 INFO | Command 'nose2 --verbose nvme_get_features_test' finished with 1 after 0.9891525170096429s
L0039 ERROR|
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:784
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/io/disk/ssd/nvme_cli_selftests.py", line 84, in test_selftests
L0045 ERROR|     self.fail("Test Failed")
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 969, in fail
L0045 ERROR|     raise exceptions.TestFail(message)
L0045 ERROR| avocado.core.exceptions.TestFail: Test Failed
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

3. However, when we test “run-test-nvme_compare_test-1521” & “run-test-nvme_get_features_test-0994” via below methods by manual, the results are PASS.

《run-test-nvme_compare_test-1521》
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
[root@localhost ~]# echo "Today is sunny !" > write_file.txt
[root@localhost ~]# nvme write /dev/nvme11n1 --start-block=1023 --block-count=0 --data-size=512 --data=write_file.txt
Rounding data size to fit block count (4096 bytes)
write: Success
[root@localhost ~]# nvme read /dev/nvme11n1 --start-block=1023 --block-count=0 --data-size=512 --data=read_file.txt
Rounding data size to fit block count (4096 bytes)
read: Success
[root@localhost ~]# cat read_file.txt
Today is sunny !
[root@localhost ~]# echo "Today is rainy !" > compare_file.txt
[root@localhost ~]# nvme compare /dev/nvme11n1 --start-block=1023 --block-count=0 --data-size=512 --data=compare_file.txt
Rounding data size to fit block count (4096 bytes)
NVMe status: COMPARE_FAILED: The command failed due to a miscompare during a Compare command(0x285)
[root@localhost ~]# echo "Today is sunny !" > compare_file.txt
[root@localhost ~]# nvme compare /dev/nvme11n1 --start-block=1023 --block-count=0 --data-size=512 --data=compare_file.txt
Rounding data size to fit block count (4096 bytes)
compare: Success
[root@localhost ~]#
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

《run-test-nvme_get_features_test-0994》
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
[root@localhost ~]# nvme get-feature /dev/nvme11 -f 0
feature-id required param
[root@localhost ~]# nvme get-feature /dev/nvme11 -f 1
get-feature:0x01 (Arbitration), Current value:0x00000003
[root@localhost ~]# nvme get-feature /dev/nvme11 -f 3
NVMe status: INVALID_NS: The namespace or the format of that namespace is invalid(0xb)
[root@localhost ~]# nvme get-feature /dev/nvme11 -f 4
get-feature:0x04 (Temperature Threshold), Current value:0x00000159
[root@localhost ~]# nvme get-feature /dev/nvme11 -f 5
NVMe status: INVALID_NS: The namespace or the format of that namespace is invalid(0xb)
[root@localhost ~]# nvme get-feature /dev/nvme11 -f 6
NVMe status: INVALID_FIELD: A reserved coded value or an unsupported value in a defined field(0x2)
[root@localhost ~]# nvme get-feature /dev/nvme11 -f 7
get-feature:0x07 (Number of Queues), Current value:0x007f007f
[root@localhost ~]# nvme get-feature /dev/nvme11 -f 8
get-feature:0x08 (Interrupt Coalescing), Current value:00000000
[root@localhost ~]# nvme get-feature /dev/nvme11 -f 9
get-feature:0x09 (Interrupt Vector Configuration), Current value:0x00010000
[root@localhost ~]# nvme get-feature /dev/nvme11 -f 10
get-feature:0x0a (Write Atomicity Normal), Current value:00000000
[root@localhost ~]#
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

**III. Configuration**
[Kernel]
4.18.0-305.el8.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e 
Pnor: IBM-mihawk-ibm-OP9_v2.4.1-4.31-prod

[HW Config]
CPU : LaGrange dd2.3 02CY582 (20c, 225W, 2.9GHz) *2
DIMM : Samsung Electronics(M393A2K40BB2-CTD) 16GiB *8 
PSU : AcBel 2000W *2 
M.2 : SAMSUNG MZ1LB960HAJQ-00007*1
JBOF : Samsung Electronics Co Ltd Device a825 *24

**Comment by Naresh-ibm** [comment]
this is working fine now. please check and if still seen, please report a new one.


localhost:~/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/ssd # avocado run --max-parallel-tasks=1 nvme_cli_selftests.py -m nvme_cli_selftests.py.data/nvme_cli_selftests.yaml
Fetching asset from nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests
JOB ID     : 1f533ef77d7822a23502b94aaf10f391aacaffc8
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-01-26T02.56-1f533ef/job.log
 (01/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_id_ctrl_test-0987: STARTED
 (01/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_id_ctrl_test-0987: PASS (0.42 s)
 (02/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_compare_test-75b9: STARTED
 (02/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_compare_test-75b9: PASS (0.46 s)
 (03/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_error_log_test-b314: STARTED
 (03/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_error_log_test-b314: PASS (0.25 s)
 (04/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_test_logger-7d0e: STARTED
 (04/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_test_logger-7d0e: PASS (0.25 s)
 (05/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_read_write_test-3f40: STARTED
 (05/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_read_write_test-3f40: PASS (0.26 s)
 (06/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_simple_template_test-8e45: STARTED
 (06/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_simple_template_test-8e45: PASS (0.26 s)
 (07/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_id_ns_test-0c80: STARTED
 (07/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_id_ns_test-0c80: PASS (0.26 s)
 (08/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_fw_log_test-73f8: STARTED
 (08/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_fw_log_test-73f8: PASS (0.26 s)
 (09/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_flush_test-e623: STARTED
 (09/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_flush_test-e623: PASS (0.26 s)
 (10/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_test_io-67e5: STARTED
 (10/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_test_io-67e5: PASS (0.27 s)
 (11/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_get_features_test-c924: STARTED
 (11/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_get_features_test-c924: PASS (0.28 s)
 (12/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_writezeros_test-3115: STARTED
 (12/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_writezeros_test-3115: PASS (0.25 s)
 (13/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_smart_log_test-8919: STARTED
 (13/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_smart_log_test-8919: PASS (0.27 s)
 (14/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_test-efcd: STARTED
 (14/14) nvme_cli_selftests.py:NVMeCliSelfTest.test_selftests;run-test-nvme_test-efcd: PASS (0.26 s)
RESULTS    : PASS 14 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-01-26T02.56-1f533ef/results.html
JOB TIME   : 29.33 s
localhost:~/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/ssd #
