### ISSUE TITLE
After running nvmetest.py in Rhel8.4, it shows “No such file or directory: './NVME-VERSION-GEN'”

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2316]
After running nvmetest.py in Rhel8.4, it shows “No such file or directory: './NVME-VERSION-GEN'”.

**I. Test nvmetest.py with Ver.97 of Avocado**
1. Edit nvmetest.yaml:
![image](https://user-images.githubusercontent.com/63998174/170234298-1a6c5fbc-84f6-43cd-885e-268e5f91adb7.png)

2. Run nvmetest.py via cmd “avocado run nvmetest.py -m nvmetest.py.data/nvmetest.yaml”.
![image](https://user-images.githubusercontent.com/63998174/170234339-9c06b6ce-6ed4-414f-bddd-d3276937f0a1.png)

◎ Job-Log: [nvmetest-V97-run-job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/8769920/nvmetest-V97-run-job.log)

3. Run nvmetest.py via cmd “avocado run --test-runner runner nvmetest.py -m nvmetest.py.data/nvmetest.yaml”.
![image](https://user-images.githubusercontent.com/63998174/170234459-a15b154e-e1fb-457b-940a-ab02bca0a1df.png)

**II. Test nvmetest.py with Ver.90 of Avocado**
1. Edit nvmetest.yaml:
![image](https://user-images.githubusercontent.com/63998174/170234487-4b398e7c-376b-4c58-9971-4e44c4def06e.png)

2. Run nvmetest.py via cmd “avocado run nvmetest.py -m nvmetest.py.data/nvmetest.yaml”.
![image](https://user-images.githubusercontent.com/63998174/170234546-4f13bfad-2d07-41a6-b0d6-2cfeaf91da76.png)

◎ Job-Log: [nvmetest-V90-run-job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/8769915/nvmetest-V90-run-job.log)

《INIT 1》
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
15:25:01 INFO | Command 'ls /dev/nvme1' finished with 0 after 0.0012496900017140433s
15:25:01 DEBUG| PARAMS (key=package, path=*, default=distro) => 'upstream'
15:25:01 INFO | Asset not in cache, fetching it.
15:25:01 INFO | Asset not in cache after lock, fetching it.
15:25:01 INFO | Fetching https://github.com/linux-nvme/nvme-cli/archive/master.zip -> /root/avocado/data/cache/by_location/ff77361cc9c09449e6006df877beb5b1a131a103/nvme-cli.zip.88cc3dd3-5ee3-4c44-9a48-41a9c45fde1f
15:25:07 DEBUG| Retrieved URL "https://github.com/linux-nvme/nvme-cli/archive/master.zip": content-length UNKNOWN, date: "Wed, 25 May 2022 07:25:07 GMT", last-modified: "UNKNOWN"
15:25:09 WARNI| No hash provided. Cannot check the asset file integrity.
15:25:09 INFO | Running './NVME-VERSION-GEN'
15:25:09 ERROR| 
15:25:09 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:769
15:25:09 ERROR| Traceback (most recent call last):
15:25:09 ERROR|   File "/root/tests/tests/avocado-misc-tests/io/disk/ssd/nvmetest.py", line 59, in setUp
15:25:09 ERROR|     process.system("./NVME-VERSION-GEN", ignore_status=True)
15:25:09 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1145, in system
15:25:09 ERROR|     encoding=encoding)
15:25:09 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1079, in run
15:25:09 ERROR|     cmd_result = sp.run(timeout=timeout)
15:25:09 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 952, in run
15:25:09 ERROR|     self._init_subprocess()
15:25:09 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 666, in _init_subprocess
15:25:09 ERROR|     raise details
15:25:09 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 663, in _init_subprocess
15:25:09 ERROR|     env=self.env)
15:25:09 ERROR|   File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
15:25:09 ERROR|     restore_signals, start_new_session)
15:25:09 ERROR|   File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
15:25:09 ERROR|     raise child_exception_type(errno_num, err_msg, err_filename)
15:25:09 ERROR| FileNotFoundError: [Errno 2] No such file or directory: './NVME-VERSION-GEN' (./NVME-VERSION-GEN): './NVME-VERSION-GEN'↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

3. However, we can manually download “master.zip” via cmd:

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
[root@localhost ~]# wget https://github.com/linux-nvme/nvme-cli/archive/master.zip
--2022-05-25 17:43:01--  https://github.com/linux-nvme/nvme-cli/archive/master.zip
Resolving github.com (github.com)... 52.192.72.89
Connecting to github.com (github.com)|52.192.72.89|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/linux-nvme/nvme-cli/zip/refs/heads/master [following]
--2022-05-25 17:43:06--  https://codeload.github.com/linux-nvme/nvme-cli/zip/refs/heads/master
Resolving codeload.github.com (codeload.github.com)... 52.193.111.178
Connecting to codeload.github.com (codeload.github.com)|52.193.111.178|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘master.zip’

master.zip                                                                  [          <=>                                                                                                                                                                   ]   1.71M   768KB/s    in 2.3s

2022-05-25 17:43:09 (768 KB/s) - ‘master.zip’ saved [1792253]

[root@localhost ~]#
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

**III. Configuration**
[Kernel]
4.18.0-305.el8.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e 
Pnor: IBM-mihawk-ibm-OP9_v2.4.1-4.31-prod

[HW Config]
CPU : LaGrange dd2.3 02CY582 (20c, 225W, 2.9GHz) *2
DIMM : Samsung Electronics(M393A2K40BB2-CTD) 16GiB *8 
PSU : AcBel 2000W *2 
M.2 : SAMSUNG MZ1LB960HAJQ-00007*1
JBOF : Samsung Electronics Co Ltd Device a825 *24

**Comment by abdhaleegit** [comment]
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/2711  fixes thi issue
