### ISSUE TITLE
Script avago9361_vd.py not skipping the ir-relavent test cases as desired.

### ISSUE THREAD

**Issue by vrbagalkote** [avocado-framework-tests/avocado-misc-tests#241]
There is a problem with the checking of self.name with the test case name, So script is not skipping the test cases/iteration which are not applicable. I have fixed that and will submit a patch.

**Comment by vrbagalkote** [comment]
Raised a PR, 
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/242

**Comment by PraveenPenguin** [comment]
closing as @242 accepted
