### ISSUE TITLE
pread fail case in random test code while running in multiple threads

### ISSUE THREAD

**Issue by kalpanashtty** [avocado-framework-tests/avocado-misc-tests#2446]
@PraveenPenguin and @narasimhan-v 
This is regarding the pread system call error case in random.c test code which is called in mm_subsystem.py.
Harish hosts random test code in his GitLab project - https://gitlab.com/harish-24/linux-mm.

I did send PR for review and merge but till now no response. I assume he is no longer working on or maintaining the GitLab project.  So do you think you can maintain a copy of this project and the community can fix issues whenever we run into problems?

My merge or PR request -> mhttps://gitlab.com/harish-24/linux-mm/-/merge_requests/2

**Comment by kalpanashtty** [comment]
@PraveenPenguin  @narasimhan-v   Any thoughts on maintaining a forked copy of  "https://gitlab.com/harish-24/linux-mm/"?
We need the proposed fix posted at: https://gitlab.com/harish-24/linux-mm/-/merge_requests/2; else we see "mm_subsystem.py" constantly failing. Please comment.

**Comment by kalpanashtty** [comment]
@PraveenPenguin  @narasimhan-v  Can you folks get back on this, please? If one of you host linux-mm gitlab then I can push my changes - https://gitlab.com/harish-24/linux-mm/-/merge_requests/2;

**Comment by narasimhan-v** [comment]
Please give me a couple of days, will host as my repository

**Comment by kalpanashtty** [comment]
> Please give me a couple of days, will host as my repository

Thanks @narasimhan-v

**Comment by narasimhan-v** [comment]
@kalpanashtty https://github.com/narasimhan-v/linux-mm

**Comment by kalpanashtty** [comment]
We have new git repo and also changed the avocado-misc-tests to point to the new link; hence closing this issue.
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/2532

**Comment by kalpanashtty** [comment]
Completed.
