### ISSUE TITLE
Stress-ng Failing

### ISSUE THREAD

**Issue by AYUSHJAIN951** [avocado-framework-tests/avocado-misc-tests#2557]
While running Stress-ng on a system test fails with below errors
```
Fetching asset from stress-ng.py:Stressng.test
JOB ID     : 97f57fcbde2710d59d22f55f38fd426a12cac0de
JOB LOG    : /root/avocado/job-results/job-2023-02-20T07.04-97f57fc/job.log
 (1/3) stress-ng.py:Stressng.test;run-exclude-fs_type-ext4-stressors-workers-f640: STARTED
 (1/3) stress-ng.py:Stressng.test;run-exclude-fs_type-ext4-stressors-workers-f640:  ERROR: Command 'losetup -d /dev/loop0' failed.\nstdout: b''\nstderr: b'losetup: /dev/loop0: detach failed: No such device or address\n'\nadditional_info: None (52.67 s)
 (2/3) stress-ng.py:Stressng.test;run-exclude-fs_type-xfs-stressors-workers-411a: STARTED
 (2/3) stress-ng.py:Stressng.test;run-exclude-fs_type-xfs-stressors-workers-411a:  ERROR: Command 'umount /dev/loop0' failed.\nstdout: b''\nstderr: b'umount: /dev/loop0: not mounted.\n'\nadditional_info: None (16.62 s)
 (3/3) stress-ng.py:Stressng.test;run-exclude-fs_type-btrfs-stressors-workers-ccec: STARTED
 (3/3) stress-ng.py:Stressng.test;run-exclude-fs_type-btrfs-stressors-workers-ccec:  ERROR: Command 'umount /dev/loop0' failed.\nstdout: b''\nstderr: b'umount: /dev/loop0: not mounted.\n'\nadditional_info: None (16.79 s)
RESULTS    : PASS 0 | ERROR 3 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 89.77 s

Test summary:
stress-ng.py:Stressng.test;run-exclude-fs_type-btrfs-stressors-workers-ccec: ERROR
stress-ng.py:Stressng.test;run-exclude-fs_type-ext4-stressors-workers-f640: ERROR
stress-ng.py:Stressng.test;run-exclude-fs_type-xfs-stressors-workers-411a: ERROR
```

@disgoel  @PraveenPenguin  @Naresh-ibm

So there are couple of issues with this test currently

1. Why in the test "self.loop_dev" is hard coded as "/dev/loop0" [@line119](https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/generic/stress-ng.py#:~:text=self.loop_dev%20%3D%20%22/dev/loop0%22) ?

2. I ran this test on my machine with a block device but that throws an error as referred above.

3. As @Naresh-ibm [quoted](https://github.com/avocado-framework-tests/avocado-misc-tests/pull/2535#discussion_r1086316258) in 

> I think this may not be the right think to give /mnt as default dir. every one doesn't uses the /mnt for their test and some time it may get messup with OS disk space like for fiotest for creating the temp files on test runs.
So I advise to keep it as "None" only. 

[In line](https://github.com/avocado-framework-tests/avocado-misc-tests/pull/2521/files#:~:text=%27dir%27%2C-,default%3D%27/mnt%27,-)  '/mnt' is being used as i used in [PR 2535](https://github.com/avocado-framework-tests/avocado-misc-tests/pull/2535) . 

Why this PR [2521](https://github.com/avocado-framework-tests/avocado-misc-tests/pull/2521) is tested on Avocado 94.0(Older version) but not on the latest upstream version at the time of PR Request/Merge.

**Comment by disgoel** [comment]
@AYUSHJAIN951 I have already sent a PR to fix the error in teardown.
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/2543

**Comment by AYUSHJAIN951** [comment]
> @AYUSHJAIN951 I have already sent a PR to fix the error in teardown. #2543

Thanks for pointing me to that.
Can you please help me with other issues as well.

**Comment by PraveenPenguin** [comment]
@AYUSHJAIN951 can you please check this issue against latest code base

**Comment by PraveenPenguin** [comment]
ping @AYUSHJAIN951

**Comment by AYUSHJAIN951** [comment]
LGTM, its working with the latest code
