### ISSUE TITLE
disktest is failing if the disk size is in TB

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#291]
The testscript is hardcoded as 100 GB as the default disk size. test works for all disks <= 100GB

        if gigabytes is None:
            free = 100  # cap it at 100GB by default
            for disk in self.disks:
                free = min(utils_disk.freespace(disk) / 1073741824, free)
            gigabytes = free

the above calculation fails if the disk is larger size like 1TB it fails with this error
 "Free disk space is lower than chunk size  (10240, 261409)"

**Comment by PraveenPenguin** [comment]
@abdhaleegit can you please elaborate more about this issue ?

**Comment by abdhaleegit** [comment]
I have a system with these configuration:
Memory : 255G  Free : 243G
disk : 5.2T Free :  4.4T

calculate for above configuration:
      
memory_mb = 267683072 / 1024 = 261409
self.chunk_mb = 261409

free = 100   >>>>>>>>>>>>>>> the code says free as 100 byte, and in comment it says 100G = 1 e+11 = 107374182400 bytes
free = min((4.398046511×10¹²÷1073741824, 100)
free = min(40960, 100)
free =  100

self.no_chunks = 1024 * 100 /  261409
self.no_chunks = 0

if  self.no_chunks == 0:
    Free disk space is lower than chunk size (102400 , 261409) 

so it fails

------------------------------------------------------------------------

if free = 107374182400 bytes

free = min((4.398046511×10¹²÷1073741824, 107374182400)
free = min(40960, 107374182400 bytes)
free =  40960

self.no_chunks = 1024 * 40960 /  261409
self.no_chunks = 160

so test case continues:

So the fix is 
- free = 100
+ free = 107374182400

Its a coding issue :-1  
I have tested this on both 100gb and 5 TB system.. it works

I will send a patch

Thanks

**Comment by PraveenPenguin** [comment]
fixed in #317
