### ISSUE TITLE
cpu/ppc64_cpu_test.py : test case fails on Power6  and Power7  machine

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#309]
Older hardware do not support options above SMT= 4

Power6/Power7
[root@ltcp6 ~]# ppc64_cpu --smt=5
SMT=5 is not valid
[root@ltcp6 ~]# echo $?
255

Power8
root@tuleta4u-lp2:~# ppc64_cpu --smt=5
root@tuleta4u-lp2:~# echo $?
0

a check for hardware could be added before the command.

Thanks

**Comment by narasimhan-v** [comment]
@abdhaleegit Agreed, and I believe the newer hardware also needs changes with this.
Would this check be enough ?
```
# cat /proc/cpuinfo | grep cpu        
cpu		: POWER8
```

**Comment by abdhaleegit** [comment]
don't we have a module to get the platfrom or cpu type in avocado ?
or  platform.processor()  ?

[root@p7-korg-ci1 quotactl]# cat /proc/cpuinfo | grep cpu
cpu		: POWER7 (architected), altivec supported

[root@ltcp6 ~]# cat /proc/cpuinfo | grep cpu
cpu		: POWER6 (architected), altivec supported

**Comment by PraveenPenguin** [comment]
@abdhaleegit @narasimhan-v  i think  `avocado.utils.cpu.get_cpu_arch()` we can get the processor info

**Comment by narasimhan-v** [comment]
@PraveenPenguin Sure, then we can directly use this utility for the test

**Comment by narasimhan-v** [comment]
#321

**Comment by PraveenPenguin** [comment]
closing in favour of #321
