### ISSUE TITLE
Using the utilities and tests in avocado-vt/virttest

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework-tests/avocado-misc-tests#31]
I see some tests and utilities in avocado-vt/virttest.
If I want to use them and write tests in avocado-misc-tests, what is the recommended way ?

Can I reference them directly ?

Thanks
Narasimhan V

**Comment by narasimhan-v** [comment]
@apahim @ldoktor Your views would be helpful

**Comment by ldoktor** [comment]
Hello @narasimhan-v, this is quite generic question. As for the utils it'd be best to move/port them from `avocado-vt` to `avocado`. The tests are not that simple as `avocado-vt` tests are a bit special. Can you please elaborate more on how would you like to reuse them? I'd recommend sending a PR with actual code and mention us there so we don't talk abstract.

**Comment by narasimhan-v** [comment]
@ldoktor I can point an example, but would be applicable to many utils there.

Lets take `avocado-vt/virttest/nfs.py`
In case I want to use it and write a nfs related test in `avocado-misc-tests`, I need to clone `avocado-vt` and use them.
Is this the recommended way ?

**Comment by ldoktor** [comment]
Well the `nfs` is tied to avocado-vt `params`. So let me mention some of the possible solutions sorted by correctness:

1. Create a new `avocado.utils.nfs` utility based on the `virttest.nfs` one but turn all the `virttest` special handling into generic API. Then use the `avocado.utils.nfs` inside `virttest.nfs` to keep the old API there.

2. Inspire by `virttest.nfs` and create a new `avocado.utils.nfs` with a limited set of functions needed by your tests. Again, ideally use this API from withing the `virttest.nfs`.

3. Import `from virttest import nfs` in `try/except ImportError` and raise exception saying `avocado-vt` is required (possibly even with a link as `avocado-vt` is not available via `pip`. The reason why I mention this as a last method is that the `virttest.nfs` is strongly tied to `avocado-vt` the calls are specific (using `params`), it uses utils, logging and style from `avocado-vt` and it's not available via pip. If it was any other util I'd simply say it's a dependency, but in this example it really is a big ugly thing (something like using photoshop to write a text label)

Anyway @apahim, @clebergnu might have different opinion on this...

**Comment by narasimhan-v** [comment]
@apahim @clebergnu Any thoughts on this please ?

**Comment by clebergnu** [comment]
@narasimhan-v defintely the *right* way to go would be do identify your test needs, and propose a port of the Avocado-VT tests/utilities to generic Avocado utility libraries.

Maybe you can choose one to start with, and we should be able to assist (if needed) to get that turned into a generic Avocado utility library.

**Comment by adereis** [comment]
Another valid option is to simply copy avocado-vt/utils/nfs.py and adapt it to what you need in avocado-misc-tests (make sure you keep the credits and license).

The right way is not always the most practical or feasible way.

**Comment by narasimhan-v** [comment]
@clebergnu @adereis Thanks, working on it.

**Comment by ldoktor** [comment]
OK, let's close it, but feel free to re-open it to get additional feedback, if necessary.

**Comment by narasimhan-v** [comment]
@ldoktor @clebergnu @adereis I have ported the nfs utilities into avocado, as needed for the tests here.
Please have a look into it.
https://github.com/avocado-framework/avocado/pull/1705
