### ISSUE TITLE
io/disk/ltp_fs.py : the test fails if the machine do not have extra disk

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#316]
test case mandates to supply a disk, and it fails if we do not have extra disk in machine.

if disk is not given, than try to continue test on default dir. as long as test do not fill the root file system its fine, else we have to limit the test run to use minimum disk space available on disk

Thanks

**Comment by Naresh-ibm** [comment]
@abdhaleegit  working on it, will send the PR soon.

**Comment by PraveenPenguin** [comment]
@abdhaleegit have this fulfilled your requirement  can you please check

https://github.com/avocado-framework-tests/avocado-misc-tests/commit/5ff85c911dcd283b611040d90450ff179d45376f

**Comment by PraveenPenguin** [comment]
@abdhaleegit can you please confirm ?
