### ISSUE TITLE
fs/filebench.py : Test takes hour's to complete if the root disk size is huge

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#326]
should we limit the test to run for given time or file size ?

**Comment by PraveenPenguin** [comment]
@abdhaleegit sure will check

**Comment by PraveenPenguin** [comment]
@abdhaleegit can you please check as recent changes fix the issue ?

**Comment by PraveenPenguin** [comment]
closing this issue as it seems me fix @abdhaleegit if you are still facing issue please feel free to reopen this issue
