### ISSUE TITLE
git_repo() in avocado/utils/git.py has cloning issue.

### ISSUE THREAD

**Issue by Naresh-ibm** [avocado-framework-tests/avocado-misc-tests#378]
git_repo() in avocado/utils/git.py is cloning  the files directly of upstream dir instead it has to clone the dir which contains the files

**Comment by narasimhan-v** [comment]
@Naresh-ibm logs please

**Comment by PraveenPenguin** [comment]
@Naresh-ibm any update here ?

**Comment by narasimhan-v** [comment]
@PraveenPenguin Think this is not a valid one. Anyways, let us wait a couple of days for @Naresh-ibm before closing this one.

**Comment by PraveenPenguin** [comment]
@narasimhan-v thanks , closing this issue i think @Naresh-ibm is not more facing this issue , @Naresh-ibm if you face again issue please raise a issue
