### ISSUE TITLE
Unable to install avocado on SLES11_SP4

### ISSUE THREAD

**Issue by poojabs7** [avocado-framework-tests/avocado-misc-tests#395]
It crashes like below.

alp3:~ # avocado --help
Avocado crashed unexpectedly: 'module' object has no attribute 'NullHandler'
You can find details in /tmp/avocado-traceback-2017-04-05_02:32:43-i8q2Rb.log
[Avocado_log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/895428/Avocado_log.txt)

Followed below steps:
Installed git gcc python-devel python-pip libvirt-devel libyaml-devel xz-devel packages.

git clone git://github.com/avocado-framework/avocado.git
cd avocado
sudo make requirements
sudo python setup.py install

**Comment by PraveenPenguin** [comment]
@poojabs7 seems me python 2.6 issue

**Comment by narasimhan-v** [comment]
@poojabs7 What is the version of setuptools installed in your system ?

**Comment by narasimhan-v** [comment]
`pip install setuptools==30.1.0`
See if this solves your issue

**Comment by PraveenPenguin** [comment]
@poojabs7 any update here

**Comment by PraveenPenguin** [comment]
closing this issue as it pending from long @poojabs7 if you still want to pursue this feel free to reopen this
