### ISSUE TITLE
Replace self.skip() by self.cancel() or by skip decorators

### ISSUE THREAD

**Issue by apahim** [avocado-framework-tests/avocado-misc-tests#449]
`self.skip()` will be deprecated by the end of this year. Let's adjust the tests in this repo so we don't face any issues in the future.

**Comment by PraveenPenguin** [comment]
@apahim thanks for pointing this , will rectify this

**Comment by narasimhan-v** [comment]
Can we start this activity once the next LTS is released (guess it is version 52) ?
The current LTS (version 36) does not support `self.cancel()`.

**Comment by PraveenPenguin** [comment]
closing in favour #556
