### ISSUE TITLE
cpu/cpupower : test fails some times 

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#496]
[stdout] Setting cpu: 68
[stdout] Setting cpu: 69
[stdout] Setting cpu: 70
[stdout] Setting cpu: 71
[stdout] Setting cpu: 72
[stdout] Setting cpu: 73
[stdout] Setting cpu: 74
[stdout] Setting cpu: 75
[stdout] Setting cpu: 76
[stdout] Setting cpu: 77
[stdout] Setting cpu: 78
[stdout] Setting cpu: 79
Running 'cpupower -c 0 frequency-info -f'
[stdout] analyzing CPU 0:
Command 'cpupower -c 0 frequency-info -f' finished with 0 after 0.00141215324402s
[stdout]   current CPU frequency: 2593000 (asserted by call to kernel)
[stdout] 
The userspace governor is working as expected
++++++++++++++++

++++++++++++++++
Running 'cpupower frequency-set -f '
[stderr] frequency-set: option requires an argument -- 'f'
[stdout] invalid or unknown argument
Command 'cpupower frequency-set -f ' finished with 234 after 0.00138282775879s

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-49.0-py2.7.egg/avocado/core/test.py:596
Traceback (most recent call last):
  File "/root/avocado-misc-tests/cpu/cpupower.py", line 59, in test
    self.check_governor(governor, min, max, cur)
  File "/root/avocado-misc-tests/cpu/cpupower.py", line 103, in check_governor
    self.check_userspace_governor(governor)
  File "/root/avocado-misc-tests/cpu/cpupower.py", line 184, in check_userspace_governor
    self.set_freq_val(self.get_random_freq())
  File "/root/avocado-misc-tests/cpu/cpupower.py", line 143, in set_freq_val
    output = process.run(cmd)
  File "/usr/lib/python2.7/site-packages/avocado_framework-49.0-py2.7.egg/avocado/utils/process.py", line 1117, in run
    raise CmdError(cmd, sp.result)
CmdError: Command 'cpupower frequency-set -f ' failed (rc=234)

Local variables:
 -> cur <type 'str'>: 2394000
 -> min <type 'str'>: 2061000
 -> governors <type 'list'>: ['conservative', 'userspace', 'powersave', 'ondemand', 'performance']
 -> max <type 'str'>: 3690000
 -> self <class 'cpupower.cpupower'>: 1-cpu/cpupower.py:cpupower.test
 -> governor <type 'str'>: userspace
 -> initial_governor <type 'str'>: userspace
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/avocado_framework-49.0-py2.7.egg/avocado/core/test.py", line 667, in _run_avocado
    raise test_exception

CmdError: Command 'cpupower frequency-set -f ' failed (rc=234)

ERROR 1-cpu/cpupower.py:cpupower.test -> CmdError: Command 'cpupower frequency-set -f ' failed (rc=234)

**Comment by vrbagalkote** [comment]
I just had a glance over the script and I guess the problem could be on which distro you are running this script. As, I see in SLES there is no file "scaling_available_governors" in the location /sys/devices/system/cpu/cpu%s/cpufreq/scaling_available_governors, as this is the location from where script is getting the value to be set, and where as in Red-Hat we have this file. As shown below.

SuSE O/P:

# uname -a
Linux linux-g616 4.4.67-1.gfa092cc-default #1 SMP Tue May 9 18:28:16 UTC 2017 (fa092cc) ppc64le ppc64le ppc64le GNU/Linux
# cat /etc/issue

Welcome to SUSE Linux Enterprise Server 12 SP3 Beta1 (ppc64le) - Kernel \r (\l).


# cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
cat: /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors: No such file or directory


Red-Hat O/P:

# cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
conservative userspace powersave ondemand performance 

# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Comment by vrbagalkote** [comment]
Ohh, I am wrong, if that location is not present, test will skip anyway, I missed the first line of the script:)

**Comment by narasimhan-v** [comment]
@abdhaleegit Hope #499 fixes the issue. Please verify

**Comment by abdhaleegit** [comment]
ran the test for 100 iterartion.. I did not see the issue.. thanks for the fix

**Comment by PraveenPenguin** [comment]
@vrbagalkote @narasimhan-v thanks , closing this issue as fix was in
