### ISSUE TITLE
softwareraid with three disk mentioned in the yaml does PASS RAID 5 test

### ISSUE THREAD

**Issue by naveedus** [avocado-framework-tests/avocado-misc-tests#502]
Softwareraid with three block device mentioned in the yaml file does pass RAID 5 scenario with fail-over test . 

=====console log=====
linux-0a5l:~/avocado-misc-tests/io/disk # avocado run softwareraid.py -m softwareraid.py.data/softwareraid.yaml 
JOB ID     : d84adcedbc346c4f86965e06a8159e796c931da1
JOB LOG    : /root/avocado/job-results/job-2017-05-18T05.23-d84adce/job.log
 (1/6) softwareraid.py:SoftwareRaid.test_run;raidlinear-scenario-4a19: PASS (0.38 s)
 (2/6) softwareraid.py:SoftwareRaid.test_run;raid0-scenario-716d: PASS (0.41 s)
 (3/6) softwareraid.py:SoftwareRaid.test_run;raid1-scenario-a5ca: PASS (3545.16 s)
 (4/6) softwareraid.py:SoftwareRaid.test_run;raid5-scenario-f871: PASS (1896.36 s)
 (5/6) softwareraid.py:SoftwareRaid.test_run;raid10-scenario-3425: PASS (1927.12 s)
 (6/6) softwareraid.py:SoftwareRaid.test_run;raid6-scenario-110f: FAIL (0.10 s)
RESULTS    : PASS 5 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
TESTS TIME : 7369.54 s
You have new mail in /var/mail/root
linux-0a5l:~/avocado-misc-tests/io/disk # lsblk
NAME                                                     MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda                                                        8:0    0    35G  0 disk  
├─sda1                                                     8:1    0     7M  0 part  
├─sda2                                                     8:2    0     2G  0 part  
├─sda3                                                     8:3    0  13.8G  0 part  
├─sda4                                                     8:4    0  19.2G  0 part  
└─SAIX_VDASD_00fa20e000004c00000001545398a86b.13         254:0    0    35G  0 mpath 
  ├─SAIX_VDASD_00fa20e000004c00000001545398a86b.13-part1 254:1    0     7M  0 part  
  ├─SAIX_VDASD_00fa20e000004c00000001545398a86b.13-part2 254:2    0     2G  0 part  [SWAP]
  ├─SAIX_VDASD_00fa20e000004c00000001545398a86b.13-part3 254:3    0  13.8G  0 part  /opt
  └─SAIX_VDASD_00fa20e000004c00000001545398a86b.13-part4 254:4    0  19.2G  0 part  /home
sdb                                                        8:16   0 361.3G  0 disk  
├─sdb1                                                     8:17   0 361.3G  0 part  
└─1IBM_IPR-0_59D6110000003AD0                            254:5    0 361.3G  0 mpath 
  └─1IBM_IPR-0_59D6110000003AD0-part1                    254:7    0 361.3G  0 part  
sdc                                                        8:32   0 361.3G  0 disk  
└─1IBM_IPR-0_59D6110000003AF0                            254:6    0 361.3G  0 mpath 
sdd                                                        8:48   0 361.3G  0 disk  
├─sdd1                                                     8:49   0 361.3G  0 part  
└─1IBM_IPR-0_59D6110000003AD0                            254:5    0 361.3G  0 mpath 
  └─1IBM_IPR-0_59D6110000003AD0-part1                    254:7    0 361.3G  0 part  
sde                                                        8:64   0 361.3G  0 disk  
└─1IBM_IPR-0_59D6110000003AF0                            254:6    0 361.3G  0 mpath 
sdf                                                        8:80   0 361.3G  0 disk  
└─1IBM_IPR-0_59D6110000004150                            254:8    0 361.3G  0 mpath 
sdg                                                        8:96   0 361.3G  0 disk  
└─1IBM_IPR-0_59D6110000004150                            254:8    0 361.3G  0 mpath 
sdh                                                        8:112  0 361.3G  0 disk  
└─1IBM_IPR-0_59D6110000004170                            254:9    0 361.3G  0 mpath 
sdi                                                        8:128  0 361.3G  0 disk  
└─1IBM_IPR-0_59D6110000004170                            254:9    0 361.3G  0 mpath 
sdj                                                        8:144  0 361.3G  0 disk  
└─1IBM_IPR-0_59D6110000004190                            254:10   0 361.3G  0 mpath 
sdk                                                        8:160  0 361.3G  0 disk  
└─1IBM_IPR-0_59D6110000004190                            254:10   0 361.3G  0 mpath 
sr0                                                       11:0    1  1024M  0 rom   
sr1                                                       11:1    1  1024M  0 rom   
sr2                                                       11:2    1  1024M  0 rom   
linux-0a5l:~/avocado-misc-tests/io/disk # cat softwareraid.py.data/softwareraid.yaml 
scenario:
    disk: /dev/dm-10 /dev/dm-9 /dev/dm-8
raidlevel: !mux
    raidlinear:
        raid: linear
    raid0:
        raid: 0
    raid1:
        raid: 1
    raid5:
        raid: 5
    raid10:
        raid: 10
    raid6:
        raid: 6

**Comment by naveedus** [comment]
[job.log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/1010721/job.log.txt)

**Comment by vrbagalkote** [comment]
@naveedus @narasimhan-v @PraveenPenguin , If I understand correctly, this bug for Raid5 test being passed for three drives. And this is how it is supposed to work. Am I missing anything here. Please let me know.

Just FYI...


    RAID 0 – Block level striping. MD can handle devices of different lengths, the extra space on the larger device is then not striped.
    RAID 1 – Mirror.
    RAID 4 – Like RAID 0, but with an extra device for the parity.
    RAID 5 – Like RAID 4, but with the parity distributed across all devices.
    RAID 6 – Like RAID 5, but with two parity segments per stripe.
    RAID 10 – Take a number of RAID 1 mirrorsets and stripe across them RAID 0 style.

**Comment by naveedus** [comment]
Is the force option in the madadm command line creating RAID 5 array with two block device ?

**Comment by vrbagalkote** [comment]
Can you please try running the same command manually, and post the o/p here, if you see any difference??

**Comment by naveedus** [comment]
According to the MAN page for mdadam
"
  Normally the array will be started after it is assembled.   However  if
       --scan is not given and insufficient drives were listed to start a com-
       plete (non-degraded) array, then the array is  not  started  (to  guard
       against  usage  errors).   To  insist that the array be started in this
       case (as may work for RAID1, 4, 5 or 6), give the --run flag.
"
"
When creating a RAID5 array, mdadm will automatically create a degraded
       array  with  an  extra spare drive.  This is because building the spare
       into a degraded array is in general faster than resyncing the parity on
       a  non-degraded, but not clean, array.  This feature can be over-ridden
       with the --force option.
"

Hence using force option while creating a raid device is not recommended.

FYI:

# mdadm --create --verbose --assume-clean  /dev/md/mdsraid --level=5 --raid-devices=3 /dev/sdc5 /dev/sdc6   --spare-devices=1 /dev/sdc7 --run
mdadm: You haven't given enough devices (real or missing) to create this array

## mdadm --create --verbose --assume-clean  /dev/md/mdsraid --level=5 --raid-devices=2 /dev/sdc5 /dev/sdc6   --spare-devices=1 /dev/sdc7 
mdadm: layout defaults to left-symmetric
mdadm: layout defaults to left-symmetric
mdadm: chunk size defaults to 512K
mdadm: /dev/sdc5 appears to be part of a raid array:
       level=raid5 devices=2 ctime=Fri Jun  2 12:41:22 2017
mdadm: /dev/sdc6 appears to be part of a raid array:
       level=raid5 devices=2 ctime=Fri Jun  2 12:41:22 2017
mdadm: /dev/sdc7 appears to be part of a raid array:
       level=raid5 devices=2 ctime=Fri Jun  2 12:32:34 2017
mdadm: size set to 10477568K
Continue creating array? y     
mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md/mdsraid started.
[root@ltciofvtr-s822l2-lp1 ~]# mdadm --detail /dev/md126
/dev/md126:
        Version : 1.2
  Creation Time : Fri Jun  2 12:43:05 2017
     Raid Level : raid5
     Array Size : 10477568 (9.99 GiB 10.73 GB)
  Used Dev Size : 10477568 (9.99 GiB 10.73 GB)
   Raid Devices : 2
  Total Devices : 3
    Persistence : Superblock is persistent

    Update Time : Fri Jun  2 12:43:05 2017
          State : clean 
 Active Devices : 2
Working Devices : 3
 Failed Devices : 0
  Spare Devices : 1

         Layout : left-symmetric
     Chunk Size : 512K

           Name : mdsraid
           UUID : f7a7d849:22b6fda2:0bbc2b5a:6d7b0099
         Events : 0

    Number   Major   Minor   RaidDevice State
       0       8       37        0      active sync   /dev/sdc5
       1       8       38        1      active sync   /dev/sdc6

       2       8       39        -      spare   /dev/sdc7

**Comment by vrbagalkote** [comment]
@naveedus @narasimhan-v @PraveenPenguin , I think usage of "force" is justified, because the test case will have more code coverage, even with minimal HW. Having said that, if we give enough drives, test case will work as expected. So, in my opinion, if we remove "force" option we are reducing test case testing ability.

**Comment by narasimhan-v** [comment]
By just having a high level understanding, I think `--run` is something to be explored. I will try it in the next week.

Other than that, the current script works fine for the functionality it is expected to.

**Comment by PraveenPenguin** [comment]
@naveedus @vrbagalkote any update here

**Comment by vrbagalkote** [comment]
@PraveenPenguin , @narasimhan-v is looking into this.

**Comment by narasimhan-v** [comment]
@PraveenPenguin I will be the one to look into this issue, and since this does not give any false failures / passes, I am having this on a lower priority level.
Please assign it to me.

**Comment by PraveenPenguin** [comment]
@narasimhan-v have you get time to look on this issue if you think it not relevant can we close this ?

**Comment by narasimhan-v** [comment]
@PraveenPenguin It is still relevant. Thanks for reminding.
@naveedus Question: Is it fine if the fix is a yaml paremeter to indicate whether or not to use force option in the command to create raid ? If yes, I will do it immediately and you can verify.

**Comment by naveedus** [comment]
@narasimhan-v Yes, let me know when I can verify

**Comment by narasimhan-v** [comment]
@naveedus https://github.com/avocado-framework-tests/avocado-misc-tests/pull/881

**Comment by narasimhan-v** [comment]
@naveedus I want more clarity here.
When I tried with 3 disks, with and without --force, mdadm behaviour is same.
Can you explain more here.

```
# cat softwareraid.py.data/softwareraid.yaml 
disks: /dev/nvme0n1 /dev/nvme0n2 /dev/nvme0n3
run_test: True
force: False 
raidlevel: !mux
    raid5:
        raid: 5
    raid10:
        raid: 10
    raid6:
        raid: 6
metadata: !mux
    superblock-1.0:
        metadata: 1.0
# avocado run softwareraid.py -m softwareraid.py.data/softwareraid.yaml 
JOB ID     : 86ad473950a722c42d6d56a24dbe43b33a9a8796
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2018-05-15T11.05-86ad473/job.log
 (1/3) softwareraid.py:SoftwareRaid.test_run;superblock-1.0-raid5-f911: PASS (122.15 s)
 (2/3) softwareraid.py:SoftwareRaid.test_run;superblock-1.0-raid10-e8ad: PASS (122.46 s)
 (3/3) softwareraid.py:SoftwareRaid.test_run;superblock-1.0-raid6-ede1: FAIL (0.39 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 246.80 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2018-05-15T11.05-86ad473/results.html
```
```
# cat softwareraid.py.data/softwareraid.yaml 
disks: /dev/nvme0n1 /dev/nvme0n2 /dev/nvme0n3
run_test: True
force: True 
raidlevel: !mux
    raid5:
        raid: 5
    raid10:
        raid: 10
    raid6:
        raid: 6
metadata: !mux
    superblock-1.0:
        metadata: 1.0
# avocado run softwareraid.py -m softwareraid.py.data/softwareraid.yaml 
JOB ID     : d0596755fb5d9dd27b86e7870dfd336370b8d4b3
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2018-05-15T11.10-d059675/job.log
 (1/3) softwareraid.py:SoftwareRaid.test_run;superblock-1.0-raid5-dcd6: PASS (122.45 s)
 (2/3) softwareraid.py:SoftwareRaid.test_run;superblock-1.0-raid10-8f10: PASS (121.83 s)
 (3/3) softwareraid.py:SoftwareRaid.test_run;superblock-1.0-raid6-9955: FAIL (0.40 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 246.43 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2018-05-15T11.10-d059675/results.html
```

**Comment by naveedus** [comment]
```# mdadm --create --verbose --assume-clean /dev/md/mdsraid --level=5 --raid-devices=1 /dev/sda 
mdadm: '1' is an unusual number of drives for an array, so it is probably
     a mistake.  If you really mean it you will need to specify --force before
     setting the number of drives

]# mdadm --create --verbose --assume-clean /dev/md/mdsraid --level=5 --raid-devices=1 /dev/sda --force 
mdadm: at least 2 raid-devices needed for level 4 or 5
# mdadm --create --verbose --assume-clean /dev/md/mdsraid --level=4 --raid-devices=1 /dev/sda --force 
mdadm: at least 2 raid-devices needed for level 4 or 5
# mdadm --create --verbose --assume-clean /dev/md/mdsraid --level=6 --raid-devices=1 /dev/sda --force 
mdadm: at least 4 raid-devices needed for level 6
# mdadm --create --verbose --assume-clean /dev/md/mdsraid --level=10 --raid-devices=1 /dev/sda --force 
mdadm: at least 2 raid-devices needed for level 4 or 5
```

**Comment by narasimhan-v** [comment]
@naveedus Thanks.
With the above mdadm error message, and the previous comment, we can conclude that the test works as expected.
Closing the issue
