### ISSUE TITLE
Test suite IO net test HtxNicTest.test raises import error

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#694]
I installed Avocado (v55.0) from PyPi and added any additional dependencies with `sudo pip install -r https://raw.githubusercontent.com/avocado-framework/avocado/master/requirements.txt` as well. If I run the IO net test suite with `avocado run ~/avocado-misc-tests-master/io/net` an import error is raised during the execution of the test `HtxNicTest.test`.

The relevant log file content:

```
2017-11-09 11:28:28,958 test             L0965 ERROR| ERROR 04-/home/rc/avocado-misc-tests-master/io/net/htx_nic_devices.py:HtxNicTest.test -> TestError: Traceback (most recent call last):
  File "/home/rc/avocado-misc-tests-master/io/net/htx_nic_devices.py", line 23, in <module>
    from pexpect import pxssh
ImportError: No module named pexpect
```

**Comment by apahim** [comment]
That's a test dependency, not Avocado's:

https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/io/net/htx_nic_devices.py#L21-L23

You have to install it by yourself.

**Comment by fkromer** [comment]
> You have to install it by yourself.

Ok, the test is executed after installing with `[sudo] pip install pexpect`.
