### ISSUE TITLE
Run of DmaMemtest.test on embedded linux device leads to crash of Avocado

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#697]
If `DmaMemtest.test` is run with Avocado v55.0 on a memory constraint embedded linux device Avocado crashes due to a `RuntimeError`. However avocado "recovers from the crash" and continues the test suite execution. The test could be skipped for embedded devices like described in this [related issue](https://github.com/avocado-framework-tests/avocado-misc-tests/issues/689#issuecomment-343109694).

```
$ avocado run ~/avocado-misc-tests-master/memory/
JOB ID     : baf4c4fa2a346e2eaae33d5c8e4b25074b0a84ad
JOB LOG    : /home/rc/avocado/job-results/job-2017-11-09T17.19-baf4c4f/job.log
 (01/11) /home/rc/avocado-misc-tests-master/memory/dma_memtest.py:DmaMemtest.test: \
Avocado crashed: RuntimeError: maximum recursion depth exceeded in cmp
```

The related source code: [memory/dma_memtest.py class DmaMemtest(Test)](https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/memory/dma_memtest.py#L32)

**Comment by harish-24** [comment]
@fkromer Can you try increasing the ulimit for open files to a max and check?

**Comment by fkromer** [comment]
In many situations one is not able to modify the upper limit for open files within a test automation environment I guess (due to permission restrictions). Wouldn't it be reasonable to read the value and use it to configure the test?

(In my case the ulimit is comparably low.)

**Comment by fkromer** [comment]
I changed the upper limit for the user to the maximal value of `170906`. I get still a `RuntimeError: maximum recursion depth exceeded in cmp`. Does the test use the limit of the current user or another limit (e.g. the kernel specific limit)?

**Comment by harish-24** [comment]
@fkromer Can you share more details on the limits and the python version being used? Let me try with the same setup to hit the issue.

**Comment by fkromer** [comment]
@harish-24 In that setup I am using Python v2.7.6 and I have set the soft and hard limit for open files to the maximal value of `170906`. The other values gathered with `ulimit -a` are as follows:

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 13354
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 170906
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 100
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 13354
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by fkromer** [comment]
@harish-24 I can run the test on another BeagleBone Black (embedded device) with an [Ubuntu 16.04.3 image](https://elinux.org/BeagleBoardUbuntu#Ubuntu_.2816.04.3.29) as well. It is not the same Ubuntu version but could give us additional information...

**Comment by harish-24** [comment]
@fkromer Sure. Let know how it goes. I did not hit this issue with the same limits provided.

**Comment by fkromer** [comment]
In case someone want's to install `avocado` on the BeagleBone Black as well:

With the [BBB Ubuntu 16.04.3 image](https://elinux.org/BeagleBoardUbuntu#Ubuntu_.2816.04.3.29) (locales need to be configured before install of `avocado`) and probably [BBB Debian 9.1 LXQt image](https://debian.beagleboard.org/images/bone-debian-9.1-lxqt-armhf-2017-08-24-4gb.img.xz) as well use `sudo apt-get install liblzma-dev` before the installation of the additional `avocado` requirements with `sudo pip install -r https://raw.githubusercontent.com/avocado-framework/avocado/master/requirements.txt` (otherwise the installation of `pyliblzma` fails due to a problem with `liblzma`).

**Comment by PraveenPenguin** [comment]
@harish-24 @fkromer can we close this issue

**Comment by fkromer** [comment]
@PraveenPenguin Sure. (It is not solved yet but I won't have time to go continue with this and it has low prio for me.)

**Comment by harish-24** [comment]
@PraveenPenguin Sure, no issues for me.
