### ISSUE TITLE
Mutlipath.py script is failing

### ISSUE THREAD

**Issue by vrbagalkote** [avocado-framework-tests/avocado-misc-tests#704]
Hi,

Multipath.py script is failing. Attached is the job.log file. I have tried to run the script with dependency code which is still not merged in utils, still no luck. I have discussed this with @Naresh-ibm , and showed him the failure, he will be looking into this.

[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/1490308/job.txt)

**Comment by Naresh-ibm** [comment]
@vrbagalkote thanks for report. Will check this.

**Comment by Naresh-ibm** [comment]
https://github.com/avocado-framework/avocado/pull/2304
fixed, waiting to get merged.

**Comment by narasimhan-v** [comment]
Merged
