### ISSUE TITLE
DriverBindTest.test is canceled due to default pci device

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#712]
The test `CANCEL`s due to a not existing pci device.

```
$ avocado run avocado-misc-tests/io/driver/driver_bind_test.py:DriverBindTest.test --tap -
1..1
# debug.log of avocado-misc-tests/io/driver/driver_bind_test.py:DriverBindTest.test:
ok 1 avocado-misc-tests/io/driver/driver_bind_test.py:DriverBindTest.test  # CANCEL 0001:01:00.0 does not exist
```

Seems like the used pci device in the test leads to this `CANCEL` ([source code of the corresponding test setup](https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/io/driver/driver_bind_test.py#L44)). Would it be reasonable to make the used default pci dev somehow configurable?

**Comment by narasimhan-v** [comment]
@fkromer You can edit the yaml file. But changing the default device in the test does not make sense.

**Comment by PraveenPenguin** [comment]
@narasimhan-v @fkromer i think not seems me issue as via yaml file it  should work can we close this  ?

**Comment by narasimhan-v** [comment]
@PraveenPenguin yes.
