### ISSUE TITLE
Architecture dependent EEH tests fail on other architectures than powerpc

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#716]
The tests for pci ["enhanced error handling"](https://www.kernel.org/doc/Documentation/powerpc/eeh-pci-error-recovery.txt) are specific to the powerpc architecture:

```
$ avocado list ./io/pci
INSTRUMENTED ./io/pci/PowerNVEEH.py:PowerNVEEH.test_eeh_basic_pe
INSTRUMENTED ./io/pci/PowerVMEEH.py:PowerVMEEH.test_eeh_basic_pe
...
```

However they are not tagged with `power` or some other suitable tag ([`power` seems to be used for another class of tests](https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/cpu/cpupower.py#L31)):

```
$ avocado list ./io/pci --filter-by-tags=power
$
```

They fail on other architectures (observed on ARMv7):

```
avocado run ./io/pci/PowerNVEEH.py:PowerNVEEH.test_eeh_basic_pe
JOB ID     : f42b620a9dee655e5d2adef9812052e29ae8fce7
JOB LOG    : /home/rc/avocado/job-results/job-2017-11-29T14.37-f42b620/job.log
 (1/1) ./io/pci/PowerNVEEH.py:PowerNVEEH.test_eeh_basic_pe: ERROR (0.00 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 0.43 s
```

Excerpt from the log file `/home/rc/avocado/job-results/job-2017-11-29T14.37-f42b620/job.log`:
```
2017-11-29 14:37:19,157 test             L0965 ERROR| ERROR 1-./io/pci/PowerNVEEH.py:PowerNVEEH.test_eeh_basic_pe -> TestSetupFail: [Errno 13] Permission denied: '/sys/kernel/debug/powerpc/eeh_enable'
```

**Comment by fkromer** [comment]
`CANCEL` of the test during setup like in [io/pci/pci_hotplug.py:PCIHotPlugTest.test](https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/io/pci/pci_hotplug.py#L44) could be suitable.

**Comment by PraveenPenguin** [comment]
@fkromer sure seems  good solution to fix this issue . Would you like to send a pull request to fix this  ?

**Comment by fkromer** [comment]
@PraveenPenguin Sure, I can PR...

**Comment by vrbagalkote** [comment]
@fkromer thanks for the report...I have changed the script for other EEH test as well.
