### ISSUE TITLE
DlparPci.test fails on other systems than power4

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#717]
When executing the `DlparPci.test` on other systems than POWER4-based systems (observed on ARMv7) the test fails:

```
$ avocado run ./io/pci/dlpar.py:DlparPci.test
JOB ID     : e931b482c930a16041ee940377fba9558eac3965
JOB LOG    : /home/rc/avocado/job-results/job-2017-11-29T15.03-e931b48/job.log
 (1/1) ./io/pci/dlpar.py:DlparPci.test: ERROR (0.29 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 0.73 s
```

Excerpt from the log file:

```
2017-11-29 15:03:35,253 test             L0965 ERROR| ERROR 1-./io/pci/dlpar.py:DlparPci.test -> TestSetupFail: 'NoneType' object is not iterable
```

["DLPAR is available on POWER4–based System p systems with microcode updates dated October 2002 or later."](https://www.ibm.com/support/knowledgecenter/en/ssw_aix_72/com.ibm.aix.performance/dyn_log_part.htm)

**Comment by PraveenPenguin** [comment]
@vrbagalkote can you please look into this issue

**Comment by vrbagalkote** [comment]
@fkromer If I understand correctly, you are running on ARM processor right? 

When you say other than Power4, on which machine have you tried? Also can you please share your yaml parameters , and if possible complete job.log file.

Thanks in advance,
Venkat.

**Comment by fkromer** [comment]
@vrbagalkote Yes, I am running on ARM, more specific on ARMv7. I am running the tests on another processor (ARM Cortex-A8) as well right now. As I want to diff the logs of all tests for both systems first I have not changed the yaml parameters from the defaults yet.

**Comment by vrbagalkote** [comment]
@fkromer Can you please give required yaml parameters, as specified in Redame file and try once?

**Comment by PraveenPenguin** [comment]
@fkromer have you got chance to try @vrbagalkote suggestion ?

**Comment by fkromer** [comment]
@PraveenPenguin No. Unfortunately I won't have time to go continue with this and it has low prio for me. From my side we can close it.

**Comment by PraveenPenguin** [comment]
@fkromer sure thanks closing now , if you try again face same issue please re open
