### ISSUE TITLE
Test results of run on embedded linux system

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#719]
I executed tests on an embedded linux device (BeagleBone Black) using an [Ubuntu 16.04.3 demo image](https://elinux.org/BeagleBoardUbuntu#Ubuntu_.2816.04.3.29). How shall I provide the results to you? (I am not sure if it is suitable to paste it here as people shouldn't but could use that in production?)

**Comment by narasimhan-v** [comment]
@fkromer You could upload it to some cloud storage and give us permission.

**Comment by fkromer** [comment]
@narasimhan-v I've send you an email and granted access to web storage with test suite run results (cpu, generic, memory, perf) and other relevant information.

**Comment by fkromer** [comment]
@PraveenPenguin I've send you an email as well.

**Comment by fkromer** [comment]
To setup the Ubuntu 16.04.3 demo image for the tests proceed as follows. Install the [demo image onto a sd card](https://elinux.org/BeagleBoardUbuntu#Ubuntu_.2816.04.3.29). Perform a minimal setup of the demo image:

```
ssh ubuntu@<ip-address>
(pwd: temppwd)
(ubuntu@arm:~$)
# to install pip (python)
sudo apt-get install software-properties-common
sudo apt-add-repository universe
sudo apt-get update
sudo apt-get install python-pip
# configure locales (otherwise install of avocado fails)
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
sudo dpkg-reconfigure locales
```

Proceed with the usual installation of `avocado` afterwards.

**Comment by fkromer** [comment]
Issue closed as possible support for additional embedded linux systems will be an ongoing process.
