### ISSUE TITLE
Question: Relation of tests to other frameworks

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#720]
The `README` states that a lot of tests are ported from `autotest`. Some tests like `/cpu/pmqa.py:Pmqa.test` seem to be ports from the [Linaro Power Management test suite](https://wiki.linaro.org/WorkingGroups/PowerManagement/Resources/TestSuite/PmQaSpecification) ([Linaro test definitions](https://git.linaro.org/qa/test-definitions.git)). Does someone know about other relations like these. It would be helpful to have some kind of "mapping" to determine coverage and avoid duplication (in case several frameworks are in use).

**Comment by narasimhan-v** [comment]
@fkromer Usually the docstring and `README` of the test are placeholders for such informtion

**Comment by fkromer** [comment]
@narasimhan-v Ok. Means after generating Sphinx docs I could search docstrings. Could the `README`s of the tests parsed somehow?

**Comment by narasimhan-v** [comment]
@fkromer I am not aware of any way to do that via some tool.

**Comment by fkromer** [comment]
@narasimhan-v Me neither.
