### ISSUE TITLE
Avago storage adapter tests fail on systems without adapters

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#725]
When executing the test suite `io/disk` with `avocado run ./io/disk` and default configuration (no modification of yaml files, etc.) the tests for the Avago storage adapter `FAIL` (with `io_disk.log` as log file of the test suite run):

```
$ cat io_disk.log | sed -n -e 's/^.*| FAIL //p'
...
31-./io/disk/Avago_storage_adapter/avago9361.py:Avago9361.test_display -> TestFail: Failed to display the version of the tool
32-./io/disk/Avago_storage_adapter/avago9361.py:Avago9361.test_adjustablerates -> TestFail: Failed to show the rate
33-./io/disk/Avago_storage_adapter/avago9361.py:Avago9361.test_set_on_off -> TestFail: Failed to show the deatils of {0}restorehotspare
```

**Comment by vrbagalkote** [comment]
@fkromer Plz provide parameteres specified in Readme file. Yes script will fail, and is expected if no values are given.

**Comment by fkromer** [comment]
@vrbagalkote My system does not have an Avago storage adapter. It makes no sense to specify the parameters then. I thought the test would be `CANCEL` when the test is run as part of the whole test suite `io/disk`.

**Comment by fkromer** [comment]
@vrbagalkote Probably it is possible to check for hw raid controllers with `lspci | grep -i raid` like [described here](https://supportex.net/blog/2010/11/determine-raid-controller-type-model/).

**Comment by vrbagalkote** [comment]
@fkromer Looking into this...

**Comment by PraveenPenguin** [comment]
@vrbagalkote any update on this ?

**Comment by fkromer** [comment]
@PraveenPenguin No. But if you want to close it just go for it. (It is not solved yet but I won't have time to go continue with this and it has low prio for me.)

**Comment by PraveenPenguin** [comment]
closing this as no response from user
