### ISSUE TITLE
Suggestion: Inform users about potentially harmful tests

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#730]
Some tests like [trinity](https://github.com/avocado-framework-tests/avocado-misc-tests/blob/6ab5b21b84d5c2458e11c536765e701e876e9eef/fuzz/trinity.py) ([its README](https://github.com/avocado-framework-tests/avocado-misc-tests/blob/6ab5b21b84d5c2458e11c536765e701e876e9eef/fuzz/trinity.py.data/README)) can be harmful to the environment of the system under test (not only the system under test itself). It could be a good idea to inform potential users of this project right on the landing page ([README](https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/README.rst)) about that.

**Comment by narasimhan-v** [comment]
@fkromer @PraveenPenguin Good suggestion to have a generic way of indicating harmful tests. Would it be better to have tagging of harmful tests with a keyword, like `harmful` for example ?

**Comment by PraveenPenguin** [comment]
@narasimhan-v @harish-24 let's discuss which is test cases are  ```harmful``` and will tag those test case , till that time we can leave this issue as open

**Comment by PraveenPenguin** [comment]
we can use Tag mechanism most for the test we have this so closing this
