### ISSUE TITLE
Test SmartctlTest.test fails on systems without hard and solid-state drive

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#734]
The test `./io/disk/smartctl.py:SmartctlTest.test` is not suitable for systems without a disk with support for SMART (a lot of ATA/SATA and SCSI/SAS hard drives and solid-state drives). A `CANCEL` would be suitable.

**Comment by narasimhan-v** [comment]
@naveedus Can you please check this one ?

**Comment by fkromer** [comment]
One could check for hard disks with `sudo lshw -class disk` which gives in case of a single ATA disk an output containing `description: ATA Disk`. Even if `eMMC` devices are present in the system they will not be contained in the output.

**Comment by fkromer** [comment]
**Improvement**

If the system uses an eMMC the use of `mmc-utils` could be suitable to implement a health check ([superuser - Check health of eMMC](https://superuser.com/questions/1181300/check-health-of-emmc)). `badblocks` (in package `e2fsprogs`) could possibly be used as well. In comparison with SMART `badblocks` it writes simple patterns to every block of a device and then reads and checks them searching for damaged areas instead of passively waiting for errors [archlinux - badblocks](https://wiki.archlinux.org/index.php/badblocks).

Executing a non-destructive eMMC test could be executed with `badblocks -nsv /dev/mmcblk0`. Remotely executing a `badblocks` based eMMC check could be done as follows:

```
#!/usr/bin/env python
# execute with: python check_mmc.py

from pexpect import pxssh
import re

try:
    s = pxssh.pxssh()
    hostname = "<IP-ADDRESS>"
    username = "rc"
    password = "<PASSWORD>"
    s.login(hostname, username, password)
    rootprompt = re.compile('.*[$#]')
    s.sendline('sudo -s')
    i = s.expect([rootprompt,'assword.*: '])
    if i==0:
        print "didnt need password!"
        pass
    elif i==1:
        print "sending password"
        s.sendline(password)
        j = s.expect([rootprompt,'Sorry, try again'])
        if j == 0:
            print("password accepted")
            pass
        elif j == 1:
            raise Exception("bad password")
    else:
        raise Exception("unexpected output")
    s.set_unique_prompt()
    s.sendline('badblocks -nsv /dev/mmcblk0')
    s.prompt()
    print(s.before)
    s.logout()
except pxssh.ExceptionPxssh as e:
    print("pxssh failed on login.")
    print(e)
```

However this will only work for eMMC devices which are not in use. For devices in use you get an output like this:

```
$ python check_mmc.py 
sending password
password accepted
badblocks -nsv /dev/mmcblk0
/dev/mmcblk0 is apparently in use by the system; it's not safe to run badblocks!
```
