### ISSUE TITLE
Test Sysbench.test does not install sysbench during setup

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#737]
The test `generic/sysbench.py:Sysbench.test` does not install `sysbench` during setup. A manual installation (on Ubuntu with `sudo apt-get install sysbench`) is required.

**Comment by PraveenPenguin** [comment]
@fkromer thanks for reporting , all test case which is required sudo privileged, you need to run through sudo 

as example `sudo avocado run generic/sysbench.py ` or you tried to provide sudo password of running terminal once , it will help to run test without sudo but you need to increase  session time out  
you can play with visudo with following param 
`Defaults        env_reset,timestamp_timeout=30`

**Comment by PraveenPenguin** [comment]
@fkromer there was some issue in  sysbench test  fixed it in  #741 now it should works for you

**Comment by fkromer** [comment]
@PraveenPenguin It is working for me now:

```
$ sudo apt-get purge sysbench
...
$ sudo avocado run generic/sysbench.py:Sysbench.test
JOB ID     : 38e12b6a72b6ea40e3b27f4b7ce4a2af15e4d991
JOB LOG    : /home/rc/avocado/job-results/job-2017-12-05T10.15-38e12b6/job.log
 (1/1) generic/sysbench.py:Sysbench.test: PASS (36.71 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 41.38 s
```

**Comment by PraveenPenguin** [comment]
@fkromer thanks , will wait for #741  to merge

**Comment by PraveenPenguin** [comment]
closing this issue as #741 already merged
