### ISSUE TITLE
Test suite generic/lshw.py is ERROR due to package installation during setup

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#738]
The test suite `generic/lshw.py` fail as `ERROR` with `TestSetupFail: Fail to install lshw required for this test.` because the package `lshw` is not installed during setup. After manual installation with `sudo apt-get install lshw` on Ubuntu the tests run without any problems. (`Lshwrun.test_lshw_verification` and `Lshwrun.test_lshw_options` require explicit configuration.)

**Comment by harish-24** [comment]
@fkromer Could you run the test using "sudo" from cmdline and check?

**Comment by fkromer** [comment]
I tried it again after "restore" of initial system state with `sudo apt-get purge lshw`. The ERROR doesn't show up when executed with `sudo`. Is it suitable to add the `priviledged` tag to the [test](https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/generic/lshw.py#L22)?

**Comment by harish-24** [comment]
@fkromer Not sure about that. Because most of the test installs some primary/dependency packages. In that case I guess most of the tests are `privileged`. @narasimhan-v @PraveenPenguin Can you comment on this?

**Comment by sacsant** [comment]
Per man page for lshw command 
"NOTES
       lshw  must be run as super user or it will only report partial information."

We should add privileged tag to this test case.

**Comment by PraveenPenguin** [comment]
PR #785 address this issue

**Comment by fkromer** [comment]
@harish-24 Right. For me it is sufficient to know that I need to run as `su`. I am just asking because the tagging as `privileged` is inconsistent. For a user either having "all" test tagged or no test would be easier to understand. Probably one could skip `privileged` completely then.

**Comment by PraveenPenguin** [comment]
closing this issue as PR #785 merged , @fkromer if this solution not works for you please feel free to reopen
