### ISSUE TITLE
Test Xfstests.test depends on replaced package

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#744]
On Ubuntu 14.04 the test status is `CANCEL` due to  `TestCancel: Fail to install libtool-bin required for this test.`. The reason for that is that `libtool-bin` has been replaced by `libtool`.

**Comment by fkromer** [comment]
The distro could be checked like [here](https://github.com/avocado-framework-tests/avocado-misc-tests/blob/837fd88fb185943f77281bdb7b90de095dff0d69/perf/aiostress.py#L46) for conditional setup for ubuntu.

**Comment by harish-24** [comment]
@fkromer You are right. `libtool-bin` was available after 14.04 from Ubuntu. Please feel free to make all the changes necessary to support 14.04. Thanks for reporting.

**Comment by harish-24** [comment]
@fkromer Yes. `distro.detect().version` would give you that.

**Comment by fkromer** [comment]
@harish-24 If your are not working on this already I can PR.

**Comment by harish-24** [comment]
@fkromer Sure, you can start with it.

**Comment by PraveenPenguin** [comment]
closing this issue as already PR merged
