### ISSUE TITLE
Question: Best practices how to select, configure and execute overall test sets

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#749]
I want to define a custom set of tests which shall be run as part of a build job (e.g. "smoke test"). I would like to *select*, *configure* and *execute* them. What possibilities do I have

- to define test sets,
- to configure these tests and
- to execute the tests?

As far as I know the configuration of tests happens in test specific `.yaml` files. It is possible to include several `.yaml` configurations into a single file, see https://github.com/avocado-framework-tests/avocado-misc-tests/issues/729#issuecomment-349070274. But w.r.t. to maintenance I am not sure if it is a really good option. (One limitation is that the execution order of the tests may vary.)

The tests may be executed on a directory basis (test suite) e.g. `sudo avocado run io/net/` which executes all tests of this "suite". Tests can be executed on a file basis (usually several tests per file). It is possible to execute single test classes specifically with e.g. `sudo avocado run generic/lshw.py:Lshwrun` or single tests with `sudo avocado run generic/lshw.py:Lshwrun.test_lshw_verification`.

Right now the information about which tests shall be executed is stored in the command line invocation of `avocado` e.g. `avocado run io/net/ sleeptest.py generic/lshw.py:Lshwrun  generic/lshw.py:Lshwrun.test_lshw_verification`. Are there alternatives to this approach?

**Comment by apahim** [comment]
Have you played with test tags? http://avocado-framework.readthedocs.io/en/56.0/WritingTests.html#categorizing-tests
That would cover the "to define test sets" phase, but not the "configuration" of those tests. For that, there's a card under discussion: https://trello.com/c/jcRIUNoB/1085-add-default-params-variants-sources.

**Comment by fkromer** [comment]
@apahim Yes. For me it is not that clear what tests are executed/skipped when white/blacklisting tests with tags. Right now I would prefer to have total control about which tests are executed (and with what configuration). Thanks for the trello card hint. I am looking forward to progress in this direction.

**Comment by apahim** [comment]
The level of control over the Job execution you're looking for is expected to be achieved when the Job API is ready: https://www.redhat.com/archives/avocado-devel/2016-April/msg00014.html
But there are no commitments to the deadline for its implementation so far.
