### ISSUE TITLE
error_cleanup prevents from execution of generic test suite

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#750]
[generic/error_cleanup.py](https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/generic/error_cleanup.py#L34) leads to a "hard coded" test status of `ERROR`. Means it is unsuitable to be executed in test suites. Is it a test for `avocados` teardown functionality? Is it suitable to move the test or inform users about that it should not be used in test suites?

**Comment by PraveenPenguin** [comment]
@narasimhan-v what you say on this , i think we can  remove this test as it is kind of example

**Comment by narasimhan-v** [comment]
sure

**Comment by balamuruhans** [comment]
@narasimhan-v @PraveenPenguin https://github.com/avocado-framework-tests/avocado-misc-tests/pull/781

**Comment by PraveenPenguin** [comment]
@balamuruhans thanks , closing as PR already merged
