### ISSUE TITLE
Question: Configuration of pmqa.py test

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#751]
In my system I don't want to allow some governors. If the corresponding tests run they are "skipped" by `pm-qa` which results in an overall test status of `pmqa.py` as `FAIL`. Is it possible to configure the test `cpufreq_05` that it does just execute the tests for specific governors?

**Comment by PraveenPenguin** [comment]
@fkromer yes make sense we can skip those test case on this case

**Comment by PraveenPenguin** [comment]
@shriyak can you please have a look on this
