### ISSUE TITLE
Suggestion: Tagging of remote execution only tests

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#754]
Seems like some tests like [`generic/pstore.py`](https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/generic/pstore.py) are suitable for remote execution only. Would it make sense to tag them accordingly like e.g. `remote`?

**Comment by fkromer** [comment]
To find `remote` only tests I searched for `"from virttest import remote"`:

* avocado-misc-tests/generic/kdump.py
* generic/pstore.py

**Comment by PraveenPenguin** [comment]
closing this issue as PR got merged , @fkromer thanks for suggestion as well PR
