### ISSUE TITLE
Test module_unload_load.sh is not executed as part of the test suite "io driver"

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#756]
When executing the io_driver test suite with `sudo avocado run io/driver/` the test [module_load_unload.sh](https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/io/driver/module_unload_load.sh) is not executed.

**Comment by PraveenPenguin** [comment]
@Naresh-ibm i think you are also facing same issue

**Comment by PraveenPenguin** [comment]
@fkromer can you try now it should work , #758 solved this issue @Naresh-ibm thanks for PR

**Comment by fkromer** [comment]
@PraveenPenguin My cloned `avocado-misc-tests` contain the commit with the file permission changes `git show 8b4e9a4e9` of the PR. However if I list the files in the cloned directory the file is not executable:

```
$ ll io/driver/
total 32
drwxrwxr-x 4 rc   rc   4096 Jan  3 11:53 ./
drwxrwxr-x 7 rc   rc   4096 Jan  3 10:55 ../
-rwxrwxr-x 1 rc   rc   2426 Jan  3 10:55 driver_bind_test.py*
-rw-r--r-- 1 root root 2291 Jan  3 11:53 driver_bind_test.pyc
drwxrwxr-x 2 rc   rc   4096 Jan  3 10:55 driver_bind_test.py.data/
-rw-rw-r-- 1 rc   rc    576 Jan  3 10:55 io_driver.yaml
-rw-rw-r-- 1 rc   rc   2874 Jan  3 10:55 module_unload_load.sh
drwxrwxr-x 2 rc   rc   4096 Jan  3 10:55 module_unload_load.sh.data/
```
