### ISSUE TITLE
memory/transparent_hugepages_defrag.py: No Memory Defragmentation

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#795]
[thp-defrag.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/1701840/thp-defrag.txt)
THP defrag test fails with this error:
No Memory Defragmentation 2651 hugepages before turning khugepaged on, 2651 After it

TestFail: No Memory Defragmentation
2651 hugepages before turning khugepaged on,
2651 After it

**Comment by PraveenPenguin** [comment]
closing this as i think recent changes fix this issue , @abdhaleegit if you still feeling issue is there please re open

**Comment by harish-24** [comment]
@PraveenPenguin I think this is not fixed yet. Should be re-opened.

**Comment by PraveenPenguin** [comment]
@harish-24 Thanks for pointing will reopen , @abdhaleegit are you facing on recent code base as well

**Comment by PraveenPenguin** [comment]
@abdhaleegit waiting for your comment

**Comment by harish-24** [comment]
@abdhaleegit From what has been observed there is no way to guarantee that kernel always de-frags memory, kernel always tries to do that but there exist an chance when system memory could not be de-fragmented which is what has happened here.

I feel we should close this or if someone has a suggestion to enhance the test it would be good to adopt.
