### ISSUE TITLE
memory/libhugetlbfs.py : counters.sh (16M: 64): FAIL for 4K pagesize kernel

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#796]
One of the libhugetlbfs test fails on kernel with Power8 4K and Power7 64K pagesize kernel

counters.sh (16M: 64):\x09FAIL Line 330: Bad HugePages_Total: expected 0, actual 1

[libhugelog.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/1701844/libhugelog.txt)

**Comment by PraveenPenguin** [comment]
@abdhaleegit seems me issue on OS can you please raise it against distro
