### ISSUE TITLE
sysbench: make failed with error "No support for PowerPC 64 bit mode (yet)

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#814]
The test builds https://github.com/akopytov/sysbench.git
It fails to build on baremetal with CentOS 
logs:
Running 'make install'
Making install in third_party/luajit
make[1]: Entering directory `/var/tmp/avocado_CYCczK/third_party/luajit'
make -C ./luajit clean
make[2]: Entering directory `/var/tmp/avocado_CYCczK/third_party/luajit/luajit' 
make -C src clean
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^

**Comment by PraveenPenguin** [comment]
@abdhaleegit can you please check #821 if this solve your problem

**Comment by PraveenPenguin** [comment]
@abdhaleegit can you please check this , i think commit is in , if you it works for you please close this
