### ISSUE TITLE
Use netplan to configure network interface on Ubuntu 17.04 and later

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#848]
with Ubuntu 17.04 and later network configuration has change. Now we have netplan to setup network and bridge setup.

The following things are changed:
1. network service command :   netplan --debug apply
2. network config path :  /etc/netplan/<x>-netcfg.yaml
3. network bridge configuration : use the yaml to add bridge entry
4. network persistent interface setup:  add entry in netplan yaml

so fix network testcases where the above functionality is implemented, which includes:
io/net/bridge.py
io/net/ethtool/ethtool.sh
io/net/htx_nic_devices.py

**Comment by PraveenPenguin** [comment]
@abdhaleegit  is this still a issue , if not can we close this ?

**Comment by abdhaleegit** [comment]
will be handeld in avocado tool
