### ISSUE TITLE
avocado-misc-tests/memory/transparent_hugepages_defrag.py test case reports test case as FAIL, incorectly.

### ISSUE THREAD

**Issue by vrbagalkote** [avocado-framework-tests/avocado-misc-tests#868]
Hi,

avocado-misc-tests/memory/transparent_hugepages_defrag.py is reported as fail, for expected behaviour. This seems to be like corner case, which needs to handled.

Complete job log can be made available privately.

Regards,
Venkat.

**Comment by harish-24** [comment]
We can close this as #795 is in place. @vrbagalkote Please close this and follow up on #795.
