### ISSUE TITLE
pci/pci_info_lsvpd : pci.py", line 185,  AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#903]
the test fails with this error on bare-metal

 Traceback (most recent call last):
 File "/root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/pci/pci_info_lsvpd.py", line 57, in test
   sys_slot = pci.get_slot_from_sysfs(pci_addr)
 File "/usr/lib/python2.7/site-packages/avocado_framework-61.0-py2.7.egg/avocado/utils/pci.py", line 185, in get_slot_from_sysfs
   slot = re.match(r'((\w+)[.])+(\w+)-P(\d+)-C(\d+)|Slot(\d+)', slot).group()
AttributeError: 'NoneType' object has no attribute 'group'

local variables:
-> vpd_output <type 'dict'>: {'slot': 'PLX Slot1', 'devices': ['raid'], 'pci_id': '10009361'}

**Comment by abdhaleegit** [comment]
this PR will fix this problem : https://github.com/avocado-framework/avocado/pull/2637

**Comment by PraveenPenguin** [comment]
@abdhaleegit  i see llib has above patch if it works for you can we close this ?
